### ISSUE TITLE
Duplicate ambiguous method names

### ISSUE THREAD

**Issue by Yenyenx** [Excel-DNA/ExcelDna#10]
Hi,
I'm currently using Excel-DNA to interface my current C# project with excel. When compiling my own project, I have no restriction on the public static method names as far as C# compiler is happy, excel-dna is too. I mean that nothing prevents the user from defining multiple public static methods with the exact same names and different arguments. The method the XLL will/should call, is ambiguous. In practice, one of the methods is picked by Excel-DNA... but which one ?
I would be nice to detect such cases at compile time or at run-time and to return an exception such as "Ambiguous function call". What do you think ?
Rgds,
Yenyenx

**Comment by govert** [comment]
Sounds good. I've recently been doing some work at improving the diagnostic logging, in particular to help find registration errors. I'll see if I can add your problem case to the warnings or errors list.

**Comment by govert** [comment]
This is now handled as a error event with the new logging mechanism. By default an error display will appear if there is more than one method with the same name, marked with an ExcelFunction attribute.
