### ISSUE TITLE
[v0.34] RTD server with persistent GUID - immediate update of RTD formulas when opening a document

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#102]
This problem is new for 0.34; it was working fine in 0.33.9. (I'm testing it in Excel 2016)

**Comment by govert** [comment]
I made some changes to the `ExcelRtdServer.ConnectData` implementation that should cause an immediate update when the sheet is loaded. I think this is the normal RTD behaviour, but it was hidden by the implementation before.

I think this commit is the important one: https://github.com/Excel-DNA/ExcelDna/commit/696669e91c4a5d8476e97f8f50a20a0720152397

Your RTD server can prevent this by setting the RTD topic value to `ExcelError.ExcelErrorNA` - the Excel won't update.

How does this impact your usage?

**Comment by fandrei** [comment]
> Your RTD server can prevent this by setting the RTD topic value to ExcelError.ExcelErrorNA - the Excel won't update.

Ok, will try it.

> How does this impact your usage?

Not refreshing RTDs when opening a document is one of important requirements. They pull data from a server, and there can be lots of them in a document.

**Comment by govert** [comment]
Your RTD server still decides when to make the back-end calls. So although your RTD server is started and the topics connected, you need not connect to the back end, and if you have a persistent RTD server registration, you can indicate to Excel in the `ConnectTopic` that the old values should be used.

Basically this gives you more control in the RTD server then with the previous version. I need this for a good implementation of the IObservable streaming, which is problematic if it does not restart.

**Comment by govert** [comment]
I have learnt a bit more about this behaviour, and I now think it works like this.

It is possible for the RTD Server ConnectData to run, without the wrapping UDF running. This will happen in the following scenario:
* A sheet is saved with an active topic called from a UDF, and the topic value (not the UDF return value) is a non-error value (possible any non-#N/A value, but I'm not sure).
* The sheet is closed and re-opened.
* The RTD Server is started by Excel - this succeeds if the add-in is loaded and still has the same path, or if the RTD Server is persistently registered.
* ConnectData is called for the ExcelRtdServer.Topic.
* In previous Excel-DNA versions, changes to the Topic value inside ConnectData would trigger a NotifyUpdate and hence a recalculation of the UDF.
* In version 0.34 of Excel-DNA, there is no automatic UpdateNotify if ConnectData returns the same value as Topic.Value.
* In the case where there is no UpdateNotify, the UDF does not automatically recalculate.
* In this scenario, the RTD Server is started and the Topic is created, but the UDF not recalculated. The cell keeps its value as when saved.

Another scenario is where the Topic value is saved as "#N/A". In this case, re-opening the sheet will not do a ConnectData on the Topic at all.

There is some interaction with the `newValues` parameter - if this is passed in as false, and kept as false in the ConnectData, and ConnectData returns Topic.Value - then there should be no update of the cell.

Note that the default value of Topic is "#N/A" and this can only be changed without triggering UpdateNotify by overriding `ExcelRtdServer.CreateTopic`.

**Comment by fandrei** [comment]
@govert, I've created a repro project. https://github.com/fandrei/RtdRefreshRepro

RtdRefreshRepro1 - Excel-DNA version 0.33.9, retains the RTD value correctly when opening a saved document (see the Doc folder)
RtdRefreshRepro2 - Excel-DNA version 0.34.4-rc3, the saved RTD value is reset to #N/A when opening

Please check if you can reproduce this on your PC.

**Comment by govert** [comment]
OK - I will check this evening.

**Comment by govert** [comment]
@fandrei  The problem is in the case where newValue = false (which happens when you open the book with existing topics. You need to return the same value as the topic has at that point - which is "#N/A" as you have it. But the topic internally stores a COM error wrapper for the "#N/A", so the comparison fails when you actually set it.

Try the code like this:

```cs
        protected override object ConnectData(Topic topic, IList<string> topicInfo, ref bool newValues)
        {
            Trace.WriteLine($"--------- RtdServer.ConnectData(newValues = {newValues})");

            base.ConnectData(topic, topicInfo, ref newValues);

            if (newValues)
                topic.UpdateValue("TEST - " + DateTime.Now);

            return topic.Value;
        }
```

**Comment by fandrei** [comment]
@govert, it seems to work fine this way, thanks.
