### ISSUE TITLE
Recalculation of RTD formulas results in #N/A

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#103]
A simplistic RTD is declared like this:

```
        [ExcelFunction(Category = "RtdMinimalAddin", IsVolatile = false, IsThreadSafe = false, IsMacroType = true, IsExceptionSafe = true)]
        public static object RtdMinimal1()
        {
            var res = XlCall.Excel(XlCall.xlfRtd, Const.RtdServerProgId, Const.RtdServerGuid, "TEST");
            return res;
        }
```

The server:
```
    [ComVisible(true)]
    [ProgId(Const.RtdServerProgId), Guid(Const.RtdServerGuid)]
    [ClassInterface(ClassInterfaceType.AutoDispatch)]
    public class RtdServer : ExcelRtdServer
    {
        protected override bool ServerStart()
        {
            return base.ServerStart();
        }

        protected override object ConnectData(Topic topic, IList<string> topicInfo, ref bool newValues)
        {
            base.ConnectData(topic, topicInfo, ref newValues);

            // NOTE temporary workaround until ExcelDNA let's modifying topic's value without change notification
            var valueField = topic.GetType().GetField("_value", BindingFlags.NonPublic | BindingFlags.Instance);
            valueField.SetValue(topic, "TEST_" + topic.TopicId);

            if (newValues)
                return topic.Value;
            else
                return ExcelError.ExcelErrorNA;
        }
    }
```
Steps:
Write a test workbook with a RtdMinimal1 formula
Close and reopen it
Hit Ctrl+Alt+Shift+F9 (recalculate all)
The RTD formula returns #N/A instead of any value

(as of the latest release version)

**Comment by fandrei** [comment]
My mistake, disregard this.

**Comment by fandrei** [comment]
(tweaked code a little bit)

**Comment by govert** [comment]
I would not expect setting the private field to have any effect.

Is this related to the batch update issue: https://github.com/Excel-DNA/ExcelDna/issues/104

**Comment by fandrei** [comment]
@govert 
> I would not expect setting the private field to have any effect.

It works fine if the document is not reopened.

> Is this related to the batch update issue: #104

No, it's related to the problem that doesn't let setting topic's value without sending an immediate update notification.

**Comment by govert** [comment]
@fandrei Why would you set a topic's value without wanting it updated in Excel?

The only reason I could think of was (from this discussion: https://groups.google.com/forum/#!topic/exceldna/VH4yLEMsDz0 ) if you want to be sure that different topics are updated atomically. For example you want to be sure that a 'price' topic and a 'volume' topic are updated in a single calculation, and the multi-threaded nature of the RTD updates might cause a race condition between the topic updates and the Excel callback that reads the values.

For this case I suggested we add a batch update mechanism.

You can also derive your own Topic class, and add other information (like a "nextValue") that you use as a temporary storage space until you're ready to update Excel. But the Topic Value is currently interwoven with the update mechanism in `ExcelRtdServer`, so I wouldn't expect sensible behaviour if you interfere with the abstraction via reflection.

**Comment by fandrei** [comment]
@govert, because in many cases its value is already known in ConnectData and triggering another update would involve lots of extra work, as there can be hundreds thousands of RTD functions in the document.

**Comment by govert** [comment]
@fandrei Is this not fixed by these commits:
* f1150b5325ff57895590689bd2dae3f1b3980a2d
* 696669e91c4a5d8476e97f8f50a20a0720152397

which have this effect:

  * Calls to Topic.UpdateNotify during the ConnectData overload are now always ignored.
  * If the topic value is updated (through Topic.UpdateValue) during ConnectData, and the same value is returned from ConnectData,
  then no spurious UpdateNotify is raised.
  * If the value returned from ConnectData differs from Topic.Value, UpdateNotify will still be raised.
