### ISSUE TITLE
Pb when using HttpWebResponse with ExcelDna

### ISSUE THREAD

**Issue by akasolace** [Excel-DNA/ExcelDna#106]
Hello,
 I have a sample code trying to download csv file from ecb wesite (see code below)
The code works well from console app but fails if called from excel addin: it exits at the last line without giving any error messages.
I use exceldna extensively and it is the first time I see a calid c# code not running through excel call.
Do you see what could go wrong here? 

Thank you in advance for your help !!

BR

`
            string url = "https://sdw-wsrest.ecb.europa.eu/service/data/YC/B.U2.EUR.4F.G_N_A+G_N_C.SV_C_YM.?lastNObservations=1";
HttpWebRequest req = (HttpWebRequest)WebRequest.Create(url);             
req.Accept = "application/vnd.ecb.data+csv;version=1.0.0";             
req.KeepAlive = true;             
HttpWebResponse resp = (HttpWebResponse)req.GetResponse();`

**Comment by govert** [comment]
@akasolace I suggest you wrap the call in a `try` - `catch` block and return the information from the exception. Maybe that can give a clue about what is going wrong.

**Comment by akasolace** [comment]
So I put a try catch and the error message is : `{"The remote server returned an error: (400) Bad Request."}`
but such error is not returned when I call the same function from a console app.
I even compare the request object created through the addin call and through the console app call, and all parameters are strictly the same!

**Comment by govert** [comment]
You might like to try a tool like Fiddler to debug this.

**Comment by akasolace** [comment]
I haven't managed to explain the bug, but for your info I managed to get what I wanted by using a WebClient object instead of an HttpWebResponse object. Surprisingly, despite they are really close, the former is not subject to the bug.

**Comment by govert** [comment]
Closing this, as I don't think it's really an Excel-DNA issue.
Please re-open if you want to track it further.

**Comment by akasolace** [comment]
For sake of clarity, both version of the code are working in Visual Studio, but the version using HttpWebResponse crashes when called from Excel. Hence, it looks to me it is an Excel-DNA issue but I am not 100% sure.

**Comment by govert** [comment]
@akasolace You're welcome to reopen the issue - maybe someone else is intrigued and wants to dig into this.

**Comment by caioproiete** [comment]
@akasolace Can you put a sample project on GitHub that reproduces the error, so we can try to debug?

**Comment by akasolace** [comment]
@caioproiete Is a sample code posted here is sufficient or do you expect it as a file attachement?

**Comment by caioproiete** [comment]
Hi @akasolace, actually yes the source code you pasted above is enough to reproduce the problem, and I was able to confirm that this issue only occurs inside an Excel-DNA Add-in.

I didn't spend too much time investigating it, but my gut feeling is that it is related to the way Excel-DNA loads the .NET Framework into the Excel process - which must be different than running a Console app directly.

The size of the response coming through is relatively large, so my guess is that there are some defaults in terms of "max request/response size" that are being applied in Excel-DNA, which are different than the defaults in a normal .NET app.

My guess is based on the fact that the following code works fine inside an Excel-DNA add-in:
```
const string url = "https://www.google.com";
var request = (HttpWebRequest)WebRequest.Create(url);
using (var response = (HttpWebResponse) request.GetResponse())
{
    //...
}
```

And the only difference here is the size of the response, compared to your URL above.

I think it makes sense to re-open this issue, so it can be looked at more closely.

**Comment by akasolace** [comment]
@caioproiete, thank you for having looked into it already.  
As I mentioned in my original post, using a WebClient instead of an HttpWebRequest works well thought ...
Do you want me to reopen the issue or do you expect @govert to do it?

**Comment by caioproiete** [comment]
@akasolace Great. As for reopening the ticket, I'll leave it up to you.

**Comment by akasolace** [comment]
@caioproiete I am not that familiar with Github, am I supposed to see a reopen button or do you expect me to create a new issue ?

Thank you for your help

**Comment by govert** [comment]
OK, I'm reopening the issue.

**Comment by govert** [comment]
Closing again.
