### ISSUE TITLE
"The parameter is incorrect" during .xll pack due to locale issue

### ISSUE THREAD

**Issue by rosecodym** [Excel-DNA/ExcelDna#115]
Hi,

When I build from master, ExcelDnaPack.exe is failing for me with this error:
```
9>  System.ComponentModel.Win32Exception: The parameter is incorrect
9>     at ResourceHelper.ResourceUpdater.RemoveResource(String typeName, String name)
9>     at ExcelDnaPack.PackProgram.Pack(String[] args)
9>     at ExcelDnaPack.PackProgram.Main(String[] args)
```
It's occurring in ResourceHelper.cs on line 203:
`bool result = ResourceHelper.UpdateResource(_hUpdate, typeName, name, localeNeutral, IntPtr.Zero, 0);`

I bisected it to commit b5f0124ea3e66e6f3290d7039c5659ccb24f635a - reverting the change to this file from that changeset (changing `LocaleNeutral` to `LocaleUS`) makes this issue go away, but I assume it was done for some reason in the first place, so that's not a "fix."

This is occurring for me on en-US Windows 7, in both the 32-bit and 64-bit versions of the packer.

(This wasn't introduced by my recent patch; I'd actually reverted that commit locally to work around this issue and didn't bring it up in the PR.)

**Comment by govert** [comment]
@rosecodym I think you get that when you're using the wrong ExcelDna.xll (or ExcelDna64.xll) base file. I changed the locales to simplify the configuration a bit, but if you've got a mismatched or old .xll file, the ExcelDnaPack will break.

**Comment by rosecodym** [comment]
@govert That was exactly it, thanks!
