### ISSUE TITLE
Running on Linux/Mono

### ISSUE THREAD

**Issue by obadz** [Excel-DNA/ExcelDna#12]
Do you think there's any way to pack XLLs on Linux?

When I try, I get the following error:

```
Using base add-in Blah-AddIn.xll

Unhandled Exception:
System.EntryPointNotFoundException: BeginUpdateResource
  at (wrapper managed-to-native) ResourceHelper:BeginUpdateResource (string,bool)
  at ResourceHelper+ResourceUpdater..ctor (System.String fileName) [0x00000] in <filename unknown>:0 
  at ExcelDnaPack.PackProgram.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.EntryPointNotFoundException: BeginUpdateResource
  at (wrapper managed-to-native) ResourceHelper:BeginUpdateResource (string,bool)
  at ResourceHelper+ResourceUpdater..ctor (System.String fileName) [0x00000] in <filename unknown>:0 
  at ExcelDnaPack.PackProgram.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Same error wether I download the binaries or build from source.

**Comment by govert** [comment]
Are you kidding me?

**Comment by obadz** [comment]
Not at all..

Right now I do all my dev work on Linux and run a quick .bat on a Windows VM to invoke ExcelDnaPack and produce the XLL. Then I send that file to my users..

There's a lot that works on Linux already:
- ExcelDNA.Integration & Registration build fine
- ExcelDnaPack.exe builds fine (and even when I run it on Windows I use the one I built on Linux)
- ExcelDnaPack.exe runs fine when simply printing the help message

So really all that's missing is the ability to run ExcelDnaPack for real and have it actually produce the packed XLL.

I'm not sure what's involved.. Maybe there's a low level code into some Excel stuff and if so the answer might be that it's just not possible, but I figured I'd ask.

**Comment by govert** [comment]
OK - that's a bit weird for Excel development.

The problem when running ExcelDnaPack is that it uses the Window APIs to pack the files into the .xll (which is a regular Windows PE .dll file). The Windows Resource APIs are called via P/Invoke. You might be able to configure WINE on Linux so that it works. The relevant APIs are all in kernel32.dll, and are declared in the ResourceHelper file: https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDnaPack/ResourceHelper.cs. Excel is not involved with ExcelDnaPack at all.

**Comment by obadz** [comment]
Okidok, thanks.  Will have a look at some point.

**Comment by govert** [comment]
Are you compiling with Roslyn on Mono?
I guess they must have some plan for embedding resources into the PE file, as part of the regular C# resource embedding.

**Comment by obadz** [comment]
For what it's worth I gave it a try, hooked it up to kernel32.dll in Wine and now getting this error:

```
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Using base add-in Blah.xll
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) ResourceHelper.BeginUpdateResource (string,bool) <0xffffffff>
  at ResourceHelper/ResourceUpdater..ctor (string) <0x0007b>
  at ExcelDnaPack.PackProgram.Main (string[]) <0x0041b>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	mono() [0x4b76c8]
	mono() [0x50ce4e]
	mono() [0x429468]
	/nix/store/i0l0jjkk82wsqz9z5yhg35iy78bjq684-glibc-2.21/lib/libpthread.so.0(+0x103e0) [0x7f75a29e63e0]

Debug info from gdb:

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted
```

**Comment by obadz** [comment]
Compiling on Mono

**Comment by obadz** [comment]
Some more information printed when running at a higher debug level:

```
Mono: DllImport attempting to load: '/nix/store/694dbnlhqkm0z7lhbzzwsb9af5azp6kp-wineWow-1.6.2/lib64/wine/kernel32.dll.so'.
Mono: DllImport loaded library '/nix/store/694dbnlhqkm0z7lhbzzwsb9af5azp6kp-wineWow-1.6.2/lib64/wine/kernel32.dll.so'.
Mono: DllImport searching in: '/nix/store/694dbnlhqkm0z7lhbzzwsb9af5azp6kp-wineWow-1.6.2/lib64/wine/kernel32.dll.so' ('/nix/store/694dbnlhqkm0z7lhbzzwsb9af5azp6kp-wineWow-1.6.2/lib64/wine/kernel32.dll.so').
Mono: Searching for 'BeginUpdateResource'.
Mono: Probing 'BeginUpdateResource'.
Mono: Could not find 'BeginUpdateResource' due to '/nix/store/694dbnlhqkm0z7lhbzzwsb9af5azp6kp-wineWow-1.6.2/lib64/wine/kernel32.dll.so: undefined symbol: BeginUpdateResource'.
Mono: Probing 'BeginUpdateResource'.
Mono: Could not find 'BeginUpdateResource' due to '/nix/store/694dbnlhqkm0z7lhbzzwsb9af5azp6kp-wineWow-1.6.2/lib64/wine/kernel32.dll.so: undefined symbol: BeginUpdateResource'.
Mono: Probing 'BeginUpdateResourceA'.
Mono: Found as 'BeginUpdateResourceA'.
```

**Comment by DanielArndt** [comment]
@obadz Did you ever come up with a solution to this? 

Believe it or not, I have attempted the same thing and run into the same issue 3 years later. I know very little about the windows world, so my understanding of their packaging/dll/xll systems is minimal.

I've chalked this up as a dead end for now, but if you had any success I'd be interested to hear.

**Comment by obadz** [comment]
@DanielArndt, no I gave up and was building stuff on Windows. Gave up on .NET altogether eventually..

**Comment by gzmp** [comment]
I have a quick related question (hope I'm not gravedigging the thread here). Is there any way to use C# code on Linux (i.e. with either Mono or .NET Core 2.2) to call functions in an XLL that was created using ExcelDNA?

**Comment by obadz** [comment]
I don't think that's possible but not sure.
