### ISSUE TITLE
Excel Live Preview feature (Excel 2010 and later) breaks QueueAsMacro

### ISSUE THREAD

**Issue by bpierce88** [Excel-DNA/ExcelDna#123]
Microsoft introduced a feature called "Live Preview" in Excel 2010 that will preview what a paste operation will look like (hover over one of the paste buttons, and it shows what the cells will look like once the button is clicked). If QueueAsMacro is called while this preview is being shown, something in ExcelDna breaks such that methods passed to QueueAsMacro are no longer executed. The Excel process must be killed and restarted before these calls will work again.

Pasted below is code that updates a cell by calling QueueAsMacro repeatedly...not a recommended practice, but it makes it easy to recreate the issue. If you call the START() method from Excel, the cell 2 rows below will start ticking. If you then invoke the Excel Live Preview feature (just copy any range of cells, then right click somewhere else and hover over one of the paste buttons to see the "live preview" of what the paste will look like) then the ticking will stop. The QueueAsMacro calls are no longer working.

This is a relatively high risk issue because Live Preview is enabled by default in Excel 2010 and later, and with almost any paste operation a user invokes it at least momentarily (as they hover over a paste button for a fraction of a second before clicking it). Even if QueueAsMacro is called infrequently, it could be called while Live Preview is invoked. Users can disable Live Preview to avoid this risk, but in practice that may only happen after something bad happens due to data being stale.

I've confirmed that this occurs in both the .33.9 release and in the latest release candidate.

Here's the code that illustrates the issue:

using System;
using System.Threading;
using System.Threading.Tasks;
using ExcelDna.Integration;

namespace LivePreviewBreaksQueueAsMacro {
    public class LivePreviewBreaksQueueAsMacro : IExcelAddIn {
        public void AutoOpen() {
            ExcelIntegration.RegisterUnhandledExceptionHandler(e => { return "UNHANDLED EXCEPTION: " + e.ToString(); });
        }
        public void AutoClose() { }
    }

    public static class QueueAsMacroCaller {

        private static bool _started;

        [ExcelFunction]
        public static string START() {
            try {
                if (!_started) {
                    _started = true;
                    var callerRef = XlCall.Excel(XlCall.xlfCaller) as ExcelReference;
                    var targetRef = new ExcelReference(callerRef.RowLast + 2, callerRef.RowLast + 2, callerRef.ColumnLast, callerRef.ColumnLast, callerRef.SheetId);
                    UpdateTarget(targetRef, 0);
                }
                return "Started";
            } catch (Exception e) {
                return e.Message;
            }
        }

        private static void UpdateTarget(ExcelReference targetRef, int newVal) {
            ExcelAsyncUtil.QueueAsMacro(() => {
                try {
                    targetRef.SetValue(newVal);
                } catch(Exception e) {
                    var msg = e.Message;
                }

                Task.Run(() => {
                    Thread.Sleep(250);
                    UpdateTarget(targetRef, ++newVal);
                });
            });
        }
    }
}

**Comment by govert** [comment]
@bpierce88 Thanks for reporting this - I can reproduce the issue.

The fact that the QueueAsMacro never recovers is due to an internal flag saying "busy running macros" that is not being reset. I'm trying to figure out how this might happen, but I think I will be able to fix it...

**Comment by bpierce88** [comment]
Cool -- thanks for looking so quickly. I'm glad to do additional testing anytime when you have a build with a fix.

**Comment by govert** [comment]
I think this check-in should fix it. There was an unexpected result from the failing `Application.Run` call - instead of an error variant (which is converted to an exception) Excel returns the error code as an integer. The Excel-DNA code now also looks for this unexpected return value and will retry later.

There should be a new NuGet preview in the next week or so, after the recent build fixes are incorporated.

**Comment by bpierce88** [comment]
Awesome! Will look for the new NuGet package - thanks!
