### ISSUE TITLE
RTD server doesn't start

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#126]
I have this problem on one of my PCs; the call to RtdRegistration.RegisterRtdServerTypes() method in Excel-DNA is successful, but the RTD server is never instantiated. I don't see any RTD-related errors in the diagnostic log.
Using Excel-DNA 0.34.4-rc3

**Comment by govert** [comment]
1. Can you confirm with this small project: https://github.com/Excel-DNA/Samples/tree/master/RtdClocks/RtdClock-ExcelRtdServer

2. Can you check that there's nothing under 'Disabled Items' under the Add-Ins options page?

3. Can you check the security / Trust Center settings for anything suspicious?

**Comment by fandrei** [comment]
@govert, my bad, it was in disabled items.
I wonder if it's possible to make Excel-DNA issue some diagnostic message in such a case?

**Comment by garethhayter** [comment]
You need to check two things to determine whether the add-in has been disabled:

- Check disabled items in registry: Software\Microsoft\Office\<EXCEL_VERSION>\Excel\Resiliency\DisabledItems
- Check Trust Center settings in registry: is OK if either of these are missing:
- 1) Software\Microsoft\Office\<EXCEL_VERSION>\Excel\Security
- 2) Software\Microsoft\Office\<EXCEL_VERSION>\Excel\Security\RequireAddinSig

**Comment by fandrei** [comment]
@garethhayter this should do the trick, thanks.
It may be useful to add functionality for checking this into Excel-DNA itself as this problem is not uncommon.

**Comment by garethhayter** [comment]
Yes. My FormulaDesk add-in checks for these on startup and displays this form which allows users to re-enable. Of course, Excel needs to be re-started before the changes take effect:
![image](https://cloud.githubusercontent.com/assets/1400090/24381150/35611af2-13ab-11e7-9718-5856ae6401d1.png)

**Comment by fandrei** [comment]
@garethhayter good idea.

**Comment by govert** [comment]
I've added a new issue to track this suggestion (https://github.com/Excel-DNA/ExcelDna/issues/141), and will close this one.
