### ISSUE TITLE
Home page is out of date

### ISSUE THREAD

**Issue by sharpe5** [Excel-DNA/ExcelDna#128]
Excel-DNA is being actively developed, as proven by the activity on GitHub.

However, the homepage mentions a "last update" from 2012, for version 0.30:

https://excel-dna.net/

In addition, CodePlex is shutting down, so homepage references should be pointed at GitHub.

It's possible that some developers may skip Excel-DNA, as they might feel the project is not being updated? If so, it's an easy fix!

**Comment by caioproiete** [comment]
Thanks @sharpe5!

**Comment by govert** [comment]
OK - I've fixed the last update info on the home page, and we've opened a separate issue to track moving that site to GitHub, where it will be easier to keep up-to-date.
