### ISSUE TITLE
XlCall.Excel(XlCall.xlGetName) from Ribbon throws unhandled exception

### ISSUE THREAD

**Issue by interdrift** [Excel-DNA/ExcelDna#13]
I get an ExcelDna.Integration.XlCallException after trying to access XlCall.Excel(XlCall.xlGetName) from a ribbon. 

The same accessing technique works if I use it from an UDF.

![new bitmap image 2](https://cloud.githubusercontent.com/assets/5409106/8205502/f0d46544-14f9-11e5-9f86-da8462155cae.jpg)

The error comes from over here :

![new bitmap image 2](https://cloud.githubusercontent.com/assets/5409106/8205625/dda69f4a-14fa-11e5-9e28-8e59c4f8fc76.jpg)

**Comment by govert** [comment]
This is similar to our discussion in issue #6 - the C API is not available in the ribbon callback context. You can either use the COM object model, or schedule a macro with `ExcelAsyncUtil.QueueAsMacro`.

**Comment by govert** [comment]
Oh - if you just want to get the full path of the .xll, you can safely call `ExcelDnaUtil.XllPath` from any context.

**Comment by interdrift** [comment]
Aha, I see now, so operations executed from the ribbon are executed on a different thread. 
Yeah I was just wondering what was causing this. :+1:  Thanks again.

**Comment by govert** [comment]
No - I don't think it's a different thread. It's just that the Excel C API is not available in that context.
