### ISSUE TITLE
Fix to AssemblyManager.cs to check for loaded assembly in resolve event handler

### ISSUE THREAD

**Issue by crater19** [Excel-DNA/ExcelDna#132]
In the AssemblyResolve event of AssemblyManager.cs a dictionary of assembly name to assembly is maintained to avoid reloading assemblies that have already been loaded.
That dictionary is added to at two points in the routine.
I found that after checking whether an assembly is already in the dictionary, when loading a particular assembly using Assembly.Load - this call to load can actually trigger the resolve event to be called again for the same assembly (behaviour due to the assembly being loaded). What this means is that the dictionary is populated by one call and so the original call throws an exception when it attempts to insert same assembly in to the dictionary.
Fix would be to test whether the dictionary has been updated since first check by calling ContainsKey on the dictionary

1st attempt:
            loadedAssembly = GetAssemblyIfLoaded(assemblyName);
            if (loadedAssembly != null)
            {
                loadedAssemblies.Add(name, loadedAssembly);
                return loadedAssembly;
            }

2nd attempt later in AssemblyResolve:
		loadedAssembly = Assembly.Load(assemblyBytes);
	        loadedAssemblies.Add(name, loadedAssembly);
                return loadedAssembly;

I am suggesting a check is made for existence of the "name" just before the second attempt to Add on loadedAssemblies

**Comment by govert** [comment]
Do you know what it is in your assembly that triggers the re-entrant call?

**Comment by govert** [comment]
@crater19 I've pushed an update that should fix this - the NuGet package version is 0.34.6-rc6. Could you check whether it works for you?

**Comment by crater19** [comment]
That works thanks.
