### ISSUE TITLE
Function return #N/A when volatile parameter is refreshed.

### ISSUE THREAD

**Issue by ionutovidiu** [Excel-DNA/ExcelDna#145]
1.Add the following UDF to your addin
[ExcelFunction( Name = "NaTest" )]
public static object NaTest( [ExcelArgument] object param )
{
  return 10;
}

2.Open the attached workbook
3.Copy range B28:B29
4.Right click in cell B31
5.Go to "Paste Options" and move the mouse over "Transpose", then over "Formatting".

Notice that cells B7:B8 and all dependent cells are now #N/A. The NaTest UDF is not called when that happens.
If NaTest is replaced with a standard Excel function (e.g. LEN) this does not happen.
NaTest use a reference to a cell that contains a volatile function. It seems that when the volatile function is refreshed the dependent UDFs are not called and just returns #N/A.
[NaIssue.xlsx](https://github.com/Excel-DNA/ExcelDna/files/1362862/NaIssue.xlsx)

**Comment by govert** [comment]
I can't reproduce this with Excel 2016 version 1711.
It doesn't like like something we could deal with in Excel-DNA if it were an Excel issue anyway.

Please re-open if you want me to look at it some more.
