### ISSUE TITLE
New Feature Suggestion: Modifying the Tell Me More Hyperlink

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#149]
(**on behalf of Andrew Lockhart who [sent this request on the mailing-list](https://groups.google.com/forum/#!topic/exceldna/zC4i86_Y7AA)**)

---

Our current Ribbon has tips and supertips that we can modify via the RibbonXML, but it seems that it isn't not possible to modify the "Tell Me More" and Addin Name Hyperlink that appears in a custom ribbon in Excel 2013 and above.
I've seen lots of complaints about this and the accepted answer is that this can't be changed.

I believe MS refers to this as the `ToolTipFooterTitle` and  `ToolTipFooterDescription` as seen here: https://msdn.microsoft.com/en-us/library/system.windows.controls.ribbon.ribbonradiobutton.tooltipfootertitle(v=vs.110).aspx but it doesn't look like Excel exposes this.

Obviously at a low level this can be changed if you are willing to intercept windows messages etc etc, something that 99% of developers don't want to or can't do - myself included. But perhaps inside ExcelDNA it could be done once with an easy interface exposed. Ideally I would like to be able to say in the .dna file for my given DnaLibrary what the toplevel hyperlink should be set to. That would be really nice.

**Comment by caioproiete** [comment]
@govert [wrote](https://groups.google.com/forum/#!topic/exceldna/zC4i86_Y7AA):

> The ribbon screenTips and superTips display is different in current Excel 2016 versions - the whole "Tell me more" story is only displayed for a few built-in controls, and not for custom ribbon controls at all. Also there are configuration options that control which parts of the screeTip and superTip to display.
> 
> Since the confusing hyperlink is gone, maybe this is not an issue anymore.
> 
> From the IntelliSense work I can say that fiddling with the Excel user interface at the low level is incredibly time consuming.
> I'd be happy to do more of it on an exorbitant hourly contract rate  ... ;-)
> 

https://groups.google.com/forum/#!topic/exceldna/zC4i86_Y7AA

**Comment by ahm3dhany** [comment]
@govert @augustoproiete 
Dears,

Is this behavior (i.e., appearance of "Tell me more") related to office version?.. it seems it happens with Office 2016 but not in 2019 & Office 365.
