### ISSUE TITLE
Decorate Excel-DNA plugin with ReSharper attributes

### ISSUE THREAD

**Issue by imanushin** [Excel-DNA/ExcelDna#156]
To help ReShaper analyze code better, it is better to decorate API with set of special attributes:
1. ```ExcelFunctionAttribute``` can be decorated as [MeansImplicitUseAttribute](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#MeansImplicitUseAttribute). So, ReShaper will understand, that method, which was decorated by ```ExcelFunctionAttribute```, is called from Reflection API
2. XlCall methods can be decorated with NotNull/CanBeNull attributes (to show warnings in the compile time)
3. There are different ways, how to reference attributes:
3.1 Add dependency and exclude it from nuget package. Code will work fine even if end-used will not have this library in the AppDomain. However, ReSharper will understand dependencies
3.1 Generate internal implementation (e.g. with internal visibility, [file will be like this](https://github.com/imanushin/CheckContracts/blob/master/CheckContracts/Properties/JetBrainsAttributes.cs)) ReSharper annotations from MSVS and add them into final dlls. So, ReShaper will able to read internal method (and do appropriate highlighting), however end-user will not see them.

**Comment by caioproiete** [comment]
LGTM.

The approach 3.2 seems safer as it doesn't require any unresolved dependencies that could possibly break reflection-based analysis developers might do on their end (that we don't know of).

Can we just copy your [`JetBrainsAttributes.cs`](https://github.com/imanushin/CheckContracts/blob/master/CheckContracts/Properties/JetBrainsAttributes.cs) as is, or are there any changes required?

**Comment by imanushin** [comment]
@caioproiete , yes, of course. It is better (for my opinion) to ask ReSharper to generate this file (to have latest version of attributes). Will do this a bit later in separate branch.

**Comment by caioproiete** [comment]
> @caioproiete , yes, of course. It is better (for my opinion) to ask ReSharper to generate this file (to have latest version of attributes). Will do this a bit later in separate branch.

Awesome. Feel free to send a PR directly then, with the correct file!
