### ISSUE TITLE
xlGetInstPtr is null

### ISSUE THREAD

**Issue by konne** [Excel-DNA/ExcelDna#160]
Hi,

I try to use the following function:

https://msdn.microsoft.com/en-us/library/office/ff475872.aspx

with: var o =  XlCall.Excel(XlCall.xlGetInstPtr);

but o is always null. I also tried XlCall.Excel(XlCall.xlGetInstPtr, new object[] { 0 });

Any advice?

thx Konrad

**Comment by govert** [comment]
I don't think Excel-DNA supports the xlBigData return type from xlGetInstPtr.

You can also get the Process Id via `System.Diagnostics.Process.GetCurrentProcess().Id`, and the instance handle via P/Invoke and the Windows API.

Do you have a specific need for this?

**Comment by konne** [comment]
I allow in my excel plugin that each "Excel" Document can connect to different datasources. I have in the background different instance of my Classese that holds the connection,... That I now need is a separation for the different Classes per Workbook from the static udf and ribbon functions. I used till now the Hwnd but this is not okay, because it returns always the top visible window.
I liked to have a fast XLCall function because in need to call it in every UDF and this can be 10.000 per Workbook.

**Comment by govert** [comment]
`xlInstPtr` won't work for that case anyway - it refers to the Excel process and not the particular workbook.

For the UDFs you can call `xlfCaller` and use the `SheetId` in the resulting `ExcelReference`. You have to sort out to bookkeeping to keep track of the sheets, but that should be fast.

**Comment by konne** [comment]
thx, I will try and close now this issue
