### ISSUE TITLE
unregister UDFs for language changes

### ISSUE THREAD

**Issue by konne** [Excel-DNA/ExcelDna#163]
in my plugin I allow a instant change of the UI language, this is working great for all Dialogs and the Ribbons.
I try now to implement this for UDF.
I can dynamic register the UDFs with ExcelIntegration.RegisterXX and add so dynamic Descriptions,...
I already tried to change with reflection the ExcelFunctionAttributes, but this is parsed only during registering, so changes are not visible.
I see now only the chance on a change of the language to unregister the UDFs and register them with new attributes.

Any better idea?

**Comment by govert** [comment]
Unregistering the UDFs is not supported - there's a fair amount of plumbing needed to make it work which is not implemented at the moment.

You can split your UDFs into a completely separate .xll, and then unload and reload this extra .xll from your 'main' add-in using the ExcelIntegration.UnregisterXLL(...) helper.

**Comment by konne** [comment]
If I split the UDFs, what you think is the best way that the "Main.XLL" and the "UDF.XLL" communicate with each other?

As a side question comming out of your suggestion. If I would like to implement a SelfVersionUpdate feature, that I implement an updater XLL, that deregisters the mainXLL, load a new from the internet and registers that after this is loaded?

**Comment by govert** [comment]
Maybe have some hidden UDF functions that you can call back and forth, or using environment variables.

I've started working on some plans for the second question - how to make add-in distribution, and updating easier. One snag at the moment is that add-ins with a Ribbon (or RTD features like async) won't unload properly.

**Comment by konne** [comment]
thx, I will close the issue

thx for the hint that unload is not working properly. I have seen that behauvior, but I thought I do someting wrong. Good to know that this is general problem.
