### ISSUE TITLE
Is there a way to Log who uses which function

### ISSUE THREAD

**Issue by vincentbeaulieu** [Excel-DNA/ExcelDna#165]
Hi,
I would like to have some sort of Log of who uses which function.
I have a file call log.json which is like this
```
{
   "userName":
      {
         "function1":8,
         "function2":17
      },
   "userName2":
      {
         "function1":2
      }
}
```
I am using Newtonsoft.Json to Deserialize and Serialize this file to check if the user is there, if he already used this function, if yes I add 1 to the number, if no, I create the Dictionary in the code accordingly and add 1 after.
After that, I Serialize my Dictionary and replace the text in my file by the new one.

My problem is that I am opening and closing this file A LOT of times... If I make 10,000 calls in Excel, this process is gonna slow down my calculation time by a lot... not counting if more than one user is using this addin at the same time... Please note that the path is going to be share for all users.

Do you have any ideas? I thought about keeping the Dictionary in Cache for the whole Excel session and writing to the file at the end, but there might be problem since multiple users, would use Excel at the same time and we would have conflicts...

Here is my Log function if interested:
```
using Newtonsoft.Json

...
public static void Log(string functionName)
{
        string path = @"C:\log.json";
        string text = File.ReadAllText(path);
        var current = JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, int>>>(text);
        var userName = Environment.UserName;

        if (current.ContainsKey(userName))
        {
            if (current[userName].ContainsKey(functionName))
            {
                current[userName][functionName]++;
            }
            else
            {
                current[userName].Add(functionName, 1);
            }
        }
        else
        {
            current.Add(userName, new Dictionary<string, int> {{functionName, 1}});
        }
        var newText = JsonConvert.SerializeObject(current);
        File.WriteAllText(path, newText);
}
```
Thanks for your time.

**Comment by caioproiete** [comment]
Hey @vincentbeaulieu we use this to track bugs and feature requests. For regular questions yours, the best place is our [mailing-list on Google Groups](https://groups.google.com/forum/#!forum/exceldna) or [StackOverflow (using the `excel-dna` tag)](https://stackoverflow.com/questions/tagged/excel-dna)

**Comment by govert** [comment]
The Excel-DNA Registration extensions have a sample that weaves logging into the function calls. See https://github.com/Excel-DNA/Registration/blob/master/Source/Samples/Registration.Sample/FunctionLoggingHandler.cs
