### ISSUE TITLE
I can't debug my ribbon code in VS 2010

### ISSUE THREAD

**Issue by ghostjiao** [Excel-DNA/ExcelDna#168]
I write a ribbon code in .DNA file, it has some buttons.  then add callback sub to them.
i want to know the compile process，so i aput some breakpoints in VS. when i press F5, the excel start , and the ribbon is ok. but when i press the button, it can't stop at breakpoints and the sub directly complete.
could anybody help me to deal with this problem? Thank a lot!

**Comment by govert** [comment]
Do you have a separate .dll project with this ribbon callbacks, or are the callbacks also inside the .dna file?
If the callbacks are inside the .dna file, you can’t debug them.

Sometimes Visual Studio will attach the wrong kind of debugger. You can follow this procedure:

  *   Start Excel without your add-in.
  *   Attach the Visual Studio debugger to the Excel process, selecting the correct debugger type – Managed (v4.x…)
  *   Then load your add-in into Excel by pressing File -> Open
  *   The add-in should load and breakpoints should work.

You can put the ribbon .xml code inside the .dll too – see the step-by-step instructions here: https://github.com/Excel-DNA/Samples/tree/master/Ribbon
But I don’t know if VS 2010 supports the NuGet packages.

-Govert

**Comment by ghostjiao** [comment]
thanks a lot for  Govert's kindly response. i will try this.
