### ISSUE TITLE
more information about UDFs

### ISSUE THREAD

**Issue by ghostjiao** [Excel-DNA/ExcelDna#169]
I remembered there was a page for UDFs ,the page showed what kind of parameters ExcelDna UDFs can accept and how to use excel reference e.g. 
but I can't find this page in excel-dna.net and github.
I am a new learner, could anyone tell me where it is. thanks a lot!

![default](https://user-images.githubusercontent.com/26499223/37556710-b623e778-2a34-11e8-92a6-9b05ec9a6f58.PNG)

the link in above picture can't be open

**Comment by govert** [comment]
I copied some stuff here: https://github.com/Excel-DNA/ExcelDna/wiki/Old-Reference

**Comment by ghostjiao** [comment]
thanks a lot!Best regards!
