### ISSUE TITLE
Exception as flow control - QueueAsMacro in Protected View

### ISSUE THREAD

**Issue by Mad-Lynx** [Excel-DNA/ExcelDna#172]
It's not really big deal, but it definitely can be improve. As we would not have to throw and cache exception.
(this ticket probably should be labeled "enhancement", not "bug" 😉 )

Description
--
In version v0.34.6 we are able to execute `ExcelDnaUtil.Application` from Protected View and we will receive object.
The problem is... in this mode we will be unable to run macros and the [`Run` method will fail](https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.Integration/ExcelSynchronizationContext.cs#L379) throwing TargetInvocationException, then we will cache this and recognize as `NAME_NOT_FOUND` ComException.
This will result to schedule "try again" in 250 ms... and the process begin all over.
So we will try to do it 4 times per second - so every second Excel will throw 4 exception, totally unnecessary.
And if you have debugger attach, you will see the flow of error messages in output window.

Solution
--
If we are in "Protected View", we can assume that we will unable to run macros, so maybe we can add something similar to `IsInFormulaEditMode` and make shortcut - "skip the try, because if will fail anyway".

**Comment by govert** [comment]
@Mad-Lynx I've made some updates to the `QueueAsMacro` and `ExcelDnaUtil.Application` code that should resolve this for the Protected View case (and some others). But there are still cases where you'll see the exception stream, like when a dialog is open. That's harder to detect in general, so I'm not really sure it's worth it

I've updated the source, and pushed to NuGet as ExcelDna.AddIn version 0.35.1-beta2. Any feedback appreciated.
