### ISSUE TITLE
"Unsupported signature, abstract or generic" error

### ISSUE THREAD

**Issue by ishiikurisu** [Excel-DNA/ExcelDna#173]
I am trying to implement a method with the following signature:

``` c#
public static double[] Evaluate(string[] actions, string[] criteria, double[] weights, double[,] ranking)
```

but when I try to load the AddIn into Excel, I get the following error:

```
Initialization [Error] Method not registered - unsupported signature, abstract or generic: 'Model.Evaluate'
```

Does anyone know how to fix it?

**Comment by govert** [comment]
Using the Excel-DNA Registration extensions it's possible to automatically add the `object[]` -> `string[]` (or any other) type conversion, but mostly it's easier to just define it as `object[]` and deal with it in your function.

**Comment by ishiikurisu** [comment]
I changed the signature as suggested and worked. Thanks!
