### ISSUE TITLE
How to efficiently load DataTable in C# to Excel?

### ISSUE THREAD

**Issue by WestXu** [Excel-DNA/ExcelDna#174]
Currently I'm using transformating DataTable to ADODB.Recordset, and use Range.CopyFromRecordset method to load it to excel. But the transform function I found on the internet is rather complex and always can be buggy. Is there any other way to do this?

**Comment by govert** [comment]
I suppose you're in a macro context (e.g. driven from a ribbon button or something similar).
(For user-defined functions called from a worksheet formula you'd need a different approach.)

For a large range you can call `Range.Value` passing in an `object[,]` array with simple primitives (strings and doubles). To build this array from a DataTable might be easier that making a Recordset, and should be faster.

**Comment by WestXu** [comment]
That's a great idea. I'll do this right away. Thanks! ;)
