### ISSUE TITLE
xladdinmanagerinfo pop up in a two xll's (excel dna and c++ xll) context

### ISSUE THREAD

**Issue by MisesEnForce** [Excel-DNA/ExcelDna#178]
We developed a fairly robust xll with excel dna since several years and using it without any problem. Recently we had to use it at the same time with another xll that is developed with microsoft's excel c++ api.

Sometimes, when executing a vba's selection calculate (triggered by a command key combo) that involves any range (not even a range using ours xll's or the new one's functions a debug msgbox pops up, containing "xlAddInManagerInfo(0)".

https://msdn.microsoft.com/en-us/library/office/bb687853.aspx

We double-checked in the c++ xll's code, no (debug or release) call to this function is ever performed. No xlcall/frmwrk dll the c++ xll links to performs any (debug or release) call to this funtion neither.

Are you aware of such an issue when using an excel dna xll conjointly with another, c++, xll ?

Would the problem be cause by something we do on the excel dna xll side, what could that possible be ? (We also double-checked our excel dna xll's code and haven't found a single clue.)

Thx in advance.

**Comment by govert** [comment]
This sounds tricky to investigate, and not something I've had reported before.
   
* Is the problem easily reproducible? Are you sure this is an interaction between the two add-ins?
* Can you get a screenshot of the msgbox? Who is showing the message?
* `xlAddInManagerInfo` is one of the dll exports that Excel looks for in an .xll add-in. Excel-DNA add-ins export this function and Excel sometimes calls it. I can't see that Excel-DNA would show a message in this context. This function is called by Excel to get info for the Add-Ins dialog.
* We can check whether the other .xll add-in exports it through the dumpbin utility.

It might be easier to track down if you contact me directly by email.

**Comment by MisesEnForce** [comment]
Hi Govert, dumpbin.exe /EXPORTS thecpp.xll shows indeed `xlAddInManagerInfo` in the list. The screeshot of the message : 
![image](https://user-images.githubusercontent.com/5349602/39087052-f86ea542-459a-11e8-9f7b-126be50d43c6.png) and it is really excel who is showing the message.
Usually (in compiled XLCALL32 and FRMWRK c++ api dll) the function `xlAddInManagerInfo` call is in a `#if DEBUG` directive so that it is not supposed to be visible in debug, except if the dll's XLCALL32 and FRMWRK were compiled in debug which the provider of the c++ dll denies. (He denies as well having any single occurence of `xlAddInManagerInfo` ...)
With his c++ xll only I cannot reproduce the pop, it only happens when used with our c# excel dna xll. It happens only one time : at the first time you do a VBA Selection.Calculate on any selected range in the excel spreadsheet, the range contain our/his functions or not.

**Comment by govert** [comment]
* To figure out where the interaction might be, you can start with a very simple Excel-DNA add-in (or even a simple C add-in) and make it more and more complicated towards your existing add-in. Somewhere along the way the interaction will appear, and that might give a clue. Or you can shim their add-in and have a look at the stack trace when Excel makes that call.

* The `0` is also weird - I wouldn't expect Excel to call that function with a null.

Anyway - I can't really see how this is an Excel-DNA problem...
