### ISSUE TITLE
SetDebuggerOptions fails when MSBuild nodes are reused between different Visual Studio instances

### ISSUE THREAD

**Issue by augustoproiete** [Excel-DNA/ExcelDna#190]
I've just noticed this on **Visual Studio v15.7.1**.

### Repro steps:

* Close any Visual Studio instances you might have opened
* Open a new Visual Studio instance (VS1)
* Create a new Class Library project (MyLibrary1)
* Install ExcelDna v0.35.1-beta2 into **MyLibrary1**
  * `Install-Package ExcelDna.AddIn -Version 0.35.1-beta2`
* Open a new Visual Studio instance (VS2)
* Create a new Class Library project (MyLibrary2)
* Install ExcelDna v0.35.1-beta2 into **MyLibrary2**
  * `Install-Package ExcelDna.AddIn -Version 0.35.1-beta2`
* Make sure there are no MSBuild processes running on the machine
  * `taskkill /im msbuild.exe /f /t`
    ![image](https://user-images.githubusercontent.com/177608/40203578-060c5b20-59fc-11e8-81b1-c1d4f19aad3c.png)
* Rebuild the solution **MyLibrary2**
  * This will start one `MSBuild.exe` process to compile the **MyLibrary2** (MB1)
  * **Everything should work as expected. No errors or warnings** :shipit:
* Now go to **VS1** and rebuild the solution **MyLibrary1**
  * Because the the `MSBuild.exe` process that we previously used to build **MyLibrary2** (**MB1**) is now idle, **VS1** will use it to build **MyLibrary1**
  * Although build finishes successfully, **you should see a warning `Unable to set the debugger options within Visual Studio`** :warning:
    ![image](https://user-images.githubusercontent.com/177608/40203549-f325cf78-59fb-11e8-9770-7d1138b245f7.png)

---

This is happening because the way we get a reference to Visual Studio in order to set the debugger options is by [getting the parent process of the MSBuild process that is running our task](https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.AddIn.Tasks/Utils/DevToolsEnvironment.cs#L73) which obviously fails in this scenario given that the parent process of MSBuild is **VS2** and the build task cannot find the project **MyLibrary1** inside the **VS2**. Doh!

### **The workaround, until we fix this, is to [disable MSBuild node reuse by defining an environment variable](https://github.com/Microsoft/msbuild/wiki/MSBuild-Tips-&-Tricks#msbuildexe-nrfalse)**

![image](https://user-images.githubusercontent.com/177608/40203741-8e235662-59fc-11e8-8e49-d974a1b39e07.png)

**Comment by govert** [comment]
Well - it is pretty wild of us to change the project settings in the build...

**Comment by caioproiete** [comment]
>
> Well - it is pretty wild of us to change the project settings in the build...
>

hahaha. I prefer to call it "bold" instead of "wild" 😆

On a serious note, I'll try to take a look at this in the next few days so that it makes it into the 0.35 RTM.

**Comment by govert** [comment]
@caioproiete Do you have any specific ideas on how we can approach the debugger setting when there are multiple VS instances? Maybe enumerate the processes and try to get the COM object model from each, or something like that?
I think it's the last thing I'd like to sort out before making a final release of version 0.35.

**Comment by caioproiete** [comment]
@govert Yes, enumerating the VS processes on the machine and trying to find the project in each of them, is the approach I was going for.

[I've started working on that](https://github.com/Excel-DNA/ExcelDna/pull/210/files#diff-ba2d9e47e4079b33a6ca8c914b09f241) at the end of May and have something that is probably 90% there, but due to personal issues I was not able to make progress since then.

[I've opened a WIP pull request](https://github.com/Excel-DNA/ExcelDna/pull/210/files#diff-ba2d9e47e4079b33a6ca8c914b09f241) in case you want to take a first look on where I'm at so far, and perhaps take it for a spin.

I should be able to resume working on that on the weekend of September 15th, but not likely not before that.

Looking forward to hear any feedback you may have on that branch.

**Comment by caioproiete** [comment]
@govert IIRC I wanted to test it more thoroughly, to see if it breaks, and make some decisions / handle edge cases:

* What's best way to find the project we are looking for? `$(ProjectPath)` or is there something better?
    * Should we do other checks besides `$(ProjectPath)` before deciding to change the debugger settings?
* The same project can be opened in different solutions, in different VS instances. How should we handle that?
    * Stop on the first project it finds (build finishes faster, but can lead to odd behavior)
    * Always enumerate all VS instances and always (safer, but build time increases with number of VS instances open)

**Comment by augustoproiete** [comment]
Fixed via [`04279b0`](https://github.com/Excel-DNA/ExcelDna/commit/04279b0dd2f6b6b60ffeaa07f52bce3eead3441e)
