### ISSUE TITLE
SetDebuggerOptions works incorrectly

### ISSUE THREAD

**Issue by hell-racer** [Excel-DNA/ExcelDna#191]
Ok, it seems like you guys are taking close look on that SetDebuggerOptions thing, let me add something :). Do I understand correctly that in recent issues you are talking about the thing that sets these values:

![image](https://user-images.githubusercontent.com/20350033/40220264-42f92a88-5a81-11e8-9570-6d99b9695481.png)

So if yes, it looks like it sets them incorrectly. At least in VS 2015 the project doesn't start because it can't find executable named "C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE %1" (with %1 in the end). I think we don't need %1 at all - it will add whatever specified in Command Line Arguments anyway.

The second thing is that it doesn't take into account the bitness of Excel. So I have 64-bit, and yet it adds 32-bit version of xll as a parameter, so when I fix that %1 thing it launches Excel but fails to load the xll addin.

Does it make sense or I do something incorrectly?

What I do is just create a new Class Library project, add ExcelDna.Addin reference and click Start :).

**Comment by hell-racer** [comment]
I use latest release version, which is 0.34.6, so that's even more strange now... Why it even changes anything if the feature doesn't exist there?

Ok, I tried to use ExcelDna.AddIn 0.35.3-beta3 and it doesn't make any changes when I install it:

![image](https://user-images.githubusercontent.com/20350033/40221944-9e2deaec-5a86-11e8-8d27-2908d11dd3a0.png)

(this is in VS 2015)

**Comment by caioproiete** [comment]
>
> Ok, I tried to use ExcelDna.AddIn 0.35.3-beta3 and it doesn't make any changes when I install it:
>

That is the expected behavior 😄. **The `SetDebuggerOptions` only runs when you build the project** (and it runs again every time you build the project).

This is done so that it captures the current name of your `.dna` file, and then figures out what is the name of the `.xll` that is being generated and sets the debugger options accordingly.

You can read more about how it works here:
https://github.com/Excel-DNA/ExcelDna/pull/147#issue-146652142

**Comment by hell-racer** [comment]
Oh, I see! When I build the project it sets the options correctly (and it works differently from what was in 0.34.6 - in 0.34.6 it changes options when I install the package, and in 0.35.3 beta - when I build it). Thanks a lot! So I'm closing the issue, right?

**Comment by caioproiete** [comment]
> I use latest release version, which is 0.34.6, so that's even more strange now... Why it even changes anything if the feature doesn't exist there?
>

Version `0.34.6` sets the debugging settings when you install the NuGet package, via a [PowerShell script that was removed with the introduction of `SetDebuggerOptions`](https://github.com/Excel-DNA/ExcelDna/pull/147/files#diff-882aebdb6b97944934381894eaecadca)

That PowerShell has that bug of getting the EXCEL.EXE with the `%1` and also doesn't check bitness, etc.

**Comment by caioproiete** [comment]
@hell-racer Cheers yes, you can close this.

**Comment by caioproiete** [comment]
For documentation purposes: This relates to #161
