### ISSUE TITLE
Update ExcelDna.AddIn NuGet Package to support the new PackageReference format

### ISSUE THREAD

**Issue by augustoproiete** [Excel-DNA/ExcelDna#193]
Spin-off of #138 to discuss how we want to support the `PackageReference` format in the `ExcelDna.AddIn` NuGet package. This relates to #188

### Background

* Currently `ExcelDna.AddIn` relies on PowerShell scripts for [installing](https://github.com/Excel-DNA/ExcelDna/blob/master/Package/ExcelDna.AddIn/tools/install.ps1) and [uninstalling](https://github.com/Excel-DNA/ExcelDna/blob/master/Package/ExcelDna.AddIn/tools/uninstall.ps1) the package which basically do the following:

#### `install.ps1`
1. Rename an `_UNINSTALLED_$(ProjectName)` to `$(ProjectName)-AddIn.dna`, if it exists
_Which would have happened after the user uninstalled a previous version of ExcelDna_
2. Add a `$(ProjectName)-AddIn.dna` file, if step 1 didn't find an old file
2.1. Perform some string replacements inside the `.dna` file added to include `$(ProjectName)`
3. ~Add a reference to the `.targets` file~ **Update 2018-05-18**: This is now done automatically by a NuGet feature implemented by #167

#### `uninstall.ps1`
1. Rename an existing `$(ProjectName)-AddIn.dna` file to `_UNINSTALLED_$(ProjectName)`, if it exists

### Known issues

* [The `PackageReference` format does not support the `install.ps1` and `uninstall.ps1` PowerShell scripts](https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html#will-existing-nuget-packages-work-if-i-am-using-packagereference-for-wpf-windows-forms-or-aspnet-projects)
* [The `PackageReference` format also does not support `content` files](https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html#supported-project-types) the same way they do with the `packages.config` format and introduce another feature `contentFiles` that behaves in a different way where [files are meant to be immutable](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files) and therefore [they are not shown in the project tree, and are not editable](https://github.com/NuGet/Home/issues/4954). The (terrible IMO) recommendation from the NuGet team is to "[_... copy them to the project manually if you need to edit the files ..._](https://github.com/NuGet/Home/issues/4954#issuecomment-337321237)" :disappointed:
* With the current approach (powershell scripts) If the user renames the `.dna` file to anything else that is not `$(ProjectName)-AddIn`, the script doesn't work anymore

### Proposed solution

I propose we do the following:

1. Remove the `install.ps1` and `uninstall.ps1` PowerShell scripts from the NuGet package
2. Rename the `ExcelDna-Template.dna` to `AddIn.dna.pp` and use NuGet's [source code transformation](https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations) feature to do the replacements inside the `.dna file`
3. Document that the user must manually copy the `.dna` file to the project when using `PackageReference` (until the NuGet team gives us an alternative) :no_good_man:
4. Update our build process (i.e. `ExcelDnaBuild` task) to - by convention - use `$(ProjectName)` as the name of the .xll, if it sees a file named `AddIn.dna` file in the project. If the user renames it to something else, then use the name of the `.dna` file for the output `.xll`

**Comment by govert** [comment]
Regarding 3: Doesn't NuGet have an option to include source files that are incorporated in the project?

**Comment by govert** [comment]
I'm confused about where the transformed .pp file ends up. Is it changed in-place in the packages directory, or added to the project, or something else?

**Comment by govert** [comment]
@caioproiete You summary of the situation is great, thank you.
Considering the current options, I'm not really feeling ready for this yet, and am not too keen on accepting changes for this issue soon.
I wouldn't want you to waste your time (unless you have a burning passion to explorer this...)

**Comment by caioproiete** [comment]
> I'm confused about where the transformed .pp file ends up. Is it changed in-place in the packages directory, or added to the project, or something else?
>

With `PackageReference`, we no longer have the `.\packages\` folder at the same level as the solution and the package files are all stored in a local cache (usually `%userprofile%\.nuget\packages`) and the file transformations are stored in the `obj` folder of the project. Content files are added to the project as "links" and because of that any changes you make to these files are lost when the package is reinstalled or upgraded.

**Comment by caioproiete** [comment]
FYI @govert pointed me to this discussion in the Visual Studio Developer Community which is about the need for restarting Visual Studio after making changes to `.props` files (which affects Excel-DNA add-ins), and this issue has been fixed in the new `.csproj` project system (which uses `PackageReference`) and it doesn't seem it will ever get fixed in the old `.csproj` project system...

**Comment by xp44mm** [comment]
I use F# .net framework 4.8 class library, found a error:

> DNA1546	Excel-DNA is not compatible with projects that use NuGet `PackageReference`. Make sure you create a .NET Framework (Class Library) project and configure Visual Studio to use `packages.config`	ExcelDNA

have resolved?

**Comment by augustoproiete** [comment]
@xp44mm The latest version of Excel-DNA as of this writing (v1.1.1) doesn't support `PackageReference` and by default displays the error message you're seeing.

The recommendation at this time is to use the `Class Library (.NET Framework)` project type instead of `Class Library (.NET Standard)` project type to get the best development & debugging experience.

If you want to use the new SDK-style project at your own risk, you can set `ExcelDnaAllowPackageReferenceProjectStyle ` to `true` in your `ExcelDna.Build.props`. See PR #327 for more details.

**Comment by andysprague44** [comment]
@augustoproiete hi! Question on the workaround should I want to use `ExcelDnaAllowPackageReferenceProjectStyle true`.

Is something like the following what is required to get this working (copied from .net framework post-build event command line,), or is there more to it?

```
xcopy "$(SolutionDir)\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDna.xll" "$(TargetDir)MyExcelAddin-AddIn.xll*" /C /Y
xcopy "$(TargetDir)MyExcelAddin-AddIn.dna*" "$(TargetDir)MyExcelAddin-AddIn64.dna*" /C /Y
xcopy "$(SolutionDir)\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDna64.xll" "$(TargetDir)MyExcelAddin-AddIn64.xll*" /C /Y
"$(SolutionDir)\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "$(TargetDir)MyExcelAddin-AddIn.dna" /Y
"$(SolutionDir)\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "$(TargetDir)MyExcelAddin-AddIn64.dna" /Y
```

**Comment by augustoproiete** [comment]
Hey @andysprague44 ! Small world :)

You shouldn't need any of that code if you're using the [latest version of Excel-DNA](https://www.nuget.org/packages/ExcelDna.AddIn/) (v1.1.1 as of this writing) as all of that is handled for you by Excel-DNA's build process (even in an SDK-style/PackageReference project). So there's basically only two switches you need to change for it to work (with some limitations (\*)): 

- Turn **on** `ExcelDnaAllowPackageReferenceProjectStyle` to ignore the error that SDK-style projects are not supported
- Turn **off** `RunExcelDnaSetDebuggerOptions` to disable the automatic configuration of Visual Studio debugging settings

This should be all you need:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <ExcelDnaAllowPackageReferenceProjectStyle>true</ExcelDnaAllowPackageReferenceProjectStyle>
    <RunExcelDnaSetDebuggerOptions>false</RunExcelDnaSetDebuggerOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDna.AddIn" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

NB: Change the `TargetFramework` as needed depending on what .NET Framework version your add-in users have on their machines.

**\*** The feature you'll be missing out when using Excel-DNA with SDK-style/PackageReference projects today is the automatic debugging configuration settings that does two things:

1. Look up where Excel is installed on your machine, and configure Visual Studio to run it (and attach the debugger to) when you press F5 / start a debugging session.

2. Determine if your Excel installation is 32-bit or 64-bit and automatically configure Visual Studio with the the correct `.xll` to be opened together with Excel when you press F5 / start a debugging session.

SDK-style/PackageReference projects no longer use the `.csproj.user` to store debugging settings so the API that we use to configure debugging is disabled in the new project system.

The current workaround is to (manually) create multiple profiles in your `launchSettings.json` (one for each machine/developer) and store it in source control, so that you can debug your add-in without having to configure this every time.

**Comment by govert** [comment]
The build can detect that it is running from an SDK-style project with 
```
Condition="'$(UsingMicrosoftNETSdk)' == 'true'"
```

**Comment by augustoproiete** [comment]
FYI [The condition we use today](https://github.com/Excel-DNA/ExcelDna/blob/abdeecb80dc81975f5cd64958a21c7ff270f9ee5/Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets#L71) already detects SDK-style projects by checking `PackageReferenceCompatibleProjectStyle`:

```xml
Condition=" ('$(PackageReferenceCompatibleProjectStyle)' == 'true' OR '$(RestoreProjectStyle)' == 'ProjectJson' OR '$(NuGetProjectStyle)' == 'PackageReference') " />
```

That said adding an extra check on `UsingMicrosoftNETSdk` just to be safe doesn't hurt.

**Comment by altso** [comment]
@augustoproiete I just tried your example and got this error from `dotnet build` command:

```
MSBUILD : ExcelDnaBuild error DNA-422377164: Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [C:\Temp\02\Test.csproj]
MSBUILD : ExcelDnaBuild error DNA-422377164: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [C:\Temp\02\Test.csproj]
MSBUILD : ExcelDnaBuild error DNA-422377164: File name: 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\Temp\02\Test.csproj]
MSBUILD : ExcelDnaBuild error DNA-422377164:    at ExcelDna.AddIn.Tasks.CreateExcelAddIn.AddDnaToListOfFilesToPack(String outputDnaFileName, String outputXllFileName, String outputXllConfigFileName) [C:\Temp\02\Test.csproj]
MSBUILD : ExcelDnaBuild error DNA-422377164:    at ExcelDna.AddIn.Tasks.CreateExcelAddIn.TryBuildAddInFor32Bit(BuildItemSpec[] buildItemsForDnaFiles) [C:\Temp\02\Test.csproj]
MSBUILD : ExcelDnaBuild error DNA-422377164:    at ExcelDna.AddIn.Tasks.CreateExcelAddIn.Execute() [C:\Temp\02\Test.csproj]
```

Test.csproj:
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <ExcelDnaAllowPackageReferenceProjectStyle>true</ExcelDnaAllowPackageReferenceProjectStyle>
    <RunExcelDnaSetDebuggerOptions>false</RunExcelDnaSetDebuggerOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDna.AddIn" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

Test.dna:
```xml
<?xml version="1.0" encoding="utf-8"?>
<DnaLibrary Name="Valitana Host Add-In" RuntimeVersion="v4.0" xmlns="http://schemas.excel-dna.net/addin/2018/05/dnalibrary">
  <ExternalLibrary Path="Test.dll" ExplicitExports="false" LoadFromBytes="true" Pack="true" IncludePdb="false" />
</DnaLibrary>
```

```
❯ dotnet --version
5.0.104
```

I do have net48 developer pack installed. Any ideas on how to make it work?

**Comment by augustoproiete** [comment]
@altso You need to use `msbuild` instead of `dotnet build`

**Comment by altso** [comment]
@augustoproiete Got it. Thank you.
