### ISSUE TITLE
Use an organization account for NuGet packages

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#196]
In April 2018, NuGet [introduced the concept of **organizations**](https://blog.nuget.org/20180417/organizations-on-nuget-org.html)... The concept is similar to the GitHub one, that is, it represents a team, more than it represents a person, and accounts can come and go in or out of the organization. This allows several users to manage packages for Excel-DNA without having to share credentials.

I went ahead and created two organizations to make sure we reserve the names for us:
* **[Excel-DNA](https://www.nuget.org/profiles/excel-dna)**
* ~[ExcelDna](https://www.nuget.org/profiles/exceldna)~ _Update 2018-05-22: This is now deleted as we've decided to go with [Excel-DNA](https://www.nuget.org/profiles/excel-dna)_.

~I have no strong preference on which one we pick. `ExcelDna` aligns with the prefix of the NuGet packages today whilst `Excel-DNA` aligns with the name of the organization on GitHub today.~

@govert & @mndrake I invited you to both organizations. You should have received an e-mail  from NuGet. **You'll need to log into NuGet and accept the invitation before you join the org**.

![image](https://user-images.githubusercontent.com/177608/40284624-1a34b96c-5c68-11e8-898d-33207c44b74a.png)

After you both accept the invitation, we can transfer the ownership of the NuGet packages to the org, and we can generate API Keys specific for the org, that we can use in AppVeyor to push packages when we do our releases.

**Comment by govert** [comment]
I try to use "Excel-DNA" as the name for the overall project, the GitHub organization and in general in human-friendly contexts. For namesspaces, code and other artifacts I use the "ExcelDna" moniker.

So "Excel-DNA" is the right organization name, also to match the GitHub organization. 

I've accepted the invitation.

**Comment by caioproiete** [comment]
Great. I'll delete the `exceldna` organization then.

Next step is to change the ownership of the packages to the `Excel-DNA` organization:

| NuGet Package                                                                                         | From             | To             |                    |
| ----------------------------------------------------------------------------------------------------- |:----------------:|:--------------:|:------------------:|
| [ExcelDna.AddIn](https://www.nuget.org/packages/ExcelDna.AddIn)                                       | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.Integration](https://www.nuget.org/packages/ExcelDna.Integration)                           | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.IntelliSense](https://www.nuget.org/packages/ExcelDna.IntelliSense)                         | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.Interop](https://www.nuget.org/packages/ExcelDna..Interop )                                 | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.Interop.Dao](https://www.nuget.org/packages/ExcelDna.Interop.Dao)                           | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.Registration ](https://www.nuget.org/packages/ExcelDna.Registration)                        | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.Registration.FSharp](https://www.nuget.org/packages/ExcelDna.Registration.FSharp)           | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.Registration.VisualBasic](https://www.nuget.org/packages/ExcelDna.Registration.VisualBasic) | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDna.XmlSchemas](https://www.nuget.org/packages/ExcelDna.XmlSchemas)                             | [caioproiete][2] | [Excel-DNA][4] | :white_check_mark: |
| [Excel-DNA](https://www.nuget.org/packages/Excel-DNA)                                                 | [govert][1]      | [Excel-DNA][4] |                    |
| [Excel-DNA.Interop](https://www.nuget.org/packages/Excel-DNA.Interop)                                 | [govert][1]      | [Excel-DNA][4] |                    |
| [Excel-DNA.Interop.Dao](https://www.nuget.org/packages/Excel-DNA.Interop.Dao)                         | [govert][1]      | [Excel-DNA][4] |                    |
| [Excel-DNA.Lib](https://www.nuget.org/packages/Excel-DNA.Lib)                                         | [govert][1]      | [Excel-DNA][4] |                    |
| [ExcelDnaDoc](https://www.nuget.org/packages/ExcelDnaDoc)                                             | [mndrake][3]     | [Excel-DNA][4] |                    |

[1]: https://www.nuget.org/profiles/govert
[2]: https://www.nuget.org/profiles/caioproiete
[3]: https://www.nuget.org/profiles/mndrake
[4]: https://www.nuget.org/profiles/excel-dna

**Comment by govert** [comment]
Oh - I see the main assembly in `ExcelDnaDoc` is already called `ExcelDna.Documentation`, so I think that's fine as a name for a replacement package.

**Comment by caioproiete** [comment]
ps: No answer from @mndrake yet, so I'm guessing he's not receiving GitHub notifications at the moment. I've sent him an e-mail.

**Comment by caioproiete** [comment]
No response from @mndrake so. I tried all channels I could find several times...

@govert As a last attempt, I'll contact the NuGet support and explain the situation, and see if they can transfer the ownership of the package to the [`excel-dna` organization](https://www.nuget.org/profiles/excel-dna), but we don't need to wait before we can release an updated version of `ExcelDnaDoc` with the new name - as soon as we decide on that.

Any more thoughts on the name suggestions above?

Would be good to release a replacement NuGet package for `ExcelDnaDoc` with the new name, to avoid issues like this one: [ExcelDnaDoc Error with latest version](https://groups.google.com/forum/#!topic/exceldna/qq0wLDSD8kk).

**Comment by govert** [comment]
I do a search on NuGet packages called:
* Documentation
* Documentor
* Builder
* Generator

I think my preferences are in order:
* ExcelDna.Documentation
* ExcelDna.Documentation.Builder
* ExcelDna.DocsBuilder

@caioproiete How strong is your objection against ExcelDna.Documentation?

**Comment by govert** [comment]
@caioproiete OK, I've heard back from Dave and he will assign ownership of the NuGet package later in the week.

**Comment by govert** [comment]
@caioproiete  What about:
    ExcelDna.Documentation.Tools

**Comment by mndrake** [comment]
@caioproiete @govert I was able to switch ownership on my phone. After you are able to confirm I’ll remove my personal account in nuget from the package.

**Comment by mndrake** [comment]
Looks like we’re good now.

**Comment by govert** [comment]
@mndrake Yes, all good - thank you very much

**Comment by caioproiete** [comment]
> @caioproiete @govert I was able to switch ownership on my phone. After you are able to confirm I’ll remove my personal account in nuget from the package.

Awesome! Thank you @mndrake !!

**Comment by caioproiete** [comment]
> @caioproiete What about: ExcelDna.Documentation.Tools

@govert That works for me.

Expanding on that idea, what if we added a suffix (or something else) to help make it more explicit the kind of documentation it generates?

For example, something like `ExcelDna.Documentation.Chm` or `ExcelDna.Documentation.ChmTools`?

That would leave the door open for other documentation generators for Excel-DNA add-ins, such as [Microsoft's DocFx](https://dotnet.github.io/docfx/) and [Pickles](https://github.com/picklesdoc/pickles)...

e.g. `ExcelDna.Documentation.DocFx`, `ExcelDna.Documentation.Pickles`, ...

**Comment by govert** [comment]
@caioproiete 
Dude! You're not helping.
It's "ExcelDna.Documentation.Tools".

**Comment by caioproiete** [comment]
Closing this one as all packages have been transferred to the the [Excel-DNA](https://www.nuget.org/profiles/excel-dna) organization. We'll track the release of the new ExcelDnaDoc nuget package via #239
