### ISSUE TITLE
On nuget.org, reserve the prefixes "ExcelDna" and "Excel-DNA", for the "Excel-DNA" organization

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#197]
In October 2017, NuGet [introduced the concept of **Package ID Prefix Reservation**](https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation), which helps developers determine the origin of a package. More specifically, if the package was published by the core maintainers of a project, or if it's an independent package built by the community.

![image](https://user-images.githubusercontent.com/177608/40400721-d510b616-5e19-11e8-90ad-7b987c38b0c7.png)

Now that we've transferred our core packages to the [`Excel-DNA`](https://github.com/Excel-DNA/ExcelDna/issues/196) organization, I propose we reserve the prefixes **`ExcelDna`** and **`Excel-DNA`** for any packages owned by the [`Excel-DNA`](https://www.nuget.org/profiles/excel-dna) organization on NuGet.

Moreover, I suggest we leave the prefix as **`public`** as per [described in their advanced scenarios](https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation#advanced-prefix-reservation-scenarios), so that the community can continue to publish NuGet packages using the prefix `ExcelDna` - as they can today - with the only difference that **our official packages will have the visual indicator** showing that the package comes from the project maintainers.

**Comment by govert** [comment]
Thanks - that sounds cool.

**Comment by caioproiete** [comment]
I've sent the request to the NuGet team.

**Comment by caioproiete** [comment]
Done!

[![image](https://user-images.githubusercontent.com/177608/40519662-1241754c-5f97-11e8-86eb-91136f24c866.png)](https://www.nuget.org/packages/ExcelDna.AddIn/)
