### ISSUE TITLE
ExcelDnaPack does not preserve original encoding of source code files

### ISSUE THREAD

**Issue by CaioProiete** [Excel-DNA/ExcelDna#2]
The source file is not guaranteed to be always be UTF8 (which is what `File.ReadAllText`) assumes. Instead, ExcelDnaPack should read source code files as binary (just like it does with images) to preserve whatever encoding is being used by the developer, in the file.

**Comment by govert** [comment]
OK - the I've finally integrated the pull request. I'm moving to GitHub for the main repository at last.

**Comment by CaioProiete** [comment]
Fantastic!! This is great news, Govert. Pretty sure you'll get more contributions moving forward.
