### ISSUE TITLE
XlCustomMarshal.cs: FieldOffsets in 64-bit version

### ISSUE THREAD

**Issue by jlewis111** [Excel-DNA/ExcelDna#207]
Hi, looking at the code for struct XlOperArray at line #69 of XlCustomMarshal.cs, shouldn't the FieldOffset values for the members after member pOpers be different between the 32-bit and 64-bit versions to account for difference pointer sizes, i.e. 32-bits and 64-bits respectively ?

This would apply in the code whereever pointer or IntPtr types are used as part of a structure or where offset arithmetic is being performed.

**Comment by govert** [comment]
Only the XlOper12 code in XlCustomMarshal12.cs would run under 64-bit Excel. That code is a bit different to the layout you're mentioning here, and seems to work right for both 32-bit and 64-bit.

**Comment by jlewis111** [comment]
The 64-bit version of XLCALL.DLL appears to retain entry points for Excel4. So is it simply the case that the ExcelDna code simply doesn't call theExcel4 entry points in the 64-bit version ?

- and presumably XLOPER can still be used, although sizeof(XLOPER) changes ?

**Comment by govert** [comment]
I think XLOPER is supported under 64-bit Excel. Excel-DNA just never uses it, always using XLOPER12 where possible.

**Comment by govert** [comment]
I'm planning to remove the XLOPER support (and support for pre-2007 Excel) in an upcoming version.

**Comment by jlewis111** [comment]
ok
