### ISSUE TITLE
Add support for unit testing in Excel-DNA

### ISSUE THREAD

**Issue by CaioProiete** [Excel-DNA/ExcelDna#21]
Currently it is not possible to unit test Excel add-ins built with Excel DNA, because pretty all iterations one does with the Excel DNA framework requires calling methods in static classes, which in turn try to call Excel APIs/features and because these are static classes, it is not possible to mock these classes.

I've made a good process with my [Excel DNA Wrapper](https://github.com/CaioProiete/Excel-DNA-Wrapper) project which addresses many of these issues, but it is not ideal and it is harder to maintain as Excel DNA moves and new methods are added.

I'd like all static classes that relies on Excel functionality to be implemented as regular classes that also implement interfaces (so that we can depend on these interfaces instead, and be able to mock) and then mark the static classes `Obsolete`, to encourage devs to use the new regular classes/interfaces.

This issue is somewhat related to issue #20.

**Comment by govert** [comment]
I think the right approach is a testing framework where Excel is in the loop.

I would not like all the static calls to become a whole interface/implementation/IoC layer and can't see myself supporting that in Excel-DNA anytime soon.

**Comment by CaioProiete** [comment]
Thanks @govert.

Having Excel in the loop would be great to run integration tests locally on in a controlled environment that we can install Excel, etc.

For unit tests, especially the ones running as part of continuous integration, it's not an option - as we don't have (or [shouldn't have](https://support.microsoft.com/en-us/kb/257757)) Excel on build nodes, etc. (think TeamCity, AppVeyor).

**Comment by CaioProiete** [comment]
@govert: Just to clarify, despite not being in your roadmap, would you be open to a PR that makes the necessary changes for this to become possible?

From the point of view of developer, it wouldn't change much. Think something like this:

```
public class AddIn : IExcelAddIn
{
    public void AutoOpen(IExcelIntegration excelIntegration)
    {
        // << Insert code that I can unit test here >>

        excelIntegration.RegisterUnhandledExceptionHandler(ex => {
            // ...        
        });

        // << Insert code that I can unit test here >>
    }
}
```

As you can see, all the developer had to do, was ask the framework to provide an instance of `ExcelIntegration` in order to use (which of course would be a singleton).

This opens the door for mocking the methods in `IExcelIntegration` and therefore devs can unit test the whole `AutoOpen` method - and can even check if an exception handler has been registered or not (and fail the test if didn't).

**Comment by govert** [comment]
For backward compatibility, such an interface / implementation layer would be in addition or on top of the existing static methods. Then I feel the extra complexity might rather go into your add-in and not into Excel-DNA (or rather in an extra library like your existing Excel-DNA-Wrapper library).

I'm not keen to support an interface / implementation layer like this in Excel-DNA in the near term.

**Comment by CaioProiete** [comment]
Yep. Totally agree with keeping existing static classes for backward compatibility (although I'd advocate setting a date/version # to mark these as `Obsolete` to encourage devs to start moving away from the static classes).

Not sure I understood the last part though.

At the moment, my add-ins do have a lot of complexity exactly because Excel-DNA do not embrace unit testing (or DI for that matter #20), so we have to jump through hoops to be able to unit test our ViewModels, Controllers, etc. We end up having to create all these wrappers for any interaction with Excel-Dna.

The goal of this issue is exactly to **remove** the need for this extra complexity, so that add-ins can be simpler. Not add more complexity. What complexity do you see in the code snipped above (`AddIn` class)?

An external library would not have the opportunity to run before the `IExcelAddIn.AutoOpen` or before the constructor of an `IRibbon`, so I don't see how would be possible to add proper support for unit testing via an external library without having Excel-DNA embrace the use of the interfaces - and stop relying on a concrete implementation.

---

When you say you're not keen to **support** do you mean that:

a) Someone would have to take responsibility to implement this and support this code (which would **have** to be inside Excel-DNA for it to work)

or

b) You don't want Excel-DNA to evolve in that direction at all, so no intention to merge a PR that enables such a thing

or

c) Something else

---

As I said before, I'm happy to volunteer for **a)**. I really like the Excel-DNA project, and I'm keen to contribute more.

**Comment by govert** [comment]
On this topic we're in case (b), at least for the next year or so.
(This certainly does not apply to the other issues you've raised, and I really appreciate your interest.)

The problem is not just implementing the code, but supporting questions about it, understanding interactions with the rest of the library, ongoing maintenance etc. I don't yet want to look after the code for the IoC / DI / interface refactoring you suggest here.

I'd be willing to reconsider this over time, perhaps as part of a larger refactoring of the whole add-in. Maybe over time I'll understand why you think it's simpler to incorporate the IoC / DI / interface wrapping in ExcelDna.Integration rather than your own add-in.

**Comment by CaioProiete** [comment]
@govert: OK, no problem.

I can update the [Excel-DNA-Wrapper](https://github.com/CaioProiete/Excel-DNA-Wrapper) project to support Excel-DNA `v0.33` and use it as a workaround. I also have to write some documentation and samples, to make it easier for people to use it.

The hardest part for me to keep this project is to detect / reconcile new methods and new classes as Excel-DNA evolves, and write the corresponding wrappers, etc. Any ideas would be appreciated (i.e. a more technical/detailed release notes with changes from release to release would help a lot).

I'll close this one, hopefully we can revisit this over time.

**Comment by robodude666** [comment]
+1. Would be great to see some better unit testing support built into Excel DNA.

@caioproiete Have you had an opportunity to work on examples for `Excel-DNA-Wrapper`? Would be nice to see an example AddIn with best practices of IoC/DI and Unit Testing based on what you found to work with Excel DNA.

**Comment by caioproiete** [comment]
Thanks @robodude666.

I'll see if I can squeeze a couple of examples when ExcelDna **v0.34** gets released, as I'll have to set aside some time to get Excel-DNA-Wrapper updated to work with it.

**Comment by zedr0n** [comment]
I've had the same concerns when trying to add unit testing as Excel for my app is just one frontend and it's important to abstract out as much as possible. If your add-in is quite simple I've found a generic way is to use syncfusion XlsIo to replace actual excel application. This can consume real excel spreadsheets containing actual tests using exported UDF functions. 

To do that I had to replace the whole exceldna and instead write my own registration routines by first implementing interface IExcelFunction an IExcelFunctionAttribute so that both ExcelDna and SyncFusion can process registrations consistently. Unfortunately that's not enough to unit test features like RTD or custom registrations ( e.g. I create Get* UDF functions for each property which is marked with IExcel attribute ) so if we could mock out parts of exceldna that would remove code duplication and allow proper unit testing without this overhead. I've put this code up as [Addin.Packages](https://github.com/zedr0n/Addin.Packages) but I since upgraded to .netcore so SFAddin might not actually work properly out of the box now.

**Comment by donald-fraser** [comment]
I thought I'd add my opinion on it too. I am also a big fan of IoC , however given that they are mostly Interfaces and wrapper classes, you could include the Interfaces and wrapper classes as part of the core Excel-DNA package but the default behaviour would not need to use them. In otherwords you have to explicitely use the wrapper classes to get the IoC behaviour. The reason it makes sence to have it included is to ensure that when new methods and classes are added there are also added to the Ioc Interfaces and wrapper classes. As it stands the current implementation of the wrapper package is now out of synch with the main release version.

**Comment by caioproiete** [comment]
@donald-fraser I'm working on a code generator that uses Reflection to generate all the wrapper classes and interfaces, which will make it easier to keep the [ExcelDna-Wrapper](https://github.com/CaioProiete/ExcelDna-Wrapper) in sync with new releases of ExcelDna. I'll update it soon.

**Comment by n1l** [comment]
> Excel is in the loop.

Hi @govert, can you please describe what do you mean here exactly?

**Comment by govert** [comment]
> > Excel is in the loop.
> 
> Hi @govert, can you please describe what do you mean here exactly?

I don't think there's a point in having test code against the Excel-DNA libraries that run outside the context of an Excel process loading the add-in.

Similarly, I think if you want to test your add-in (i.e. any functionality that is specific to it being an Excel add-in, and hence might depend on the Excel-DNA libraries) then that testing should be done by scripting a real instance of Excel, rather than trying to mock out the Excel and/or Excel-DNA parts.

**Comment by n1l** [comment]
> Similarly, I think if you want to test your add-in (i.e. any functionality that is specific to it being an Excel add-in, and hence might depend on the Excel-DNA libraries) then that testing should be done by scripting a real instance of Excel, rather than trying to mock out the Excel and/or Excel-DNA parts.

Thanks for the replay @govert . My motivation here is an approach how can I tests my code for excel rather that implementing specific Exel-DNA features so it would be better to create a separate thread but still I think it's only about your opinion.

So is there any chance I can retrieve results of excel functions automatically?
I mean I run excel with addin, I open sheet with cases, and at the end I can get some result and do some assertions.

**Comment by govert** [comment]
> So is there any chance I can retrieve results of excel functions automatically?
> I mean I run excel with addin, I open sheet with cases, and at the end I can get some result and do some assertions.

Yes - you can do this with Excel's COM automation from VBA or .NET or Powershell or any other COM-friendly environment.

**Comment by n1l** [comment]
> Yes - you can do this with Excel's COM automation from VBA or .NET or Powershell or any other COM-friendly environment.
Awesome! Do you have some examples here: https://github.com/Excel-DNA/Samples

**Comment by govert** [comment]
> Awesome! Do you have some examples here: https://github.com/Excel-DNA/Samples ?

I doubt it runs at the moment, but you can see an old attempt at doing this here:
https://github.com/Excel-DNA/ExcelDna/tree/master/Source/Tests/ExcelDna.IntegrationTests
https://github.com/Excel-DNA/ExcelDna/blob/master/Source/Tests/ExcelDna.IntegrationTests/Tests.cs

That might give you some ideas on how to get started.

**Comment by n1l** [comment]
@govert thank you a lot!
