### ISSUE TITLE
Add-In Description DnaLibrary XmlAttribute

### ISSUE THREAD

**Issue by mzhukovs** [Excel-DNA/ExcelDna#211]
This is a tiny concern, and perhaps it is already implemented and I'm just not sure how to use it, but would be nice to be able to provide a description of the add-in. Perhaps add a Description XmlAttribute to DnaLibrary.cs?

e.g. in .dna file then this:
`<DnaLibrary Name="PremiumHelper Add-In" Description="Helps with your premiums, duh!" RuntimeVersion="v4.0">`

Would result in this:
![image](https://user-images.githubusercontent.com/13161978/44981588-9b9ca880-afa5-11e8-95a9-97d47ab4cb10.png)

**Comment by mzhukovs** [comment]
P.S. that's from the manage add-ins option within Excel.

P.P.S. thanks for all the hard work on this library, it's truly fantastic

**Comment by govert** [comment]
Excel does not seem to support providing a description for .xll add-ins. There may be some undocumented registry entry that one can set that would be checked for the description, but I've not been able to track that down, and am not sure even then when we'd set the value.

**Comment by mzhukovs** [comment]
ok thanks for the prompt response
