### ISSUE TITLE
Excel-DNA Compatibility with Excel 2019

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#213]
GA of the Office 2019 was announced yesterday. Adding this for us to track compatibility tests with Excel 2019.

>
> ### Office 2019 is now available for Windows and Mac
> https://www.microsoft.com/en-us/microsoft-365/blog/2018/09/24/office-2019-is-now-available-for-windows-and-mac/
>

**Comment by KFoxder** [comment]
@ara818

**Comment by KFoxder** [comment]
@caioproiete do you know if anyone has the time or chance to test this?

**Comment by gmichaud** [comment]
I've been using our add-in with Excel "Insider Fast Ring" for a while (currently at version 1812, build 11101.20000) and I have not encountered any issues beside some toolbar icons (ImageMso) being unavailable and replaced by black circle for a short period of time. I'm using the Office 365 version and it still says "Office Professional Plus 2016", but my understanding is that it's the exact same thing (my build would actually be more recent than the official Office 2019 release as per https://docs.microsoft.com/en-us/officeupdates/update-history-office-2019)

**Comment by govert** [comment]
Closing this for now - I have no reason to think that Excel 2019 is a real version from an internal perspective.
