### ISSUE TITLE
ExcelCommand button order error

### ISSUE THREAD

**Issue by Charltsing** [Excel-DNA/ExcelDna#216]
I use the xll of 0.34.6 and my own xll compiled with vs2017(0.34.6 source), run the same dna file, the order of the buttons is not the same .

my own xll compiled with vs2017----button is order by B3/Z5/C2/A4/Z2
0.34.6  xll                                       ----button is order by Z5/Z2/B3/C2/A4

win10(1809) + office365(1809) 64bits

what wrong with 0.34.6  xll ?

.dna file:

using System;
using System.Text;
using System.Threading;
using ExcelDna.Integration;
using System.Windows.Forms;

public class Common
{
    [ExcelCommand(MenuName = "Sample", ShortCut="^1",
	              MenuText = "B3",Name="ShowVer0")]  
    public static void ShowVersion4()
    {       
        MessageBox.Show("ShowVersion3"); 
    }
	[ExcelCommand(MenuName = "Sample", ShortCut="^2",
	              MenuText = "Z5",Name="ZZZZ")]  
    public static void ShowVersion3()
    {       
        MessageBox.Show("ShowVersion1"); 
    }
	[ExcelCommand(MenuName = "Sample", ShortCut="^3",
	              MenuText = "C2",Name="Name4")]  
    public static void ShowVersion0()
    {       
        MessageBox.Show("ShowVersion2"); 
    }
    [ExcelCommand(MenuName = "Sample", ShortCut="^4",
	              MenuText = "A4",Name="Name1")]  
    public static void ShowVersion1()
    {       
        MessageBox.Show("ShowVersion4"); 
    }	
    [ExcelCommand(MenuName = "Sample", ShortCut="^5",
	              MenuText = "Z2",Name="Z")]  
    public static void ShowVersion2()
    {       
        MessageBox.Show("ShowVersion1"); 
    }    
}
 

xll(compiled with vs2017 v141xp) file size is 1905kb
0.34.6 xll file size is 687kb
What is the difference between them?

**Comment by ittegrat** [comment]
See 93d9cb6.

**Comment by Charltsing** [comment]
thanks

**Comment by caioproiete** [comment]
@Charltsing Can we close this one?

ps:
> xll(compiled with vs2017 v141xp) file size is 1905kb
0.34.6 xll file size is 687kb

You are likely comparing a `Debug` build on your machine with a `Release` build that is distributed with Excel-DNA.
