### ISSUE TITLE
Why need GuID and ProgId to define ProgId

### ISSUE THREAD

**Issue by konne** [Excel-DNA/ExcelDna#217]
@govert 
Is there any reason that both has to be defined?

Code Line:
https://github.com/Excel-DNA/ExcelDna/blob/2aa1bd9afaf76084c1d59e2330584edddb888eb1/Source/ExcelDna.Integration/ExcelComAddIn.cs#L82

Do you willing to accept a PR that changes this to.

That allows to only define for example the GUID and the progid is gernated out of my GUID and the "DNA."+GUID+...
Or only define a ProgID and than just use this.

**Comment by govert** [comment]
@konne The way Guid and Progids are used by .NET, COM, Excel and Excel-DNA is very confusing. Any change we make here is likely to break something unexpected, so I'm not keen at all.
Why is the current behaviour an issue for you?

**Comment by konne** [comment]
@govert 
I don't like to define a GUID if I just want to define the ProdId.
I will close it, because of the your described issues. If you still
like it you can reopen it.
