### ISSUE TITLE
ExcelDna/Source/ExcelDna.Integration/ComInterop.cs  ERROR！！

### ISSUE THREAD

**Issue by Charltsing** [Excel-DNA/ExcelDna#218]
ExcelDna/Source/ExcelDna.Integration/ComInterop.cs

353、409 line
original：
_CustomTaskPaneEvents_SinkHelper customTaskPaneEvents_SinkHelper;
                        for (int i = 0; i <count; i++)
fix：
_CustomTaskPaneEvents_SinkHelper customTaskPaneEvents_SinkHelper;
                        for (int i = count - 1; i <= 0; i--)

**Comment by govert** [comment]
Fixed for v 1.0.0
