### ISSUE TITLE
Implement continuous integration builds with Appveyor

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#22]
Add automated builds through AppVeyor, and packages published through a MyGet feed, for Excel-DNA and the Registration extension.

I have registered accounts with both in the past, but I still have to figure out how the permissions and accounts should work to allow others to work on this.

There also a tool to help with the NuGet package configurations, but I can't find it now...

**Comment by govert** [comment]
OK - we have this now:
https://ci.appveyor.com/project/govert/exceldna/build/1.0.1

The build fails - I think we need an AppVeyor.yml file.

**Comment by govert** [comment]
It builds now, but there is a more serious snag. Excel-DNA requires the xp build tools for C++ but that's not installed on the AppVeyor server.

![image](https://cloud.githubusercontent.com/assets/414659/9562266/1858bc26-4e68-11e5-833b-a29f45fd3223.png)

**Comment by govert** [comment]
OK - the Appveyor build now work.

They also have a NuGet feed, so I don't think we need MyGet to get a NuGet feed for every build. I haven't figured out how to set that up on Appveyor.

I also don't know how the version numbers interact between the assemblies, the Appveyor builds and the NuGet packages.

**Comment by CaioProiete** [comment]
That's awesome!

Let me know if you want me to look into the NuGet setup.

As for the version, what I typically do for NuGet in CI, is to use use
"major.minor.patch" where "patch" takes the build number generated by build
server, so in your case with AppVeyor would be "0.33.{build}".

**Comment by govert** [comment]
OK - the two new NuGet packages (ExcelDna.Integration and ExcelDna.AddIn) are now produced from the Appveyor build. I've tried to configure, but not yet checked, that they go into the account feed at: https://ci.appveyor.com/nuget/exceldna

**Comment by govert** [comment]
The project feed is now at https://ci.appveyor.com/nuget/Excel-DNA/ExcelDna and seems to work OK.

**Comment by govert** [comment]
OK - I'm closing this as an issue for now. More specific settings, versioning and tagging as part of a development workflow can be raised as new issues.
