### ISSUE TITLE
Add support for add-ins that use Strong-Name

### ISSUE THREAD

**Issue by caioproiete** [Excel-DNA/ExcelDna#223]
As per https://groups.google.com/forum/#!topic/exceldna/hSCb4ig5rVI (and #76)

Currently, if we add a strong-name to a Class Library project that uses Excel-DNA, it doesn't work - i.e. The add-in doesn't get loaded because the copy of `ExcelDna.Integration.dll` that is embedded within the `.xll` doesn't have a strong-name, and we don't get a chance to add the strong-name ourselves, of course, because it's embedded in the `.xll`...

Probably the easiest approach is to just add a strong name to all of our assemblies, which includes `ExcelDna.Integration.dll`, so that future versions of Excel-DNA `.xll` add-ins ship with strong-named versions.

---

More info: [Strong naming .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries)

**Comment by govert** [comment]
@caioproiete  Does this project, which allows the consuming library to strong-name assemblies when they build, make any difference to your opinion on this topic? 
https://github.com/dsplaisted/strongnamer

**Comment by caioproiete** [comment]
@govert Unfortunately it doesn't resolve the issue, because the key used to sign matters in the assembly resolution.

e.g.:
* Mary creates `LibraryA` that depends on `ExcelDna.Integration` `v1.0.0` and use [StrongNamer](https://github.com/dsplaisted/strongnamer) with key `X`
* Paul creates an Excel-DNA add-in `ProjectDNA`, also using `ExcelDna.Integration` `v1.0.0`, and use [StrongNamer](https://github.com/dsplaisted/strongnamer) to sign `ExcelDna.Integration` with his company key `Y`

Now we are in a bad place... Both `ProjectDNA` and `LibraryA` **seem** to depend on the exact same assembly (`ExcelDna.Integration` `v1.0.0`), yet for the .NET Framework they are completely different assemblies because the key used to sign them is part of the assembly identity...

**Comment by govert** [comment]
OK thank you - I didn't think of it that way.

That's a good reason why users might stay away from StrongNamer, though for Excel-DNA we deal with the loading explicitly and bypass what .NET would do, so I think it would actually work fine with different strong names.

OK, closing again... we're going to try strong names for v 1.1.
