### ISSUE TITLE
Diagnostic log doesn't log persistent RTD server init errors

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#224]
https://github.com/fandrei/RtdMinimal
The constructor or RtdServerMinimal throws an exception, but it's not written to the diag log.

**Comment by fandrei** [comment]
@govert I've fixed this problem; could you give me permission to create a PR?

**Comment by fandrei** [comment]
@govert I've fixed this problem; could you give me permissions to create a PR?

**Comment by govert** [comment]
Yes thanks - that would be great.
