### ISSUE TITLE
Error: "Excel found unreadable content in 'Test.xlsx'. Do you want to recover the contents of this workbook?"

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#225]
Apparently, this error is happening when my addin is disabled in Excel options and I'm trying to open any document that contains RTD funcs from my addin.
After this message, when choosing "Yes" - Excel crashes instantly, or returns this error message: "Removed Part: /xl/volatileDependencies.xml part with XML error.  (Volatile external formula reference) Catastrophic failure Line 2, column 358."
Choosing "No" - Excel closes.

I wonder if it's possible to somehow prevent Excel from behaving in this way? For instance, just return "#N/A" for the funcs from any disabled addin?

**Comment by Rand-Random** [comment]
Do you call `ComServer.DllUnregisterServer()` in `AutoClose()`?

**Comment by fandrei** [comment]
@Rand-Random apparently, it wasn't. Thanks.
