### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by mnar53** [Excel-DNA/ExcelDna#227]
Not really an issue.

I was not able to find if it is possible to use directly Python within the framework of Excel-DNA, which means to use Excel-DNA in place of pyxll (commercial) or xlloop (free), all using the Excel C API.  

But I found there is a Python package called "Python for .Net" which apparently makes it possible the communication between Python and .Net in both directions. Please note this is not IronPython, here Python is whatever version (2.7 upwards) which is installed on the machine. Given the tremendous number of scientific packages available in Python, this would be a real boost for Excel-DNA.

But before to get involved, I'm just curious to know if there are reasons for not to do it. Did anybody tried it already?

**Comment by zqwght** [comment]
I have developed a xll which integrated Excel-DNA and Python for .Net.

**Comment by caioproiete** [comment]
@zqwght Is it open source? If yes, would you mind posting a link to the repo?

**Comment by mnar53** [comment]
I agree with @caioproiete. If I can further elaborate, for Python I'd give a chance also to BERT-R : yes, it is for the R language, but using in it the package **reticulate**, it is possible to link in whatever Python library (e.g., numpy and scipy). Plus R too has a lot of applications too.

**Comment by ittegrat** [comment]
@mnar53 an alternative to pyxll and xlloop is [xlwings](https://www.xlwings.org/).

**Comment by mnar53** [comment]
@**ittegrat**: I was no mentioning xlwings because it does not use Excel C-API. It is COM-based and forces to write, manually or automatically, a lot of vba glue code.

**Comment by mnar53** [comment]
Something between self-teaching and open-source. Always used Excel a front-end while in chemical industry, and always looking for the best integration solutions.

**Comment by caioproiete** [comment]
@mnar53 An easy way to have this integration working is to expose the functions implemented in Python through a simple web server (e.g. Flask, Bottle, etc.), and have the C# code call that via HTTP. That also gives you the option to have the functions running on a different machine than the one where the Excel Add-in is running.

**Comment by mnar53** [comment]
**@caioproiete** thank you for this suggestion. In this vein, consider also xlloop: it is one single xll sending requests to a function server written in whatever language (python, R, java, Ruby,....).  Function can be exposed, i.e., registered in Excel.

**Comment by govert** [comment]
Not really an issue for Excel-DNA - I highly recommend using PyXLL for integrating Python with Excel.

**Comment by RusselWebber** [comment]
I created a product just as @mnar53  suggested. 

xlSlim uses Python.net and Excel DNA to allow Python functions to be called from Excel. I recently added RTD functionality so that any Python generator function can be used to stream data into Excel.

https://xlslim.com
