### ISSUE TITLE
Initialize Excel12v - is it thread safe?

### ISSUE THREAD

**Issue by mvorisek** [Excel-DNA/ExcelDna#244]
Initialize Excel12v
https://github.com/Excel-DNA/ExcelDna/blob/2aa1bd9afaf76084c1d59e2330584edddb888eb1/Source/ExcelDna.Loader/XlCallImpl.cs#L70

is it thread safe or does it miss a lock after the if condition?

**Comment by govert** [comment]
I think this will always be called first during Excel-DNA startup, on the main Excel thread.

**Comment by mvorisek** [comment]
Thanks for this reply, closing it.
