### ISSUE TITLE
long running exceldna ExcelFunction giving Excel is waiting for another application to complete OLE action

### ISSUE THREAD

**Issue by jsralph** [Excel-DNA/ExcelDna#248]
Hi,

Have some excel dna functions which load time series data from a web service.

Have recently expanded the data a lot so it takes more like 3/4 minutes to run the background call, instead of ~30secs. This has introduced a problem where Excel is giving a pop up with "Microsoft Excel is waiting for another application to complete an OLE action". Previously it ran fine

Is there a way to prevent this error occurring? 
Often the tasks still completes fine once the error msg is clicked 2 or 3 times. So i think c# code is ok.

have tried adding attributes to the Excel function such as :
        public bool IsMacroType = true;
        public bool IsThreadSafe = false;

But didn't seem to help

Thanks

**Comment by govert** [comment]
@jsralph You might try to make your functions async - see https://github.com/Excel-DNA/ExcelDna/wiki/Async-Notes

For help you can write to the public Google group at https://groups.google.com/forum/#!forum/exceldna or email me to book a direct support session

**Comment by govert** [comment]
I don't think this is something Excel-DNA can help with. Closing for now, please re-open if we need to review.
