### ISSUE TITLE
Is there a way to get the Excel RTDThrottleInterval in Excel-DNA?

### ISSUE THREAD

**Issue by EugenDueck** [Excel-DNA/ExcelDna#249]
For an RTD addin that needs to do polling, it would be nice to know the ThrottleInterval, so it doesn't poll more often than needed.

There is a way to read the ThrottleInterval from the registry, like

```
HKEY_CURRENT_USER\Software\Microsoft\Office\15.0\Excel\Options\RTDThrottleInterval
```

but for that you would have to know and consider the version number etc. Is there an easy and reliable way to get the interval, perhaps via Excel-DNA?

**Comment by govert** [comment]
You could use the COM object model: `Application.RTD.ThrottleInterval`

**Comment by EugenDueck** [comment]
I guess, this is what you mean:
```
Application xlApp = (Application)ExcelDnaUtil.Application;
var throttleInterval = xlApp.RTD.ThrottleInterval;
```
At least, it does the trick. Thanks!
