### ISSUE TITLE
UDF returning DateTime created from 2 digit year causes Excel to crash

### ISSUE THREAD

**Issue by lzeitz** [Excel-DNA/ExcelDna#252]
Hi,

I have found an issue in Excel DNA concerning return of a DateTime created from a 2 digit year. I am running Excel-DNA.0.34.6. Is there a fix for this?

`
        [ExcelFunction(Name = "TEST_DATE", Description = "TEST", Category = "TEST", IsThreadSafe = false)]
        public static object TEST_DATE()
        {
            try
            {
                return new DateTime(19, 3, 1).EndOfMonth();
            }
            catch
            {
                return ExcelError.ExcelErrorValue;
            }
        }
`

**Comment by govert** [comment]
I think this is fixed in v1.0. Could you perhaps have a look?

-Govert

**Comment by lzeitz** [comment]
Thanks for the quick response Govert,

I will have to setup a test environment separate from my code base so that the versions of Excel-DNA do not overlap. I will try to do that later this week.

Thanks

**Comment by lzeitz** [comment]
Hi Govert,

I tried it in v1.0 and Excel still shuts down.

Thanks

**Comment by govert** [comment]
OK thanks Lee - I'll take a look.

-Govert

**Comment by govert** [comment]
@lzeitz Thank for reporting this - I've pushed a fix that will go into the next release - it now returns #VALUE for the case where a DateTime is not a valid OLE Automation date. There no automatic conversion of 2-digit years in the .NET `DateTime`, so your code still won't be interpreted like `=DATE(19,3,1)` in Excel, but at least it won't crash anymore. See this post for more details on dealing with 2-digit years in .NET: https://www.hanselman.com/blog/HowToParseStringDatesWithATwoDigitYearAndSplitOnTheRightCenturyInC.aspx
