### ISSUE TITLE
Difference between Debug and Release build

### ISSUE THREAD

**Issue by bluewalk** [Excel-DNA/ExcelDna#258]
Something seems to be going wrong between Debug and Release builds:

When building our Excel plugin the Debug build works on machines (dev-machine and test machines) using Excel 365 an Excel 2013 (64 and 32 bits respectively).

When running the Release build of the plugin on these machines, they all fail with the following initialization error:
```
Initialization [Error] There was an error in processing .dna file bytes:
Het XML-document (2, 2) bevat een fout.
<DnaLibrary xmlns='http://schemas.excel-dna.net/addin/2018/05/dnalibrary'> werd niet verwacht.
Initialization [Error] No Dna Library found.
```

Used XML in our DNA file:
```xml
<DnaLibrary Name="ZR.IP21.AARP.ExcelAddin Add-In" RuntimeVersion="v4.0">
  <ExternalLibrary Path="ZR.IP21.AARP.ExcelAddin.dll" LoadFromBytes="true" Pack="true" UseVersionAsOutputVersion="true" />
  <Reference Path="Newtonsoft.Json.dll" Pack="true"/>
  <Reference Path="ZR.IP21.AARP.Utils.dll" Pack="true"/>
</DnaLibrary>
```

Funny thing is, as you can see, our DNA file doesn't even reference the `xmlns`.

**Comment by govert** [comment]
I'd guess it's just something going wrong with how you're building, or an extra file somewhere.

Maybe make a new project from scratch, install the NuGet packages, check that everything is OK, then bring your code in or see what's different. Also compare the build outputs, looking particularly at the ExcelDnaPack output.

**Comment by bluewalk** [comment]
Just had a look, there is no difference between the Debug and Release output besides the path changing from bin\Debug to bin\Release.

Also as the DNA file has UseVersionAsOutputVersion set, the Debug build includes our assembly info, whilst the Release build includes yours (ExcelDNA). It worked fine with the previous ExcelDNA version (`0.34.6`), now using `1.0.0`.

**Comment by govert** [comment]
You can check for something funny that stays in the post-build step after upgrading.
You can check for an extra .dna file or something in the project after upgrading.

Have you tried a new project with v1.0?
That should certainly work.

I'm pretty sure this is not a general problem, but specific to something in your project.

**Comment by bluewalk** [comment]
Will try creating a new project tomorrow morning, will report back if that solves the issue. Most likely you are correct though.

**Comment by bluewalk** [comment]
Recreating the project fixes the build issue, seems there are indeed leftovers after upgrading. Thanks for the tip!
