### ISSUE TITLE
Detecting implicit intersection

### ISSUE THREAD

**Issue by andrewbridge** [Excel-DNA/ExcelDna#259]
Office 365 versions of Excel add "dynamic array" and `#SPILL!` support. In order to achieve feature parity and consistent behaviour, these versions will add a `@` to function calls which return data that would normally rely on dynamic arrays. From [the implicit intersection wiki page](https://support.office.com/en-gb/article/implicit-intersection-and-dynamic-arrays-7c21bf05-72f9-4261-822b-b26767efbd13):

> If a formula authored in non-dynamic aware Excel relied on implicit intersection, that formula will be preceded by @ when opened in dynamic array Excel. The @ will be removed on save to facilitate compatibility with non-dynamic aware Excel.

In my add-in, I'm trying to provide progressive enhancement behaviour for dynamic arrays, detecting support for them and either falling back to a manual "print to cells below the caller" approach or returning an object and allowing dynamic array support to handle it.

This works well except when opening a worksheet that was authored in a non-365 version of Excel but opened by a 365 version of Excel, due to the behaviour described above.

I've not found a reliable method of checking if the `=@` has been added or any other way of detecting if implicit intersection is being used as part of the caller formula. This is compounded by the caller object sometimes representing irrelevant cells during load time (is this expected behaviour?).

Has anyone had the need or found a reliable method of detecting this?

**Comment by govert** [comment]
It might be tricky - the

**Comment by govert** [comment]
Sorry didn't mean to close - pressed the wrong button.

**Comment by andrewbridge** [comment]
Ah closing it may well be the right decision nevertheless! I've had a go detecting just based on the formula string, but it isn't reliable.

Is it expected behaviour that the C API `app.caller` object is for a totally different cell when a sheet initially loads? It all seems to work as expected during normal operation, but totally haywire at load.

**Comment by govert** [comment]
By `app.Caller` do you mean you can the caller through the COM object model?
You could rather try the C API `xlfCaller` call. It would be interesting if you find a difference.

**Comment by andrewbridge** [comment]
Ah, I may be getting the two APIs confused. I've tried something along the lines of

```c#
if (ExcelDnaUtil.Application is Application app)
{
    var caller = (Range)app.caller;
    var formula = (string)caller.FormulaArray.ToString();
    return formula.Substring(0,2) == "=@"
}
```

Am I able to get the formula string from `xlfCaller` instead?

**Comment by govert** [comment]
For a start you can just check if the result from `xlfCaller` is more stable than the COM API.

You should be able to read the `FormulaArray` with some `xlfGetCell` call.
The code in my ArrayResizer here does this: https://github.com/Excel-DNA/ExcelDna/blob/master/Distribution/Samples/ArrayResizer.dna in the `DoResize` method

**Comment by andrewbridge** [comment]
Hi @govert, just got back on to this project.

I'm trying to run

```c#
string formula = (string)XlCall.Excel(XlCall.xlfGetCell, (int)41);
```

and previously

```c#
string formula = (string)XlCall.Excel(XlCall.xlfGetCell, (int)41, (ExcelReference)caller);
```

as suggested, but I'm still running into `Exception thrown: 'ExcelDna.Integration.XlCallException' in ExcelDna.Integration`

I'm currently trying to run this in the `OnSuccess` callback of a class derived from `FunctionExecutionHandler`. I've seen elsewhere that if I were running this from a core function I'd need to set `IsMacroType=True`. Is it possible for me to run this call under the conditions I'm currently running?

**Comment by govert** [comment]
You definitely need to set IsMacroType=true for the xlfGet... Functions to work. It should be preserved by the transformations, but simplest would be to figure out (one instance of) your function as a standalone, before applying the transformations.

**Comment by andrewbridge** [comment]
Great, thank you! I started off just running this in a function, and got that returning. I've now applied the `IsMacroType` attribute to all registered functions as part of one of the registration processes and added a call in one of my transformations. The formula that comes back certainly seems to be more reliable than the `app.caller` method above, even at load time.

However, based on your [recommendations on the wiki](https://github.com/Excel-DNA/ExcelDna/wiki/ExcelFunction-and-other-attributes#ismacrotype), it seems like using `IsMacroType` across the board may cause all sorts of side effects, especially as it mentions functions being treated as volatile, and you recommend using the attribute sparingly.

I've not noticed functions acting as volatile functions, nor have I seen any side effects in my small amount of testing. Have the side effects of this attribute changed/improved over time? Do you still not recommend using it widely?

**Comment by govert** [comment]
A function marked as `IsMacroType=true` will automatically be considered as volatile by Excel if there is at least one argument (of type `object`) that is marked as `AllowReference=true`. I don't know of any change in this regard across versions of Excel.

Functions marked `IsMacroType=true` cannot be registered as thread-safe.

I don't know what the other side effects `IsMacroType=true` might have. I recall something related to the calculation dependency order, but don't have a reference or more details for that.

**Comment by andrewbridge** [comment]
Okay, those actually don't sound like terrible negatives in my situation as we don't use `AllowReference` or `IsThreadSafe` in our codebase.

Excellent, thank you once again for your help! I think I can probably use this for my hacky detection method!
