### ISSUE TITLE
Set `Environment.CurrentDirectory` to folder where XLL is located

### ISSUE THREAD

**Issue by augustoproiete** [Excel-DNA/ExcelDna#276]
Currently the Excel-DNA add-in loader does _not_ set a value for `Environment.CurrentDirectory`, leaving it with a default value (usually `%USERPROFILE%\Documents`).

![image](https://user-images.githubusercontent.com/177608/68539169-cf1b5580-0355-11ea-8f3e-f6ccd40b640c.png)

![image](https://user-images.githubusercontent.com/177608/68539170-d17daf80-0355-11ea-95ed-cad5ef3dc06b.png)

---

**This is inconsistent with other .NET applications, and cause issues with libraries that rely on `Environment.CurrentDirectory` in order to access the file system**.

For example, writing to a file from within a Console app, will write to the same folder where the `ConsoleApp.exe` is located (1), whereas writing to a file from within an Excel-DNA Add-In, will write to `%USERPROFILE%\Documents\`.

* (1) On double-clicking of the `.exe` in Windows Explorer.

N.B. This behavior happens when double-clicking the `.xll` from Windows Explorer. When debugging the add-in from Visual Studio, `Environment.CurrentDirectory` is set by Visual Studio to be the output path where the `.xll` is located, so we get the correct/expected behavior.

---

### Proposed solution

Set `Environment.CurrentDirectory` to the folder where the `.xll` add-in is being loaded from, before any user-code gets executed (e.g. `IExcelAddIn.AutoOpen`, Ribbon constructors, etc.) and revert back to its original value after user-code finished executing.

---

### Current workaround

One workaround is to set `Environment.CurrentDirectory` during the initialization of each add-in:

```csharp
public class AddIn : IExcelAddIn
{
    public void AutoOpen()
    {
        Environment.CurrentDirectory = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
        // ...
    }
}

// ...

[ComVisible(true)]
public class Ribbon : ExcelRibbon
{
    public Ribbon()
    {
        Environment.CurrentDirectory = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
        // ...
    }
}
```

**Comment by govert** [comment]
We should not be setting process-wide stuff like the current directory. The add-in is not an application - Excel is the application.

The workaround is fine for add-ons that need to work with library calls that leave no option, but we should encourage re-setting at the end of the context where it is changed.

**Comment by caioproiete** [comment]
> The add-in is not an application - Excel is the application

That's certainly one way to look at it... Or you could look at Excel as a "host" of multiple apps (add-ins), the same way that IIS and Kestrel can host multiple ASP .NET Core apps, ServiceController can a host multiple Windows Services, etc... It's a common behavior of hosts to override environmental aspects during user-code execution, and that's exactly what Excel is doing by changing the current directory to the user's documents folder.

> we should encourage re-setting at the end of the context where it is changed

Why not do that automatically? We could store the current directory just before calling `AutoOpen`, set it to the `.xll` folder path and let the add-in initialize itself, then revert back to whatever value it was previously.

**Comment by govert** [comment]
It would be good to add a bit of documentation about this. And having the option to do this around AutoOpen might be a good candidate to your 'Professional Developers' extension library.

**Comment by augustoproiete** [comment]
Closing this one as `wontfix`
