### ISSUE TITLE
[Question] .NET Framework 4.8 + VS2019 + SDK project type debugging?

### ISSUE THREAD

**Issue by jzabroski** [Excel-DNA/ExcelDna#278]
Hi @augustoproiete and @govert 

I am curious if you've hit this issue, or if I am simply doing something wrong on my side: https://stackoverflow.com/questions/58864114/new-net-core-sdk-project-type-debug-com-add-in-not-possible

While I didn't encounter this using ExcelDNA, I imagine anyone using ExcelDNA likely will also hit the same issue.  If I'm wrong, then ExcelDNA is clearly doing some additional magic and may be motivation to get me to switch from pure COM registration to ExcelDNA.

**Comment by caioproiete** [comment]
@jzabroski I've [answered you on StackOverflow](https://stackoverflow.com/a/58864762/211672). SDK-style projects are not supported by Excel-DNA at the moment and we're working on adding support for it (#193, #188, #138).

**Comment by jzabroski** [comment]
I replied in the comments.  I suspect even after you get past those three issues, you'll realize the showstopper I mentioned in StackOverflow.

Based on my example, I believe debugging with the new project type is strictly impossible.

**Comment by jzabroski** [comment]
Related, I discovered .NET Core has removed all support for "corrupted state exceptions", so if your Excel-DNA project tries to use .NET Core dll's, expect that you will not be able to recover or respond to "corrupted state exceptions".  See: 

https://github.com/dotnet/coreclr/issues/9045
https://github.com/dotnet/coreclr/pull/10957

**Comment by augustoproiete** [comment]
Hey @jzabroski,  I'm closing this one for now. Feel free to re-open if needed.
