### ISSUE TITLE
ExcelDna.Integration.dll must be strong signed

### ISSUE THREAD

**Issue by WilliamHerrgott** [Excel-DNA/ExcelDna#279]
I am trying to build my solution while using ExcelDna but i keep having this issue:
```
ExcelDna.Integration.1.0.0\lib\ExcelDna.Integration.dll' must be 
strong signed in order to be marked as a prerequisite
```

Any ideas how to solve that problem? 

Thanks in advance for the response!

**Comment by govert** [comment]
@WilliamHerrgott TL;DR Don't try to sign and strong name your class library assembly which references ExcelDna.Integration.dll - there's no good reason to.

There is an orthogonal issue which is sometimes confused with assembly signing, which is making a signed add-in to work with the Excel security. For this purpose you need to sign the packed binary .xll file that is the output of building the add-in. If this is what you are trying to do, see https://github.com/Excel-DNA/ExcelDna/wiki/Signing-the-.xll-add-in-binary-for-Excel's-Trust-Center for some further links.

Longer version:

Singing and strong naming of .NET assemblies is a somewhat controversial topic - see #223 and #250. In the context of Excel-DNA there is no benefit to having your add-in library signed, and the whole strong naming of assemblies has essentially been deprecated in the .NET ecosystem. However, we understand that some organizations have a legacy policy that requires signing their assemblies. So we have decided to sign the assembly for the next version - see #250 - to avoid future questions like this one.

However, until the next release you have the following options:
* Don't sign your add-in library (the one that references ExcelDna.Integration). This library is likely to be tightly coupled to Excel (so can't be a general purpose library) and for an add-in there is no benefit to having it signed.
* Install a package like [StrongNamer](https://github.com/dsplaisted/strongnamer) into your project which will sign ExcelDna.Integration at build-time. It's not a perfect fix (see the comment from @caioproiete  [here](https://github.com/Excel-DNA/ExcelDna/issues/223#issuecomment-550528301) ) and I have not tried it, but it looks worth a try.
* Build and sign your own version of ExcelDna.Integration.dll from source.

**Comment by WilliamHerrgott** [comment]
Thanks for your answer @govert, I tried the first method you gave, so not signing my class library but it doesn't seem to work any better, I still have the same mistake.
I therefore tried the second option you offered, and indeed installing the `StrongNamer` package fixed my issue, I think I'll use this solution until the next release. 

Do you already have an approximate date for the next release? 

Once again, thanks a lot for your answer.
