### ISSUE TITLE
Construct ExcelReference from collection of other ExcelReferences

### ISSUE THREAD

**Issue by n1l** [Excel-DNA/ExcelDna#286]
It could be useful to extend ExcelReference c'tor with such parameter if we are talking about the same sheetId.

//code sample
ExcelReference collatedReference = new ExcelReference(
                        references.Select(r => new[] { r.RowFirst, r.RowLast, r.ColumnFirst, r.ColumnLast}).ToArray(), sheetId);

but it could be better to have saometing like this:
ExcelReference collatedReference = new ExcelReference(references, sheetId);

I've created a pr for this.

**Comment by govert** [comment]
Closed by #288
