### ISSUE TITLE
Replicating BDH Insert Function Box Behavior

### ISSUE THREAD

**Issue by KD33** [Excel-DNA/ExcelDna#293]
Hello

I need to write a UDF that works similar to BDH:
- If the function is called in cell(0,0), I need to return something to this cell.  In this case, I return "See Results Below"

- The function takes the users input arguments and makes a request to an API, that returns the data in an object

- With the returned data, I use ExcelAsyncUtil.QueueAsMacro(() => { reference.SetValue(data); }) in order to write all of the data to the cells  (I've seen similar approaches done by people trying to replicate BDH).

- With the data written, to the cell, I return "See Results Below"

The function works fine, except for the fact that if the user tries to call this function from the insert function box, what I think happens is:

- With every argument entered, the function calls the formula with the supplied argument to give the user a preview of the return results

-So if the user enters all of the arguments correctly, a call will be made to the function. 
 The request to the API will be made, the data returned and the ExcelAsyncUtil.QueueAsMacro portion of the code will run.  The problem is that the user can then cancel the function, but the Queued macro will have already ran.  

- The result is that the cells supplied by reference will still be written to with data.  The difference is that the "See Results Below" portion will not be returned since the formula has been cancelled.

Ideally what I would like to do is run QueueAsMacro portion only when the function has returned.  How can I achieve this?  I don't have access to a Bloomberg terminal, but how does BDH handle a user filling out the function box, then cancelling the inputs?

Thanks

**Comment by govert** [comment]
If your user a running an up-to-date version of Excel that support Dyanmic Arrays, you should return the array result directly. There was a discussion with some code to check for this here: https://groups.google.com/forum/#!topic/exceldna/0K5yBXa610c

You can detect whether a function is being called from the Insert Function dialog with a call to ExcelDnaUtil.IsInFunctionWizard.

**Comment by KD33** [comment]
Thanks govert! Closing this.
