### ISSUE TITLE
Change ExcelDNA.Integration TargetFrameworkVersion to 4 and push to Nuget

### ISSUE THREAD

**Issue by drobertson123** [Excel-DNA/ExcelDna#294]
Currently the ExcelDNA.Integration Target Framework is set to v2.0.

<TargetFrameworkVersion>v2.0</<TargetFrameworkVersion>v2.0</TargetFrameworkVersion>>

The rest of the ExcelDNA framework is Targeting v4.0.

This is triggering a known bug in the Add-In build process;

[FindRibbons task fails when including a .NET Standard 2.0 package #2475](https://github.com/microsoft/msbuild/issues/2475)

Could you possibly redirect the framework to v4.0 and push it to Nuget.

Thanks

**Comment by govert** [comment]
The current version of the core Excel-DNA add-in supports .NET Framework 2.0 and above. Only some of the extensions packages, like the Registration extensions, require .NET Framework 4.

You might be confusing .NET Framework 2.0 (which we support) with .NET Standard 2.0 (which we don't).

Mixing Excel-DNA with a VSTO add-in won't work at all, so it's not clear that the issue you link to is relevant to Excel-DNA.

**Comment by drobertson123** [comment]
I may be off track on the cause of this problem. The FindRibbons task is notoriously buggy and errors get triggered for a wide range of reasons. I may be conflating Framework and Standard as you suggest.

Let me dig into this further and add information if I find it.

**Comment by caioproiete** [comment]
@drobertson123 Any news on the `FindRibbons` issue above?

**Comment by govert** [comment]
Closing this for now.
