### ISSUE TITLE
Excel-DNA Integration problem

### ISSUE THREAD

**Issue by SohaibQ** [Excel-DNA/ExcelDna#296]
I am using visual studio 2017 with office 2016.Giving error to integrate Excel-DNA in my project

---------------------------------------
PM>  Install-Package Excel-DNA -Version 0.33.9

Attempting to gather dependency information for package 'Excel-DNA.0.33.9' with respect to project 'MyExcelDNALiberary', targeting '.NETFramework,Version=v4.5.2'
Install-Package : Unable to load the service index for source http://packagesource.
  An error occurred while sending the request.
  The remote name could not be resolved: 'packagesource'
At line:1 char:2
+  Install-Package Excel-DNA -Version 0.33.9
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:07.7202439
PM> -----------
---------------------------------------------

**Comment by govert** [comment]
This is a problem with your NuGet configuration. You seem to have a NuGet package source set up or selected that is not standard. That package source should be something like https://api.nuget.org/v3/index.json

**Comment by caioproiete** [comment]
@SohaibQ I'm assuming @govert's answer above resolved your issue so I'm closing this one. Let us know if this is not the case.
