### ISSUE TITLE
UDFs appear without the attribute ExcelFunction

### ISSUE THREAD

**Issue by younghang** [Excel-DNA/ExcelDna#301]
I got the situation that many public functions without the attribute [ExcelFunction] appear in my catagory. I want to know how to remove them and in which case C# functions will be seen as UDF.

**Comment by caioproiete** [comment]
This is the default behavior for any Excel-DNA add-in...

If you want Excel-DNA to only register functions that have the
`ExcelFunction` attribute, set the `ExplicitExports` to `true` inside of
your .dna file:

<ExternalLibrary Path="YourAddIn.dll" ExplicitExports="true" ... />

Cheers,
Caio Proiete
https://github.com/caioproiete

**Comment by younghang** [comment]
Thanks. Appreciate  for your instruction. 
I intend to find document for reading but didn't find.
