### ISSUE TITLE
Strange Reference to  ExcelDna.Integration, Version=0.33.5730.40390

### ISSUE THREAD

**Issue by drobertson123** [Excel-DNA/ExcelDna#302]
In AutoOpen I am calling   
IntelliSenseServer.Install();

It gives me this error;

 System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'ExcelDna.Integration, Version=0.33.5730.40390, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=<Cannot evaluate the exception source>

I can't find anywhere in any code or projects where I am referring to Version=0.33.5730.40390

Every reference in my projects refer to version 1.0.7056.37028

Do you have any idea where this bad reference is coming from?

**Comment by caioproiete** [comment]
@drobertson123 Did you get to the bottom of this one?

**Comment by drobertson123** [comment]
This issue is resolved as of the latest update.
