### ISSUE TITLE
IExcelObservable does not update in recent Excel versions

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#304]
Recent changes in Excel seems to have broken our IExcelObservable implementation.
See this discussion: https://groups.google.com/forum/#!topic/exceldna/pKlSA2iX03Q

**Comment by gidven** [comment]
Hi Govert,

I read the google groups page. We have the exact same issue with this flow: first update value is reflected in the UI, any following updates are seemingly ignored (cells don't update). Our app logs show updates correctly received from our server and handled by the add-in. No errors or other suspicious behavior so we suspect a change in the Excel app causes this.

RTD confirmed broken using local and cloud machines running:
Office 365 MSO 16.0.12325.20280 32-bit
Office 365 MSO 16.0.12430.20172 64-bit
Office 2019 MSO 16.0.12430.20112 32-bit

Note we tested 2019 and got the same issue, which you mentioned someone should try in the google groups discussion.

We use the same add-in on an older version of Excel and RTD functions properly:
Office 2016 MSO 16.0.4966.100032-bit

Hope this helps and please let me know if I can contribute in any way by testing on different versions of Excel etc!

**Comment by govert** [comment]
@gidven Thank you checking and the version details. 

I should be able to push a beta NuGet package with a fix for this over the next few days.

**Comment by gidven** [comment]
Thanks for the quick reply Govert I will make sure to reserve some resources on our end to get this implemented and tested as soon as we can. Will be back with updates when I have them!

**Comment by govert** [comment]
@gidven If you fish out the latest binaries from https://github.com/Excel-DNA/ExcelDna/tree/master/Distribution and either replace and rename your unpacked .xll files, or replace the .xll files in your local NuGet package, it should work.

But I'll try to make a NuGet package soon.

**Comment by gidven** [comment]
Thanks @govert! Will UAT this across all versions listed above to confirm it works as expected once we have this implemented.

**Comment by govert** [comment]
@gidven I've now tweaked a bit more and pushed to NuGet as v1.1.0-beta1.

I'd appreciate if you could have a look and write back with anything you find.

**Comment by gidven** [comment]
With the latest beta NuGet package, I can confirm streaming is back to working state in Excel versions:

Office 365 MSO 16.0.12325.20280 32-bit
Office 2019 MSO 16.0.12430.20112 32-bit
Office 365 MSO 16.0.12430.20172 64-bit

Thanks for the help with this @govert :)

**Comment by gidven** [comment]
For completeness sake, the new package works as expected on older versions of Excel as well:

Office 2016 MSO 16.0.4966.1000 32-bit

**Comment by andymouk** [comment]
Came across this bug report while investigating the same issue in my add-in.

Can confirm package 1.1.0-beta2 appears to fix the issue (`IExcelObserver` non-initial emits not resulting in the RTD server pushing on screen updates) in Office 365 MSO 16.0.12527.20260 32-bit.

**Comment by augustoproiete** [comment]
Fixed by ExcelDna v1.1
