### ISSUE TITLE
Excel-DNA - 2020 Roadmap

### ISSUE THREAD

**Issue by arunhallan** [Excel-DNA/ExcelDna#305]
Apologies if this has been covered elsewhere.

I'm about to deploy a solution using Excel DNA. I've used it a few times before in previous firms.

Is there an updated Roadmap for the addin?  

Thanks

**Comment by govert** [comment]
Sorry @arunhallan - I have nothing to report yet.

Is there anything specific that you're interested in?

**Comment by arunhallan** [comment]
I managed to get typelibs automatically created, so nothing as of yet. 

Thanks
