### ISSUE TITLE
How to use DateTime Parameter in UDF?

### ISSUE THREAD

**Issue by Jennal** [Excel-DNA/ExcelDna#310]
I pass a Datetime value like 2019/04/04 in my UDF SayHello which accept Object parameter.

```
        [ExcelFunction(Description = "My first .NET function")]
        public static string SayHello(Object name)
        {
            switch (name)
            {
                case double val:
                    return SayHello(val);
                case string val:
                    return SayHello(val);
                default:
                    break;
            }

            return "#ERROR";
        }

        private static string SayHello(double name)
        {
            return $"Double({name})";
        }
        private static string SayHello(string name)
        {
            return $"String({name})";
        }
```

Then it return Double(43559), what is this number mean? How to get 2019/04/04 from this number?

**Comment by govert** [comment]
@Jennal Internally and through the C API which Excel-DNA uses, Excel stores and processes date/time values as doubles. So date/time is just a display formatting for a double value.
If you type or return from a function the number `4355` into a cell, you can change the formatting to date/time if you want to view this double as a date/time.
Inside your C# code you can interpret a double from Excel as a DateTime by calling `DateTime.FromOADate(...)`.

**Comment by Jennal** [comment]
@govert Thank you for your kind reply. Very clear.
