### ISSUE TITLE
ExcelDNAPack.exe fails in hosted Azure Pipeline build.

### ISSUE THREAD

**Issue by jklcns** [Excel-DNA/ExcelDna#311]
Hi,
My hosted Azure Pipeline builds have started to fail recently on ExcelDNAPack.exe.

The breaking hosted system image is `20200331.1`
The last working system image for me is `20200303`.

To replicate, I have created a sample SayHello project. It builds fine locally but fails in Azure.
The Azure pipeline is quite simple and I take the default settings for all the Azure Tasks shown in the attached image.  Full logs are also attached.  Any help appreciated.

[init.log](https://github.com/Excel-DNA/ExcelDna/files/4482608/init.log)
[build.log](https://github.com/Excel-DNA/ExcelDna/files/4482609/build.log)
![pipeline](https://user-images.githubusercontent.com/63740013/79364995-0f3fbf00-7f18-11ea-81ae-ca3f673ff642.png)

Partial Log:

```
ExcelDnaPack: bin\Release\CNS.ExcelDNA.Simple-AddIn.dna -> bin\Release\CNS.ExcelDNA.Simple-AddIn-packed.xll
"D:\a\1\s\packages\ExcelDna.AddIn.1.0.0\build\..\tools\ExcelDnaPack.exe" "bin\Release\CNS.ExcelDNA.Simple-AddIn.dna" /Y  /O "bin\Release\CNS.ExcelDNA.Simple-AddIn-packed.xll"
Using base add-in bin\Release\CNS.ExcelDNA.Simple-AddIn.xll
System.ComponentModel.Win32Exception: The operation completed successfully
   at ResourceHelper.ResourceUpdater..ctor(String fileName)
   at ExcelDnaPack.PackProgram.Pack(String[] args)
   at ExcelDnaPack.PackProgram.Main(String[] args)
```

**Comment by caioproiete** [comment]
It seems that the exception is being thrown because [a call to `BeginUpdateResource`](https://github.com/Excel-DNA/ExcelDna/blob/2aa1bd9afaf76084c1d59e2330584edddb888eb1/Source/ExcelDnaPack/ResourceHelper.cs#L96-L103) is failing on your environment.

I looked at the [release notes of the Azure Pipeline images after `20200303`](https://github.com/actions/virtual-environments/releases) and didn't see anything obvious that would explain the error you're seeing.

Perhaps you can put the code below in a console application and run it through your build pipeline to see if we can get an error code from Windows which could give us a clue?

```csharp
void Main()
{
        // Change to the path to a valid .xll file in your work folder in Azure Pipelines
	var fileName = @"bin\Release\CNS.ExcelDNA.Simple-AddIn-packed.xll";
	
	var hUpdate = BeginUpdateResource(fileName, false);
	if (hUpdate == IntPtr.Zero)
	{
		var win32ErrorCode = Marshal.GetLastWin32Error();

		Console.WriteLine($"win32ErrorCode: {win32ErrorCode}");
		throw new Win32Exception(win32ErrorCode);
	}

	EndUpdateResource(hUpdate, false);
}

[DllImport("kernel32.dll", SetLastError=true)]
private static extern IntPtr BeginUpdateResource(
	string pFileName,
	bool bDeleteExistingResources);

[DllImport("kernel32.dll", SetLastError=true)]
private static extern bool EndUpdateResource(
	IntPtr hUpdate,
	bool fDiscard);
```

**Comment by jklcns** [comment]
Caio, The above was slightly modified to accept a command line parameter and built into DebugExcelDNSPack.exe . 

It doesn't throw an error when run through the pipeline. Attached are the CNS.ExcelDNA.Simple build log and the output from the console app.

Logs are attached.
Thanks
[init.log](https://github.com/Excel-DNA/ExcelDna/files/4484848/init.log)
[CNS.ExcelDNA.Simple_build.log](https://github.com/Excel-DNA/ExcelDna/files/4484849/CNS.ExcelDNA.Simple_build.log)
[DebugExcelDNSPack.log](https://github.com/Excel-DNA/ExcelDna/files/4484850/DebugExcelDNSPack.log)

**Comment by jklcns** [comment]
It appears to be an issue when BeginUpdateResource() is called with a partial path to the packed file.

If you look at line 319 of the attached log, I run a dir command for the packed file using the partial path starting at **bin\Release**.  This is the same value you use in fileName variable in the code you provided.  I am able to find the file. 

At line 329 of the log, I run DebugExcelDNSPack.exe with the same partial path used in line 319. I am getting "the system cannot find the file specified."

At line 336 of the log, I run DebugExcelDNSPack.exe with the full path to the packed file and it is successful.

Is there a way to configured ExcelDNAPack to use the full path of the files?
Thank you.

[DebugExcelDNSPack2.log](https://github.com/Excel-DNA/ExcelDna/files/4485342/DebugExcelDNSPack2.log)
[Program.txt](https://github.com/Excel-DNA/ExcelDna/files/4485344/Program.txt)
