### ISSUE TITLE
NuGet doesn't create <ProjectName>-AddIn.dna

### ISSUE THREAD

**Issue by apoleo88** [Excel-DNA/ExcelDna#312]
Using Visual Studio 2019:

1. Create Library Class C#
2. Install with NuGet: **ExcelDna.Integration**, **ExcelDna.AddIn**, **ExcelDna.IntelliSense**. (version 1.0.0)

the File **\<ProjectName\>-AddIn.dna** is not created
The following warnings show up:
```
DNA-749570463 - Unable to find add-in to Debug
DNA-1291548950 - Operation of method not implemented.
NU1701
```

**Comment by govert** [comment]
You need to pick the project template that targets ".NET Framework" instead of the one targeting ".NET Standard".

**Comment by apoleo88** [comment]
Yes, Thank you!
