### ISSUE TITLE
Bug in Excel 365 (Version 2003): Excel starts with no default workbook or empty start page if I use the IntelliSenseServer

### ISSUE THREAD

**Issue by rusodan** [Excel-DNA/ExcelDna#314]
Hi!

I'm using the IntelliSenseServer to show the descriptions and parameters for the custom formulas that I created, but the Excel starts with a empty start page (not on the home screen).

I know this was an existing bug in older versions of Excel but I cannot find any version that fixes this. I tried with the version 1909 and the current version 2003 and the error still exists.

Do you know that the bug still not resolved? Any excel version that works fine with the IntelliSenseServer?

I tried with ExcelDna.Addin 1.0.0, ExcelDna.Integration 1.0.0 and ExcelDna.Intellisense 1.1.0. Also I tried with the beta current versions. I'm using windows 10 64 bit.

Thanks, regards!

**Comment by caioproiete** [comment]
This seems to be a bug in Excel itself, and not Excel-DNA.

* [Open to blank workbook/Open to splash backstage broken after Excel 2016 O365 Upgrade
](https://groups.google.com/d/topic/exceldna/3fIunrFUbwY/discussion)
* [Excel 2016 bug: the Excel window shows no content at startup if an XLL is registered](https://social.msdn.microsoft.com/Forums/office/en-US/a2b1b34e-5914-48df-bc19-71fa502477d2/excel-2016-bug-the-excel-window-shows-no-content-at-startup-if-an-xll-is-registered?forum=exceldev)

> 
> From: Govert van Drimmelen <govert@icon.co.za>
> Date: Wed, Sep 27, 2017 at 4:53 PM
> Subject: [ExcelDna] Re: Open to blank workbook/Open to splash backstage broken after Excel 2016 O365 Upgrade
> To: Excel-DNA <exceldna@googlegroups.com>
> 
> 
> Hi Will,
> The issue is discussed on the MSDN forums here: https://social.msdn.microsoft.com/Forums/office/> en-US/2bb21bfb-4940-4a68-9656-743ae0b8b4da/> bug-in-excel-2016-excel-starts-with-no-default-workbook-or-start-page-if-an-xll-is-registered?forum=exceldev
> I believe this is an Excel bug, as I was able to reproduce it by compiling the sample .xll add-in in the Excel SDK - with that add-in > installed the problematic behaviour happens, with no Excel-DNA or managed code involved at all.It would be nice is someone could go > through the steps to reproduce with the native C add-in, and confirm.
> 
> It might help if you can add your voice to the MSDN discussion, the bug report on the Microsoft answers > site: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_win10-mso_o365b/> bug-in-excel-2016-version-1707-excel-starts-with/9c013a9c-d600-4681-a04b-c3eeac207030?auth=1 and through the File->Feedback feature in > Excel. Alternatively if you have some access to Microsoft through a sales or account manager, that might also help to report this bug.
> A possible workaround is to install more .xll add-ins, for instance enabled the Analysis ToolPak add-in too. That seems to work around > the problem.
> -Govert
>

**Comment by augustoproiete** [comment]
@rusodan I'm closing this one. Feel free to re-open if you find out more about it.

**Comment by rusodan** [comment]
Sure @augustoproiete . Thanks!
