### ISSUE TITLE
Array Parameter cause lag

### ISSUE THREAD

**Issue by Jennal** [Excel-DNA/ExcelDna#315]
I write a Function called XLookUp2, find target by 2 column values. This is the code below.

```
        [ExcelFunction(Description = "XLookUp2(Object val1, Object[] src1, Object val2, Object[] src2, Object[] dst)")]
        public static Object XLookUp2(Object val1, [ExcelArgument(AllowReference = true)] Object[] src1, Object val2, [ExcelArgument(AllowReference = true)] Object[] src2, [ExcelArgument(AllowReference = true)] Object[] dst)
        {
            if (val1 == null || src1 == null || val2 == null || src2 == null || dst == null) throw new ArgumentException();
            if (src1.Length != dst.Length || src2.Length != dst.Length) throw new ArgumentException();

            for (int i = 0; i < src1.Length; i++)
            {
                if (src1[i] == ExcelEmpty.Value) break;

                if (val1.Equals(src1[i]) && val2.Equals(src2[i])) return dst[i];
            }

            return "#NOT_FOUND";
        }
```

Then I use this function in a 150 line sheet, and pass the `A:A` to the `src1`. It is really slow to show the results.
I tried to add `[ExcelArgument(AllowReference = true)]`, but lag still there.
I don't know why it lag. It doesn't make sence to lag in a simple for statement. It is about 10,000 loop at most. So I am wondering if the problem is alloc and free array? How can I confirm my guess?

**Comment by govert** [comment]
If you pass in `A:A`, then a millions cells are being passed in, which has some overhead in the Excel-DNA conversion. There are some tricks to keep track of the used range on the sheet, and intersect the reference passed in with the used range before marshaling the values.

For tracking the used range, here are some links:
* https://fastexcel.wordpress.com/2015/12/12/excel-full-column-references-and-used-range-good-idea-or-bad-idea/
* https://fastexcel.wordpress.com/2012/12/05/writing-efficient-udfs-part-12-getting-used-range-fast-using-application-events-and-a-cache/

**Comment by Jennal** [comment]
Thank you for your sharing. Now I convert `A:A` into a named range. The named range select the rows with data, not all rows. Then the change of the range can be automatically followed. And the lag problem solved.
