### ISSUE TITLE
Using default App Domain for ExcelDNA

### ISSUE THREAD

**Issue by dnallicus** [Excel-DNA/ExcelDna#323]
Also posted in the google group,, I don't know which place is preferred for feature requests.

I wanted to start using ExcelDna to replace some old addins, but I noticed that every ExcelDNA addin creates its own App Domain.  This causes a lot of memory bloat for me, since I have 15 other libraries that are loaded into the process, and if I call one of the libraries from ExcelDNA it reloads the library (and duplicates the associated data).  It looks like when ExcelDna is used outside of an excel process, it doesn't use a separate domain (see IsRunningOnCluster function below). My plan is to just set that to TRUE all the time for my use.  Is there any known issues with doing this? It seems like this would be a good configuration option to have when building an addin. It would also be nice to directly reference some of the dlls like ExcelDna.Integration instead of loading them from resources.

https://github.com/Excel-DNA/ExcelDna/blob/2aa1bd9afaf76084c1d59e2330584edddb888eb1/Source/ExcelDna/ExcelDnaLoader.cpp#L848

**Comment by augustoproiete** [comment]
Link to this discussion in the Excel-DNA Google Groups:

> https://groups.google.com/d/topic/exceldna/_Cc6DNSVM0E/discussion

**Comment by govert** [comment]
Closing for now - I've discussed on the Google Group and don't plan to add this feature for now.
