### ISSUE TITLE
Namespace error running in 64 bit error CS0116 A namespace cannot directly contain members such as fields or methods

### ISSUE THREAD

**Issue by raymondjstone** [Excel-DNA/ExcelDna#326]
Revisted a macro after a few months to package it up and the existing object (which was working last time I checked) now gets a strange error to which I can't see a cause

ExcelDna.Integration Error: 2 : There was an error in loading the add-in xxxxx Add-In (C:\Users\xxxxxx\bin\x64\Debug\xxxxx-AddIn64.xll):
ExcelDna.Integration Error: 2 : There were errors when compiling project: 
ExcelDna.Integration Error: 2 :     c:\Users\xxxx\AppData\Local\Temp\me4gyvfe\me4gyvfe.0.cs(1,1) : error CS0116: A namespace cannot directly contain members such as fields or methods

The temp file disappears by time this message appears so not able to locate that, and the solution itself will build ok, it's only when excel starts do I see this issue,

No  namespace in the project has the mentioned issue

**Comment by govert** [comment]
You have some spurious text in your .dna file, that Excel-DNA is trying to compile.

**Comment by raymondjstone** [comment]
Thanks, been staring at all the namespaces and never occurred to me that it was a typing error in the dna file, looks like a typing in wrong window issue sometime in the past,
