### ISSUE TITLE
DNA build fails but does not give error code to solution build process

### ISSUE THREAD

**Issue by raymondjstone** [Excel-DNA/ExcelDna#328]
I have a DNA file that includes lines such as 

   <Reference Path="Reprise.dll" Pack="true"/>
    <Reference Path="rlm1402x64.dll" Pack="true"/>
    <Reference Path="rlm1402x86.dll" Pack="true"/>

When one of these files is not found during the build the DNA packing processes stops processing references from that point onwards but do not actually fail the overall build process.   

 ~~> Assembly path Reprise.dll resolved to bin\x64\Release\Reprise.dll.
    ~~> Assembly path rlm1402x64.dll resolved to .
    ~~> Reference with Path: rlm1402x64.dll and Name:  not found.
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: LOG4NET, Length: 78448
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: MICROSOFT.OFFICE.TOOLS.COMMON.V4.0.UTILITIES, Length: 11914
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: MICROSOFT.SYNCHRONIZATION.DATA.SERVER, Length: 35018
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: SYSTEM.DRAWING, Length: 160234
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: KELTON.BASE, Length: 185822
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: MICROSOFT.SYNCHRONIZATION.DATA.SQLSERVERCE, Length: 61534
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: MICROSOFT.VISUALSTUDIO.TOOLS.APPLICATIONS.RUNTIME, Length: 23138
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: MICROSOFT.SYNCHRONIZATION.DATA, Length: 94191
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: REPRISE, Length: 11215
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: KELTON.FLOCALC, Length: 304647
    ->  Updating resource: Type: IMAGE_LZMA, Name: ADDFUNCTIONICON_0.PNG, Length: 4032
    ->  Updating resource: Type: IMAGE_LZMA, Name: EDITFUNCTIONICON_1.PNG, Length: 4087
    ->  Updating resource: Type: IMAGE_LZMA, Name: IMPORT_3.PNG, Length: 2997
    ->  Updating resource: Type: DNA, Name: __MAIN__, Length: 10002
    ->  Updating resource: Type: IMAGE_LZMA, Name: HELP_2.PNG, Length: 2784
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: MICROSOFT.SYNCHRONIZATION, Length: 84693
    ->  Updating resource: Type: IMAGE_LZMA, Name: EXPORT_4.PNG, Length: 2978
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: KELTON.FM2P, Length: 596204
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: KELTON.KCCL.CALCULATION.IMPL, Length: 363753
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: NHIBERNATE, Length: 530744
    ->  Updating resource: Type: ASSEMBLY_LZMA, Name: SYSTEM.WINDOWS.FORMS, Length: 1229879
  Completed Packing bin\x64\Release\FloXL2020-AddIn64-packed.xll.
  ExcelDnaPack: bin\x64\Release\FloXL2020-AddIn64.xll.config -> bin\x64\Release\FloXL2020-AddIn64-packed.xll.config
========== Build: 18 succeeded, 0 failed, 7 up-to-date, 0 skipped ==========

Is it possible to get this build process to fail and not give a clean result?

**Comment by govert** [comment]
Hi @raymondjstone - Yes I also think it should fail if there are unresolved files.

I think this would be a good issue for a contributor to get into - the ExcelDnaPack code is small and simple, though not elegant.
Is something you'd like to have a go at?

Over the long term I think the packing should be split into a library and a small wrapping executable, so that the library can be used directly as a build task instead of the build process calling the ExcelDnaPack executable.

**Comment by raymondjstone** [comment]
I can have a look at it as soon as I get some free time, but hopefully someone else may also pop in to look at it. Is there a contributor agreement I need to sign (some projects have these)?

**Comment by govert** [comment]
Yes there is - this is the agreement: https://gist.github.com/govert/e6c44f5ffed933dac9fb and you'll be prompted for signing through the CLA bot when you make a Pull Request.

**Comment by raymondjstone** [comment]
ok, had a quick look at the pack process looks simple enough. I'll just need to see if it's as simple as giving a non zero return code to the overall build process or if something specific is needed.

**Comment by augustoproiete** [comment]
@raymondjstone Yes, ExcelDnaPack returning an `ExitCode >= 1` is all that is needed to fail the build. The easiest way is to throw an exception describing the issue and [it will be caught by the `Main` method and the `ExitCode` will be set appropriately](https://github.com/augustoproiete-forks/Excel-DNA--ExcelDna/blob/master/Source/ExcelDnaPack/PackProgram.cs#L44).

**Comment by gmichaud** [comment]
@raymondjstone we've been by this issue more than once. Your help resolving this issue in ExcelDnaPack will be greatly appreciated!

**Comment by raymondjstone** [comment]
As time permits I have started to look at this, have a version where all errors are replaced by a throw but need to switch to my work machine to get something to check it against.

**Comment by augustoproiete** [comment]
@raymondjstone Are you still interested in sending a PR for this one?
