### ISSUE TITLE
32/64 bit builds with different dependencies

### ISSUE THREAD

**Issue by raymondjstone** [Excel-DNA/ExcelDna#329]
I have a build where the packages need to include different dependencies for 32 and 64 bit

 <Reference Path="rlm1402x64.dll" Pack="true"/>
and
 <Reference Path="rlm1402x86.dll" Pack="true"/>

I was originally going to just include both in both builds and live with the superfluous component but that does not work 

ssembly at bin\x64\Release\rlm1402x86.dll could not be packed. Possibly a mixed assembly? (These are not supported yet.)
  Exception: System.BadImageFormatException: Could not load file or assembly '666112 bytes loaded from ExcelDnaPack, Version=1.0.7056.37048, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  File name: '666112 bytes loaded from ExcelDnaPack, Version=1.0.7056.37048, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Bad IL format.
     at System.Reflection.Assembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection)
     at System.Reflection.Assembly.Load(Byte[] rawAssembly)
     at ResourceHelper.ResourceUpdater.AddAssembly(String path, Boolean compress, Boolean multithreading, Boolean includePdb)

So is there a way to have a directive that includes only the correct file for the correct configuration or if not then can one be included in a future release?

**Comment by govert** [comment]
The message indicates that the problem here is packing native libraries or mixed native/managed assemblies.
These are not currently supported, since the un-packing is done in memory and the assembly loaded from memory, so no temporary files are managed on disk. Native libraries and mixed assemblies cannot be loaded from memory - they would have to be unpacked to a temp file and loaded from there, preferably with some form of cleaning up at some time later (or with some Windows magic). So supporting that is quite a bit of work, and not something planned right now.

**Comment by raymondjstone** [comment]
yes that is the point the 32 bit build needs a 32 bit C++ dll and the 64 bit build needs the 64 bit version but there seems to be no directives for doing different things by config setting

**Comment by govert** [comment]
You can actually have different .dna files for 32-bit and 64-bit, and they are then used to pack the respective .xll files. But that won't help you, since the native libraries can't be packed.

**Comment by augustoproiete** [comment]
@raymondjstone You might be interested in [this answer](https://stackoverflow.com/a/54190410/211672) on SO: https://stackoverflow.com/a/54190410/211672

You can embed the 32-bit and 64-bit native libraries in a single .NET assembly (Any CPU) and decide which native library to extract & load at runtime, or you can create separate assemblies (32-bit and 64-bit) and embed the corresponding native library in each assembly.

![image](https://user-images.githubusercontent.com/177608/86429900-32803c00-bcc7-11ea-8a12-362bf77c02b3.png)

**Comment by raymondjstone** [comment]
Thanks, I am indeed interested in that.

For my immediate issue the solution was actually simple enough, because the addin can only be installed along with another software product I got away with just making the files I needed pack='false' and will add them to the feature in the wix package (in case the main software is 64 bit but they wanted the 32 bit plugin or vice versa). But I do plan at looking at the packing code for some other changes anyway

**Comment by Turhan8** [comment]
I am getting the same error
`could not be packed. Possibly a mixed assembly? (These are not supported yet.)`
when I create a 32 bit add-in using dotnet build command
`dotnet build -r win-x86 -c Release -p:EnvironmentName=PRD -p:DebugType=None -p:DebugSymbols=false -p:Platform=x86 --sc false`
I do not get any errors when I create a 64 bit add-in
`dotnet build -r win-x64 -c Release -p:EnvironmentName=PRD -p:DebugType=None -p:DebugSymbols=false -p:Platform=x64 --sc false`

I can create a 32 bit build without error if I build through Visual Studio UI
