### ISSUE TITLE
Function names and namespaces

### ISSUE THREAD

**Issue by raymondjstone** [Excel-DNA/ExcelDna#330]
Long shot here but

I have an old VSTO method that we are replacing it prepends the excel function with the namespace ie =@company.co.funct whereas with exceldna it is just =@funct

Is there anyway to get the namespace included so that files are backwards compatible?

**Comment by govert** [comment]
@raymondjstone See the discussion here: https://github.com/Excel-DNA/ExcelDna/issues/316

Basically you can set the name of your Excel-DNA function to have the prefix, but that still won't make Excel see this is the same type of function. So it doesn't help. You need to search & replace formulas on the sheet or something similar to change those functions from "Automation add-in" functions to "xll" functions.

**Comment by govert** [comment]
In particular see me answer here: https://github.com/Excel-DNA/ExcelDna/issues/316#issuecomment-638059043

**Comment by raymondjstone** [comment]
Thanks, will look at those,

**Comment by raymondjstone** [comment]
I need to  up my issue searching game, sorry for the repeat.

However in this case after a quick test this appears to have totally sorted my issue, rather more simply that I expected. I'll need to test more to make doubly sure but looks promising.
