### ISSUE TITLE
RunExcelDnaSetDebuggerOptions doesn't work after upgrade to v1.1

### ISSUE THREAD

**Issue by fandrei** [Excel-DNA/ExcelDna#338]
I have `<RunExcelDnaSetDebuggerOptions Condition="'$(RunExcelDnaSetDebuggerOptions)' == ''">false</RunExcelDnaSetDebuggerOptions>` param set in the build props file, but the command line arguments in my project still get overwritten with the addin's file name on every build.

**Comment by augustoproiete** [comment]
v1.1 doesn't introduce any changes to the way `RunExcelDnaSetDebuggerOptions` work, so this shouldn't happen.

Visual Studio / MSBuild cache the contents of build file. Did you follow the instructions described at the top of the .props file?

```
<!--
  If you change properties in this file, they may not come into effect until you:
     * Rebuild the solution/project

     or

     * Close Visual Studio
     * Delete .vs folder, if exists
     * Delete ProjectName.csproj.user (or equivalent for VB, F#, etc.), if exists
     * Delete SolutionName.suo, if exists
     * Open your solution/project again in Visual Studio
  -->
```

**Comment by fandrei** [comment]
@augustoproiete I didn't change this option recently, only upgraded Excel-Dna. However, deleting those settings files helped. Thanks.
