### ISSUE TITLE
Enable users to detect if add-in is running in Excel 2019 or 365

### ISSUE THREAD

**Issue by augustoproiete** [Excel-DNA/ExcelDna#340]
Microsoft decided not to bump the version number of Excel in Office 2019 and Office 365 and for this reason, the `ExcelDnaUtil.ExcelVersion` returns `16` for Excel 2016 or 2019 or 365 and users cannot easily tell which version of Excel their add-in is running other than knowing it's >= 2016

```
Excel2003 = 11 => Office 2003
Excel2007 = 12 => Office 2007
Excel2010 = 14 => Office 2010
Excel2013 = 15 => Office 2013
Excel2016 = 16 => Office 2016 or 2019 or 365
```

In terms of API, I think it makes sense to leave `ExcelDnaUtil.ExcelVersion` as is, and introduce a new property in `ExcelDnaUtil` e.g. `ExcelVersionName` that returns a string with the Office version e.g. `Excel 2013`, `Excel 2019`, etc.

---

ps: This does not affect our MSBuild tasks because we only attempt to detect the version of Excel in order to find where `EXCEL.EXE` is located, in order to determine the bitness, and the registry key continues to be the same as Excel 2016 for Excel 2019 & 365.

**Comment by govert** [comment]
I'm not sure it's so helpful to distinguish 2019 from a 365 subscription, since the features kind of overlap (2019 is a snapshot or fork of the 365 stream of versions, now getting separate patches). So it's not useful for either feature or bug detection. How do you want to use it?

**Comment by garethhayter** [comment]
I would really like to distinguish between Excel installed from the Microsoft Store versus standard install, due to the different way that the registry is used. This would be extremely useful.

**Comment by augustoproiete** [comment]
@govert Be able to pinpoint the exact version of Excel the user is running helps the add-in developer in trying to reproduce errors reported as well as suggesting workarounds to the add-in user.

[I've been storing `ExcelDnaUtil.ExcelVersion` in the diagnostic logs of my add-ins for years](https://github.com/augustoproiete/serilog-enrichers-exceldna), and it's one of the first things I look when troubleshooting issues my users report.

[![image](https://user-images.githubusercontent.com/177608/87364887-260fa500-c54b-11ea-83c2-63df680c25fb.png)](https://github.com/augustoproiete/serilog-enrichers-exceldna)

With Excel 2019, 365, as well as the Microsoft Store install that @garethhayter mentioned, `ExcelDnaUtil.ExcelVersion` alone is not as useful anymore...

**Comment by garethhayter** [comment]
Vote++ for knowing the exact version that a user has installed, for debugging purposes. I also include the exact version in error reports.

**Comment by govert** [comment]
To be clear - my objection was not about adding a helper to get detailed version information, but about the fact the "Excel 2019" vs. "Office 365" is not a useful distinction. Ideally we'd want two sets of information, the version from the _File -> Account_ screen showing the build,  channel and install mode:
`Version 2008 (Build 131202.20002 Click-to-Run)`
and then also the _About_ info
`Microsoft Excel for Microsoft 365 MSO (16.0.131202.20002) 32-bit`

I guess one would have to trawl through the registry to find the relevant bits and pieces.

(And even then, this is not enough for feature detection like knowing whether the Dynamic Arrays of StockHisotory is supported in the running instance.)

**Comment by govert** [comment]
This is the result of `FileVersionInfo.GetVersionInfo(Process.GetCurrentProcess().MainModule.FileName)`

```
Comments: 
CompanyName: Microsoft Corporation
FileBuildPart: 13102
FileDescription: Microsoft Excel
FileMajorPart: 16
FileMinorPart: 0
FileName: C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE
FilePrivatePart: 20002
FileVersion: 16.0.13102.20002
InternalName: Excel
IsDebug: False
IsPatched: False
IsPrivateBuild: False
IsPreRelease: False
IsSpecialBuild: False
Language: Language Neutral
LegalCopyright: 
LegalTrademarks: 
OriginalFilename: Excel.exe
PrivateBuild: 
ProductBuildPart: 13102
ProductMajorPart: 16
ProductMinorPart: 0
ProductName: Microsoft Office
ProductPrivatePart: 20002
ProductVersion: 16.0.13102.20002
SpecialBuild: 
```
