### ISSUE TITLE
.DNA file names for splitting by 32/64 bit

### ISSUE THREAD

**Issue by raymondjstone** [Excel-DNA/ExcelDna#345]
In the past on some questions this was mentioned

"You can actually have different .dna files for 32-bit and 64-bit, and they are then used to pack the respective .xll files."

Now sure if I have missed it somewhere in the docs but I can't see any mention on how to have different .DNA files for 32 and 64 bit builds

**Comment by raymondjstone** [comment]
ok, some progress I think its '' for 32 bit and 64 for 64 bit so AddIn.dna goes to AddIn64.dna
this is in exceldna.build.props (within properties in the project).

however using this (and assuming it's now picking up the correct files) there seems to be no way to only build the 32 bit version when building solution for x86 and only building the 64 bit when building the solution for x64.

there are other entries in the prop file 

 <ExcelDnaCreate32BitAddIn Condition="'$(ExcelDnaCreate32BitAddIn)' == ''">true</ExcelDnaCreate32BitAddIn>
    <ExcelDnaCreate64BitAddIn Condition="'$(ExcelDnaCreate64BitAddIn)' == ''">true</ExcelDnaCreate64BitAddIn>

But I don't know if the prop file can be changed based on bitness or not,

**Comment by govert** [comment]
Have a look at this discussion:
https://groups.google.com/g/exceldna/c/oNEDMHvYg5E

**Comment by raymondjstone** [comment]
Thanks, that's what I was looking for. And for future reference incase the link ever stops working


aug...@proiete.com
unread,
16 Aug 2020, 02:45:30 (3 days ago) 
to exce...@googlegroups.com
Hi,

Yes, you can change this behavior and generate the XLLs based on the platform selected during build.

Inside the file `Properties\ExcelDnaBuild.props` you have the build parameters `ExcelDnaCreate32BitAddIn` and `ExcelDnaCreate64BitAddIn` which define if the XLL for these platforms should be created or not, and the `Condition` attribute allows you to specify a boolean expression to assign the value (true or false) to these parameters.

By default, the build process will always assume `true` and create .XLLs for both 32 and 64-bit, so the first thing you need to do, is to change the defaults by disabling them:

<PropertyGroup>

  <ExcelDnaCreate32BitAddIn>false</ExcelDnaCreate32BitAddIn>

  <ExcelDnaCreate64BitAddIn>false</ExcelDnaCreate64BitAddIn>

</PropertyGroup>


This completely disables the creation of XLLs in the output for both platforms.

Then, you can selectively enable each one, based on the platform:

<PropertyGroup>

  <ExcelDnaCreate32BitAddIn>false</ExcelDnaCreate32BitAddIn>

  <ExcelDnaCreate64BitAddIn>false</ExcelDnaCreate64BitAddIn>

  <ExcelDnaCreate32BitAddIn Condition="'$(Platform)' == 'x86'">true</ExcelDnaCreate32BitAddIn>

  <ExcelDnaCreate64BitAddIn Condition="'$(Platform)' == 'x64'">true</ExcelDnaCreate64BitAddIn>

</PropertyGroup>


The above will only generate a 32-bit add-in when the platform selected is x86, and will only generate a 64-bit add-in when the platform selected is x64. No add-in is generated when the platform selected is AnyCPU.

If you want to change that, so that in AnyCPU it generates the two add-ins as it is today, then you can enable it for AnyCPU as well, in addition to the other platforms.

<PropertyGroup>

  <ExcelDnaCreate32BitAddIn>false</ExcelDnaCreate32BitAddIn>

  <ExcelDnaCreate64BitAddIn>false</ExcelDnaCreate64BitAddIn>

  <ExcelDnaCreate32BitAddIn Condition="'$(Platform)' == 'x86' OR '$(Platform)' == 'AnyCPU'">true</ExcelDnaCreate32BitAddIn>

  <ExcelDnaCreate64BitAddIn Condition="'$(Platform)' == 'x64' OR '$(Platform)' == 'AnyCPU'">true</ExcelDnaCreate64BitAddIn>

</PropertyGroup>


Cheers,
C. Augusto Proiete
https://augustoproiete.net
