### ISSUE TITLE
What sets the command line arguments in Properties/Debug/Start options?

### ISSUE THREAD

**Issue by cirrusone** [Excel-DNA/ExcelDna#347]
I'm trying to remove the command line arguments in Properties/Debug/Start options but each time I delete it, when the project rebuilds it's re-assigned. What setting affects this and how do I keep it blank?

![Untitled](https://user-images.githubusercontent.com/10389314/90768406-9053fc00-e2e6-11ea-9458-db1c319dc8d6.png)

I've tried editing the `ExcelDna.Build.props` file by commenting out the following lines but these don't appear to affect it
```

<!--<RunExcelDnaSetDebuggerOptions Condition="'$(RunExcelDnaSetDebuggerOptions)' == ''">true</RunExcelDnaSetDebuggerOptions>-->
<!--<ExcelDnaExcelExePath Condition="'$(ExcelDnaExcelExePath)' == ''"></ExcelDnaExcelExePath>-->
<!--<ExcelDnaAddInForDebugging Condition="'$(ExcelDnaAddInForDebugging)' == ''"></ExcelDnaAddInForDebugging>-->
```

**Comment by augustoproiete** [comment]
In order to disable that behavior you need to set `RunExcelDnaSetDebuggerOptions` to `false`. The default is `true` so commenting out doesn't have any effect.

Out of curiosity, what are you disabling it?

**Comment by augustoproiete** [comment]
NB: You might need to restart Visual Studio for the changes to the `ExcelDnaBuild.props` file to be applied because Visual Studio/MSBuild sometimes cache this file.

**Comment by cirrusone** [comment]
Thanks, that's working.

I'm testing with both 32bit and 64bit Excel on the same PC so the command line arguments sometimes get in the way depending on what I'm testing.

**Comment by augustoproiete** [comment]
Thanks @cirrusone

It looks like you're playing with fire there! :fire::fire: :smile:

[https://support.microsoft.com/en-us/office/choose-between-the-64-bit-or-32-bit-version-of-office](https://support.microsoft.com/en-us/office/choose-between-the-64-bit-or-32-bit-version-of-office-2dee7807-8f95-4d0c-b5fe-6c6f49b8d261#32or64Bit=Office_2013)

[![image](https://user-images.githubusercontent.com/177608/90835808-e6936000-e323-11ea-8927-ed252d752814.png)](https://support.microsoft.com/en-us/office/choose-between-the-64-bit-or-32-bit-version-of-office-2dee7807-8f95-4d0c-b5fe-6c6f49b8d261#32or64Bit=Office_2013)

**Comment by PhilippeRaemy** [comment]
Might be a little late on this thread, but I've also got a reason to prevent resetting the debug options on build: I want to start a fresh excel instance each time (adding parameter /x to the command line), and starting a test spreasheet.
So my debug command line becomes :
 /x MyAddin.xll MyTestSpreadSheet.xlsx

**Comment by augustoproiete** [comment]
@PhilippeRaemy Thanks. FYI in the next version of Excel-DNA opening a new Excel instance will be the default behavior (i.e. the `/x` will be added for you automatically). See https://github.com/Excel-DNA/ExcelDna/pull/344
