### ISSUE TITLE
CTRL ALT F9 required on workbook following deployment of new xll

### ISSUE THREAD

**Issue by Chadders187** [Excel-DNA/ExcelDna#362]
Evening all,

Back again, unfortunately! I've seen similar issues in the forums but they seem to be from many years back so I'll go from scratch

We are finding that if we have a deployed xll where Test() returns X, and then we update the xll file where Test() returns Y, the value Y is only calculated following a CTRL ALT F9 or "return" on the cell itself.

Is this a known "issue"? Or maybe is this something you can advise on how to sort? The issues referred to previously regarding a full recalculation on opening feel very relevant here and may in fact be the same issue.

I must note that the "update/deployment" is currently a basic copy and paste.

Thanks,

Josh

**Comment by joycestick** [comment]
Is the function marked as volatile? If not, the inputs to the function haven’t changed and so Excel will not recalculate it. If you need it to recalculate automatically you need to set the function to be volatile.

**Comment by Chadders187** [comment]
> Is the function marked as volatile? If not, the inputs to the function haven’t changed and so Excel will not recalculate it. If you need it to recalculate automatically you need to set the function to be volatile.

Whether it is volatile or not volatile, the Excel still shows the incorrect value X on opening the workbook. Regardless, that would mean any function that ever takes an updated code base would need to be Volatile?

Using IsVolatile is also not updating cells automatically for this function call "LCP_BlackModel(B1,B2,B3,B4)" until I hit F9. Is this because the ExcelArgument attribute needs an "AllowReference = true" flag? In which case, I'd need to add to all parameters?

**Comment by govert** [comment]
I do not use Excel much, but I don't expect Excel to recalculate a workbook when opening. Sometimes Excel does recalculate a workbook - I think this is when the workbook was last saved with a different version of Excel. But this is normally considered a problem, and you'll find lots of people trying to figure out why they have this problematic behaviour if you Google for "excel recalculate workbook when opening"
So under normal circumstances I think it would recalculate (unless you have volatile functions etc...).

I think you could manage whether workbooks are fully recalculated when opening by handling the Application.WorkbookOpen event, and forcing a recalc there.

**Comment by Chadders187** [comment]
> I think you could manage whether workbooks are fully recalculated when opening by handling the Application.WorkbookOpen event, and forcing a recalc there.

Is this something that you can do via the xll or ExcelDna? Or something that has to be done elsewhere?

> Using IsVolatile is also not updating cells automatically for this function call "LCP_BlackModel(B1,B2,B3,B4)" until I hit F9. Is this because the ExcelArgument attribute needs an "AllowReference = true" flag? In which case, I'd need to add to all parameters?

Any comments or thoughts on this one too?

**Comment by govert** [comment]
You should be able to do that in the add-in.  I don't have a nice example at hand, but it would go something like this:

* You need to add a reference to the COM object model (easiest is to install the `ExcelDna.Interop` package from NuGet).
* Then in your add-in's `AutoOpen` method (in a class which implements `IExcelAddIn`) you get hold of the root Excel `Application` object with a call to `ExcelDnaUtil.Application`.
* This will be a COM Application and you can hook up events etc. from there.

**Comment by joycestick** [comment]
Following on from Govert's response, I think what you're looking for is something like this (not tested, apologies):

```using System;
using System.Runtime.InteropServices;
using System.Windows;
using ExcelDna.Integration;
using Microsoft.Office.Interop.Excel;
using Application = Microsoft.Office.Interop.Excel.Application;

namespace MyAddIn
{
    [ComVisible(true)]
    public class AddIn : IExcelAddIn
    {
        private Application _xl;

        public void AutoOpen()
        {
            try
            {
                _xl = (Application)ExcelDnaUtil.Application;
                _xl.WorkbookOpen += OnWorkbookOpen;
            }
            catch (Exception e)
            {
                MessageBox.Show($"An error occurred when starting the XLL:\n\n{e.Message}", "XLL Error");
            }
        }

        public void AutoClose() { }

        private void OnWorkbookOpen(Workbook workbook)
        {
             _xl.CalculateFull();
        }
    }
}

**Comment by Chadders187** [comment]
@govert @joycestick Thanks both - the implementation of the above worked a treat and makes sense following additional research around opening/volatile functions etc.... At least we have a solution now and we can consider the knock on impacts of the CalculateFull on opening across the business. 

Thanks again, your help once again is much appreciated.
