### ISSUE TITLE
Accessing workbook state inside ThreadSafe UDF

### ISSUE THREAD

**Issue by MaximGurschi** [Excel-DNA/ExcelDna#366]
Hi,

Excel UDFs are declared as static methods.
Suppose i have a ThreadSafe declared UDF - MyUdf.
Is there a way for MyUdf to "know" which workbook is invoking it?
If i attempt to access "Application" then Excel freezes until i kill the process.

My goal is to known, inside MyUdf, of a piece of data that is tied to the workbook that invokes the executing instance of MyUdf.

Is such a thing possible? My current proxy for this is registering for WorkbookActivate event and updating "current workbook". But i'm concerned that there are some edge cases where this is not sufficient (for example i don't know if the same Excel process can calculate two workbooks concurrently - which would make the event approach broken).

**Comment by govert** [comment]
Inside your UDF you can ask for the caller information (a reference to the cell where the formula is that is being evaluated).

You do this with a call to the C API, which looks like this:
```cs
   var caller =XlCall.Excel(XlCall.xlfCaller) as ExcelReference;
```

The result is normally an `ExcelReference` object, but can sometimes be something else (so `caller` above will be null) if the UDF is called from a different context, like from a VBA procedure.

Now with the `ExcelReference, you can get the workbook and sheet name like this:
```cs
   var callerSheetName = XlCall.Excel(XlCall.xlSheetNm, caller) as string;
```

Now you have the name in the format `[MyWorkbook]Sheet1`.

Together, a little sample function looks like this:
```cs
        [ExcelFunction(IsThreadSafe = true)]
        public static string GetCallingSheetName()
        {
            var caller = XlCall.Excel(XlCall.xlfCaller) as ExcelReference;
            var callerSheetName = XlCall.Excel(XlCall.xlSheetNm, caller) as string;
            return callerSheetName;
        }
```
You can use either the caller `ExcelReference` or the workbook and/or sheet name in a dictionary to manage other information.
Keep in mind that the threadsafe function may be executing in parallel, so you need some locking or concurrency management around any dictionary that may be accessed from multiple threads concurrently.

In general you should access the Excel COM object model from other threads.

**Comment by MaximGurschi** [comment]
@govert That is great! Am i able to use the ExcelReference as the map key? Will it work as expected?

ie, will this be consistent:

var **caller** = XlCall.Excel(XlCall.xlfCaller) as **ExcelReference**;

Dictionary<ExcelReference, MyState> _map = new Dictionary<ExcelReference, MyState>();

_map.TryGetValue(**caller**, out myState);

**Comment by govert** [comment]
Yes you can - `ExcelReference` implements equality etc. in a way that makes it suitable as the key in a dictionary.

**Comment by govert** [comment]
Note that bad things may happen if you try to use the `ExcelReference` when the sheet no longer exists. For example the `xlSheetNm` call might crash your Excel. Checking whether the sheet of an `ExcelReference` still exists is problematic, but there was some code on GitHub or the Google group to check this safely.

**Comment by MaximGurschi** [comment]
Perfect! So in that regard does ExcelReference represent the workbook? Can you please let me know what is the semantics of ExcelReference type?

**Comment by MaximGurschi** [comment]
Argh there is a gotcha then :)

Do you know of a foolproof way to go from ExcelReference to Interop Workbook? Or something similar? What i really need to do is tie the UDF call to the workbook's internal custom xml parts.

**Comment by govert** [comment]
The `ExcelReference` represents a rectangle of cells (or multiple rectangles of cells) on a specific sheet.
You can get the name of the workbook and the sheet in the workbook as I showed above, and you can do this safely when the UDF is first called. But if you store the `ExcelReference`. e.g. in a `Dictionary`, you might have to take care how you use it later, when the sheet it refers to might no longer exist.

You can read the workbook name as I show above.
But you can't access the COM object model from the UDF thread-safe context. So you must either store the extra information in your own internal dictionary earlier, and then read back from there, or do the COM interaction later in some other execution context.

It does indeed get tricky, and depends on what you want to do.

**Comment by MaximGurschi** [comment]
Ok, it is tricky as i suspected! 

How about this. Is there any (combination) of values i can extract from ExcelReference/XlCall to tie them back to the workbook?

I'm not sure the workbook name is foolproof, as you can have clashing workbook names. Is there any special value i can get from XlCall that would be a reliable way to tie it back to the workbook the udf runs in? It does not have to be the Interop/COM Workbook reference.

A contrived example of what i want to be able to achieve:

//Has the ability to do lookups based on the workbook from which the UDF is running.
private static readonly MyCollection _workbooks;

[ExcelFunction(IsThreadSafe = true)]
public static int Foo()
{
//Get something from ExcelReference/XlCall.
var uniqueKeyAmongOpenWorkbooks=.....;

var value = _workooks.GetResult(uniqueKeyAmongOpenWorkbooks);

return value;
}

The way i currently do this is by subscribing to WorkbookActivate event and have "uniqueKeyAmongOpenWorkbooks" key be a static field that i change depending on what the activated workbook is. I suspect however that this is not reliable.

**Comment by govert** [comment]
You can get the workbook and sheet names from the ExcelReference. The workbook name is unique in the Excel instance and appropriate for what you are asking. I don't know what you mean about 'clashing workbook names'. You do have to track the workbook opening and closing, AfterSave etc. since doing SaveAs could change the workbook name, so in that sense it is not a stable identity over time. But if you manage and keep up to date through the COM events a cache that maps workbook name to extra data, you can pretty reliably look it up with the name in that thread-safe UDF context.

**Comment by keithalewis** [comment]
You can also use [xlfGetWorkbook](https://xlladdins.github.io/Excel4Macros/get.workbook.html).

**Comment by garethhayter** [comment]
You can also store a unique id in CustomDocumentProperties and use it for tracking purposes.

**Comment by MaximGurschi** [comment]
@govert I thought that you can open workbooks with same name in the same Excel process but it does not allow that! In that case your approach does work.

So is it something like this - to get the workbook name?
 
var caller = XlCall.Excel(XlCall.xlfCaller) as ExcelReference;
var workbookName = XlCall.Excel(XlCall.xlcWorkbookName, caller) as string;

@garethhayter I am using an id generated in the custom xml props but that cannot be accessed from the threadsafe UDF, so i have to do some other gymnastics.

**Comment by MaximGurschi** [comment]
I see that:
XlCall.Excel(XlCall.**xlcWorkbookName**, caller) as string
, throws an exception. Is there another way to get the workbook name?

Shall i then use:
XlCall.Excel(XlCall.**xlSheetNm**, caller) as string
, and parse the workbook name from the sheetname? To get the workbook name, is it reliable to parse the string between the [] (square brackets) of the sheet name?

**Comment by govert** [comment]
Yes, you should use xlSheetNm and look for the workbook name in the brackets.

**Comment by MaximGurschi** [comment]
Thank you!

**Comment by govert** [comment]
Great @MaximGurschi - glad to help. If you're interested in a more formal support agreement for Excel-DNA, you're welcome to contact me directly at govert@icon.co.za.
