### ISSUE TITLE
Volatile function get calculated before Workbook events

### ISSUE THREAD

**Issue by MaximGurschi** [Excel-DNA/ExcelDna#367]
Hello,

I hope this is related to ExcelDna.

I notice that if i have a workbook with a UDF i coded up accepting a the result of a volatile function call, then the workbook open event fires after the function is already calculated.

Example:

[ExcelFunction(IsThreadSafe = true)]
public static bool MyUdf(DateTime dt)
{
  //..
}

, if i call that as:
=MyUdf(**NOW()**)
, then when i open my workbook my WorkbookOpen event callback is triggered after MyUdf is invoked.
However if the workbook has a single function like:
=MyUdf(**static date**)
, then the event fires first.

I need to execute some code on workbook open but before any functions are executed. Is there a trivial event (or something that achieves the same) i can subscribe to (that handles the volatile case)? I do have a workaround but it involves tracking the first function call without a matching open event - this is not as nice.

**Comment by govert** [comment]
Is this true for both Application.WorkbookOpen and Workbook.Open?

**Comment by MaximGurschi** [comment]
I will try but where would i get the Workbook instance reference from to subscribe to its Open event?

The user double clicks an xslx to open it so the workbook instance must already be available for me to subscribe to the Open event.

**Comment by govert** [comment]
You can make a VBA event handler on the Workbook just to check.
But I doubt that will make a difference.
Nothing else I can think of :-(

**Comment by MaximGurschi** [comment]
I will try your approach.

If it does not work, i'm thinking of possible workarounds. One that i have in mind will require me to workout the file name (full path) of the workbook currently executing the UDF.

You have showed me how to get the short name from within a UDF-is there a way to get the full workbook path of the workbook executing the udf?

**Comment by keithalewis** [comment]
Use [xlfGetDocument](https://xlladdins.github.io/Excel4Macros/get.document.html) with `type_num` 2.

**Comment by MaximGurschi** [comment]
@govert The event on the workbook itself still runs after the volatile function dependent is already evaluated (as you feared) .

@keithalewis Suggested xlfGetDocument, but that seems to bomb for me when the thread safe UDF is invoked.
I tried (XlCall.Excel(XlCall.xlfGetDocument, 2)) inside the UDF but it throws.

This works as expected when the ThreadSafe UDF that has a volatile NOW() parameter passed in as input runs before the WorkbookOpen event.
caller = XlCall.Excel(XlCall.xlfCaller) as ExcelReference;
XlCall.Excel(XlCall.xlSheetNm, caller);

If only i could get the full path of the workbook - not just the short name, then i can do a workaround.

So my questions are:
1. Does anyone know of an Event that, when the workbook is opened, actually runs before any UDF that might depend on a volatile parameters, or alternatively;
2. Retrieve the full path to the workbook, from within the execution of the UDF. I have a way to get the short name, but not the complete path.

**Comment by keithalewis** [comment]
@MaximGurschi When calling Excel4 command equivalents you may need to specify the function is `Uncalced`. You might also want to try passing an explicit missing third argument.

**Comment by MaximGurschi** [comment]
@keithalewis 
I'm not sure what you mean.

I've also found an old post, where @govert specifies that there are Class 1 and Class 2 udfs.
https://groups.google.com/g/exceldna/c/DUNfSIoDarA

A thread safe UDF is Class1 (as it cannot be Class2) and is not allowed to call things like xlfGetDocument. Only Class2 can.

So it seems that the object model in Excel itself makes it impossible to get the file path from within a ThreadSafe UDF.

If this is indeed the case then i think my only option is some sort of callback that i can supply when the user opens a workbook, and this callback is guaranteed to run before any UDF.

While investigating this i noticed many strange things.

For example a static constructor in C# being invoked twice?! A large workbook i have, when i open it, the breakpoint in the static ctor fires twice.

Another odd thing is that the same workbook can perform an arbitrary number of UDF calls before the workbookopen event is called.

My goal is to read a CustomXmlPart of the opened workbook BEFORE any UDF in that workbook are called. But Excel seems to want to start running UDFs before the WorkbookOpen event.

**Comment by keithalewis** [comment]
@MaximGurschi You specify an uncalced function by placing a `#` in the type text when registering a function. See [this](https://docs.microsoft.com/en-us/office/client-developer/excel/xlfregister-form-1#registering-worksheet-functions-as-macro-sheet-equivalents-handling-uncalculated-cells) for the details. You are correct that this is not permitted for asynchronous functions.
Instead of relying on events, you can call your function before registering the UDFs. I'm not sure how to do that using ExcelDna, but I'm sure @govert  has a hook for that.

**Comment by MaximGurschi** [comment]
@keithalewis To clarify, are you implying that Excel (or rather exceldna) registers udfs per workbook?

What i mean, if i open workbook W1 then open W2 while W1 is still open, then Excel runs code to register the UDFs for W2 too, even though it already did it for W1?

If so then this is equivalent to what i want to achieve through the WorkbookOpen event, but instead of this being an Application event, this would be an ExcelDna event (callback) that we can interact with. @govert  is there such a custom ExcelDna callback we can supply so that it is always called before the UDFs are registered?

**Comment by keithalewis** [comment]
@MaximGurschi The functions are registered when the add-in is opened. You can use [xlcOnWindow](https://xlladdins.github.io/Excel4Macros/on.window.html) to run a macro when a workbook is activated.

**Comment by MaximGurschi** [comment]
@keithalewis I've added the call to:

public void AutoOpen()
{
   IntelliSenseServer.Install();
   XlCall.Excel(XlCall.xlcOnWindow, null, "**TestFunction**");
}

[ExcelFunction]
public static void **TestFunction**()
{
   var wb = DnaExcelApplication.ExcelApp.ActiveWorkbook.Name;
}


When i open the workbook that has a UDF that takes a volatile NOW() date parameter as input, then the UDF is still executed first. Only after that does TestFunction run.

Perhaps there is no way to have code executed before this volatile chain runs?

**Comment by MaximGurschi** [comment]
Closing the issue, as there does not seem to be a deterministic solution to this problem.
