### ISSUE TITLE
excel addin non-compatible with windows 10 version 1909

### ISSUE THREAD

**Issue by Protosseler** [Excel-DNA/ExcelDna#371]
The c# addin is not recognized by excel after this windows update. I tried this version of ExelDna but did not solve the problem. I wonder if there is something could be done within this project to resolve the compatibility issue. Thank you.

**Comment by govert** [comment]
In general, Excel-DNA is compatible with all versions of Windows. The upgrade might have changed some settings on your computer to break things, but the Windows version is not a problem.

Can you test by trying to open the add-in from inside Excel, by clicking File -> Open and selecting the add-in?
What do you see then?

**Comment by Protosseler** [comment]
Thank you for the reply. Indeed the windows upgrade may have changed some other parts in our code library so the compilation of the addin was erroneous. We rebased our whole code library and the addin worked again.
