### ISSUE TITLE
code changes necessary for x64 xll packing

### ISSUE THREAD

**Issue by ian-cole-mcdavid** [Excel-DNA/ExcelDna#38]
### documentation suggestion

In **Excel-DNA - Step-by-step C# add-in.doc**, in addition to _Load the corresponding ExcelDna64.xll file instead._ can you please add _Also, ensure that the ExcelDna64.xll file is used in the packing process if applicable_? This would make it absolutely clear that this is necessary.
### code changes necessary for x64 xll packing

The following code in _Source\ExcelDnaPack\PackProgram.cs_ had to be changed from

> xllInputPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ExcelDna.xll");

to 

> xllInputPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ExcelDna64.xll");

**Comment by govert** [comment]
You're right that the getting started documentation is out of date.

The suggested approach is to use the NuGet package, which configures everything automatically.

Is there still value in having an alternative approach documented?

**Comment by ian-cole-mcdavid** [comment]
I guess not. Thank you for the response.
