### ISSUE TITLE
Excel file gets corrupted after saving with specific defined names

### ISSUE THREAD

**Issue by akashkarov** [Excel-DNA/ExcelDna#385]
When opening and saving ExcelPackage with the following format of defined name's reference, the Excel file is treated as corrupted, and such defined names are removed on repair.

='\\test.sharepoint.com@SSL\1\2\[file.xlsm]Something'!$A$1

**Comment by govert** [comment]
@akashkarov This sounds like an issue with EPPlus and not Excel-DNA.
Are you perhaps posting to the wrong repository?
Excel-DNA has no code to read or write Excel files.

**Comment by akashkarov** [comment]
@govert You're right, sorry for the inconvenience.
