### ISSUE TITLE
Use unity build rather than PCH

### ISSUE THREAD

**Issue by davidhunter22** [Excel-DNA/ExcelDna#394]
IMHO PCH is brittle and causes all sorts of problems for not much gain.
I would suggest either not using it at all or using a Unity build 
https://devblogs.microsoft.com/cppblog/support-for-unity-jumbo-files-in-visual-studio-2017-15-8-experimental/
instread.
I will submit a PR just for ExcelDna.Host so you can take a look and see what you think.

**Comment by govert** [comment]
I've never had problems with that, but I'm happy to take it out.
Not sure I'm up to learning about the unity build thing, though.
It's a tiny project, after all.

**Comment by davidhunter22** [comment]
OK, as I said you can switch off the Unity build in the properties so you can just merge then switch the "Include in Unity File" to No. I did do some wall clock timining of builds, the origional PCH build seemed to take about 7 seconds, with PCH removed and without Unity, so a regular build, seemed to take at most a second longer.
If you do switch it off I would suggest switching on the /MP multi processor flag, that way the .cpp files will build in parallel anyway.

BTW I think I added an extern flag onto the "PFN thunks" variable in the wrong place to get the unity build to work. I added it in addins.cpp when it should be added to the one in exports32.cpp. It may be better to declare the array in the exports.h header anyway. Let me know if you want me to fix this.

**Comment by govert** [comment]
OK great, I've merged it in for the experimental ExcleDna.Host project, but I would prefer to keep the main ExcelDna project as it is.

**Comment by govert** [comment]
Would you like to look at something more functional, like dealing with the packed ExcelDna.ManagedHost.dll file, which needs to be unpacked to some temp file and managed from there?

**Comment by davidhunter22** [comment]
Sure. I'm only putting out suggestions for ExcelDna.Host. I assume if you want to you can port them over to ExcelDna
