### ISSUE TITLE
Writing output to multiple cells

### ISSUE THREAD

**Issue by mvind** [Excel-DNA/ExcelDna#399]
Suppose I have a 2D object in VB, fx. a time series, and I want to write output into excel using Excel-DNA. 
Is it possible to develop a addin with a UDF likeso:
```
=get2Ddata("Path\timeseries.csv")
```
where the excel function writes out the data besides/below the refferecing cell calling the formula? 

How would you write a 2d object to multiple cells using visual basic and excel-dna?

**Comment by govert** [comment]
For this you really, really want to use the "Dynamic Arrays" functionality that is available in current Office 365 versions of Excel. This will automatically take an array result from a UDF (whether in an Excel-DNA add-in or VBA) and expand it as you describe. In addition, there are some formula extensions that also expand to the array dynamically, so if you had that formula in cell A1, you can say something like `=SORT(A1#, ...)` to sort the resulting array; the `A1#` refers to the whole dynamic array returned by your function. You can start with some references from here: https://github.com/Excel-DNA/ExcelDna/wiki/Dynamic-Arrays or just Google "Excel Dynamic Arrays" to get loads of links and videos etc.

**Comment by mvind** [comment]
@govert Thanks for a quick answer. Maybe I have written my question badly, but my question is not about the unknown dimensions of some object, but rather how VB code should look to write the output out into multiple cells?

For example I want to create: 
```
Public Function MakeArray(rows As Integer, columns As Integer) As Object
			Dim result As Object(,) = New Object(rows - 1, columns - 1) {}
			For i As Integer = 0 To rows - 1
				For j As Integer = 0 To columns - 1
					result(i, j) = i + j
				Next
			Next

			' Return result
                       [VB code for writing the result object into excel, below the cell that
                        calls "=makeArray(3,3)", in this case  3x3 individual cells]

End Function
```

I'm not looking for array formulas where you have to select a range. 

Right now I am looking at
```
dim reference = New ExcelReference(...) 
```
To somehow get the  coordinates from cell which calls the function. 

Hope it make sense, thanks for taking the time!

**Comment by govert** [comment]
Hi @mvind - the "Dynamic Arrays" feature of Excel is exactly what you are looking for. New versions of Excel will automatically write the result array to the 3x3 cells to the right and below your formula. You need no extra VB code. I suggest you check some of the links.

If you _have_ to use an old version of Excel, there are some horrible workarounds (see for example here: https://github.com/Excel-DNA/ExcelDna/blob/master/Distribution/Samples/ArrayResizerVB.dna), but you really are wasting your time and effort by going down that road

**Comment by mvind** [comment]
@govert Thanks - Unfortunately I am working in a 2019 Excel environment... I'll take a look at the blob you linked. Closing this issue now.
