### ISSUE TITLE
Investigate Excel 2016 RTD server startup for persistent RTD server

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#40]
We need to investigate this report: https://social.msdn.microsoft.com/Forums/office/en-US/99c944df-d1ec-42c8-92d4-95b7e78de954/excel-2016-rtd-interface?forum=exceldev

There might be a problem with the RTD Server startup when opening a document with persistent RTD server formulae.

**Comment by zmarwa** [comment]
Hello,

I have the same problem with Excel 2016. Have you found any solution please?

Thks,
zm

**Comment by govert** [comment]
If you are able to reproduce this issue, please report it to Microsoft.

-Govert

**Comment by govert** [comment]
We need to add the "localhost" server name to Excel-DNA to work around this (at least for problem versions).

A fix for the bug is available here: https://support.microsoft.com/en-us/kb/3114374

**Comment by govert** [comment]
A possibly related issue with RTD in Excel 2016 is discussed here: https://social.technet.microsoft.com/Forums/en-US/30538dc2-5e5b-4674-acac-bde07ba8ae00/problem-with-rtd-function-in-excel-2016?forum=excel

(and references here: https://social.technet.microsoft.com/Forums/office/en-US/1195792c-c0d4-4e13-9b2e-ccf3d766dc64/rtd-in-excel-2016?forum=excel)

I don't know whether the change in having a space in the server name position of the formula is significant.
