### ISSUE TITLE
Allow wildcard references in .dna file

### ISSUE THREAD

**Issue by sparticus1701** [Excel-DNA/ExcelDna#402]
The .dna file can get long and cumbersome when trying to pack all the .dlls in:

&lt;DnaLibrary Name="ExcelPlugin" RuntimeVersion="v4.0">
	&lt;ExternalLibrary Path="ExcelPlugin.dll" Pack="true" />
	&lt;Reference Path="A.dll" Pack="true" />
	&lt;Reference Path="B.dll" Pack="true" />
	&lt;Reference Path="C.dll" Pack="true" />
	&lt;Reference Path="D.dll" Pack="true" />
	...
&lt;/DnaLibrary>

I really wish we could use wildcards:

&lt;DnaLibrary Name="ExcelPlugin" RuntimeVersion="v4.0">
	&lt;ExternalLibrary Path="ExcelPlugin.dll" Pack="true" />
	&lt;Reference Path="*.dll" Pack="true" />
&lt;/DnaLibrary>

**Comment by govert** [comment]
Wild cards are supported in .dna files, and there are some other options for adding additional references for SDK-style projects. See https://groups.google.com/g/exceldna/c/xZHE2SouxXw
