### ISSUE TITLE
Disable excel convert string to date while opening csv file

### ISSUE THREAD

**Issue by Edward-Zhou** [Excel-DNA/ExcelDna#410]
I am trying to disable excel to convert normail string like `1-2` to date `1/2/2021`, I know there is no default settings to disable this behavior.

I am wondering whether there is any event to be fired before converting or any automatically way to convert back.

**Comment by rkapl123** [comment]
Well, what if you did the old "format as text" [trick](https://support.microsoft.com/en-us/office/stop-automatically-changing-numbers-to-dates-452bd2db-cc96-47d1-81e4-72cec11c4ed8)
You might also do this before opening the workbook for the user in the area where they are supposed to enter the data. Afterwards the cells can be converted back to standard without automatically changing the data back...

**Comment by govert** [comment]
This question might also get some others answers if posted on StackOverflow. But it a bit more general than the Excel-DNA add-in library can help with.
