### ISSUE TITLE
ExcelDNA.Integration 1.5.1-rc3 - "stomped PECompilation timestamp" warning by VirusTotal

### ISSUE THREAD

**Issue by wh1t3cAt1k** [Excel-DNA/ExcelDna#418]
https://www.virustotal.com/gui/file/2634ee8fb742fd2adf8ec7490203321daa228180a09f36373f66dabc17d8a870

Not sure about the severity of the problem, but it might pose a potential problem with anti-virus software.

**Comment by govert** [comment]
@wh1t3cAt1k 
I see no message like "stomped PECompilation timestamp" anywhere.

Do you mean the Creation Time of the file showing as 2064-12-22?
I have no idea where that comes from - I presume some tooling change in how I build or sign the assembly?
How can I see that date locally? - Windows Explorer does not show that date.

![image](https://user-images.githubusercontent.com/414659/145372335-ec10bd4a-c07a-4406-9e0a-97f499926805.png)


![image](https://user-images.githubusercontent.com/414659/145370984-319cbc58-a801-4e57-8440-58445d335f4a.png)

**Comment by wh1t3cAt1k** [comment]
@govert frankly this is outside of my current area of expertise, I am not sure where to look up that date myself...

Here is what I see by the URL above:

![image](https://user-images.githubusercontent.com/5159662/145380149-c95e2cbc-cd54-45c1-9cc1-9a49dbe88ffb.png)

https://www.virustotal.com/gui/file/2634ee8fb742fd2adf8ec7490203321daa228180a09f36373f66dabc17d8a870

To clarify, I downloaded / unpacked the .nupkg from the latest uploaded NuGet.

**Comment by govert** [comment]
I don't see that warning when I go to VirusTotal, but in any event the nonsense DateTime is 'by design' to support reproducible builds. See https://devblogs.microsoft.com/oldnewthing/20180103-00/?p=97705

**Comment by govert** [comment]
I've filed an issue in the relevant YARA repository: 
https://github.com/ditekshen/detection/issues/2

**Comment by wh1t3cAt1k** [comment]
Thanks for clarifying @govert 🤝
