### ISSUE TITLE
Recompilation Environment?

### ISSUE THREAD

**Issue by bigSteakOnTheGrill** [Excel-DNA/ExcelDna#419]
I like to recompile the package. I downloaded the package from github. I opened with VS Community 2019 the solution file ExcelDna.sln in the folder Source. The rebuild stops with an error message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "xcopy /y D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Host\bin\Debug\x64\ExcelDna.Host.x64.xll D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Test\bin\Debug\net5.0-windows\ExcelDna.Test-AddIn.xll*
xcopy /y D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Host\bin\Debug\x64\ExcelDna.Host.runtimeconfig.json D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Test\bin\Debug\net5.0-windows\
xcopy /y D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Host\bin\Debug\x64\ExcelDna.ManagedHost.* D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Test\bin\Debug\net5.0-windows\
xcopy /y D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Host\bin\Debug\x64\ExcelDna.Loader.* D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Test\bin\Debug\net5.0-windows\
xcopy /y D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Host\bin\Debug\x64\ExcelDna.Integration.* D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Test\bin\Debug\net5.0-windows\" exited with code 4.	ExcelDna.Test	D:\Data\Software\ExcelDnaGitHub\Source\ExcelDna.Test\ExcelDna.Test.csproj	25	

Any idea why?

**Comment by bigSteakOnTheGrill** [comment]
Is there a better environment than VS2019?

**Comment by govert** [comment]
VS2019 should work fine.
The errors you see relate to the (experimental) .NET 5 host. There might be some errors earlier in your build which means the listed files didn't get built.
However, you might still have the ExcelDna.xll and ExcelDna64.xll files, which are the main .NET Framework outputs.

Can you look for earlier errors?

**Comment by govert** [comment]
Some comments about debugging, once you have it building successfully:

•	Debugging is a bit messy. I have some small ExcelDna64.dna files that I copy into the 64-bit Debug directory (next to the Source\ExcelDna\x64\Debug\ExcelDna64.xll file). Then I set the ExcelDna project as the startup, with Debug settings to start Excel with the ExcelDna64.xll file. That’s for the normal (.NET Framework) ExcelDna. I also set the Debugger Type:
 
![image](https://user-images.githubusercontent.com/414659/147394773-cc6cbe23-56cf-4b2c-8f2d-cf1aeb70f264.png)


•	The ExcelDna64.dna might be simple, or have some bits with a feature I want to check:
```
<?xml version="1.0" encoding="utf-8"?>
<DnaLibrary Name="Test Add-In" RuntimeVersion="v4.0" xmlns=http://schemas.excel-dna.net/addin/2020/07/dnalibrary>
  <Project Language="C#" >
    <![CDATA[
       public class Functions
       {
          public static string SayHello()
          {
              return "Hello from Excel-DNA";
          }
       }
    ]]>
  </Project>
</DnaLibrary>
```

•	Sometimes I just use it as an external library that I copy into the same x64\Debug:
```
<?xml version="1.0" encoding="utf-8"?>
<DnaLibrary Name="AVCrash Add-In" RuntimeVersion="v4.0" xmlns=http://schemas.excel-dna.net/addin/2020/07/dnalibrary>
  <ExternalLibrary Path="AVCrash.dll" ExplicitExports="false" LoadFromBytes="true" Pack="true" IncludePdb="false" />
</DnaLibrary>
```
These bits are not in the repository.

•	So this lets me debug the native ExcelDna code (.NET Framework) and the managed code projects (ManagedHost / Loader / Integration) under .NET Framework.

**Comment by govert** [comment]
Closing this issue - feel free to reopen if you still run into problems.
