### ISSUE TITLE
ExcelDna.AddIn 1.5.1 missing in Nuget

### ISSUE THREAD

**Issue by vkirienko** [Excel-DNA/ExcelDna#420]
Hi, 

It seems like ExcelDna.Integration and ExcelDna.Interop were updated to 1.5.1 version in Nuget but ExcelDna.AddIn 1.5.1 is missing there.

Regards,
Vlad

**Comment by govert** [comment]
Hi Vlad - I pushed the NuGet package for ExcelDna.Addin v 1.5.1 at the same time as the rest, but NuGet is still 'Validating' the package. I presume the anti-virus issues are related. The binaries are identical to the 1.5.1-rc3 package.

My admin view on NuGet:

![image](https://user-images.githubusercontent.com/414659/147480758-a707e2ad-a610-422d-925e-75f20e2503f0.png)

**Comment by vkirienko** [comment]
Thank you. I will check later, hopefully will be listed.

**Comment by govert** [comment]
It looks like it's published now.
I am planning on making another update in the next few days which might be a bit better on the anti-virus issues.
