### ISSUE TITLE
ExcelDna.AddIn.1.5.1\tools folder does not have ExcelDna.xll

### ISSUE THREAD

**Issue by jimfoye** [Excel-DNA/ExcelDna#425]
![image](https://user-images.githubusercontent.com/4249676/150820437-1e529935-8681-4886-8cee-2f9f771e2a26.png)

It should be there, right?

**Comment by govert** [comment]
Indeed that file is in the .nupkg, but your anti-virus probably ate it. I see it seems to be back on Microsoft Defender's black list.
You might want to try the prerelease version 1.6.0-preview1. I still need to write a post, but that could help a bit with the anti-virus false positives.

**Comment by jimfoye** [comment]
Wow, I would not have guessed that was the problem in a hundred years. Already Microsoft makes it so hard for developers to write add-ins for Excel; now they silently prevent nuget packages from completely installing? That is just mind-blowing.

**Comment by jimfoye** [comment]
Check it out!

![image](https://user-images.githubusercontent.com/4249676/150874668-a8fe15ae-c73c-4b2f-88bf-50d8eaba8dbe.png)

I did a restore and now I'm all good.

Every day is stranger than the previous one in the Microsoft developer ecosystem. :confounded:

**Comment by jimfoye** [comment]
Looks like I should have said "Windows Security Essentials" and not "Windows Defender". It's not confusing at all to have two anti-virus programs from the same manufacturer, is it?

**Comment by govert** [comment]
Hi @jimfoye - I wonder if you could check the version 1.6.0-preview1 version with the 'Microsoft Security Essentials'. I only have Defender.

**Comment by jimfoye** [comment]
I created a new project and installed 1.6.0-preview1 without problems.

**Comment by govert** [comment]
Thank you for the check @jimfoye
