### ISSUE TITLE
How Can I Keep RTD Cell Values When ReOpen Excel

### ISSUE THREAD

**Issue by zzzqgrelax** [Excel-DNA/ExcelDna#432]
Many cells have been inserted with Rtd Like AAA("PARA1","PARA2")
When cell value is not empty and  i will not update topicValue any more

My question is that when i reopen my excel  all the topics will refrsh again.  May i keep the old value and do not fresh 

I Have found that the ref property  ref bool newValues  if false then return the old Value . but i found that when Reopen my excel  it will immediately call  DisconnectData  and then call ConnectData  and then newValues changed to true

Can you offer me some help,Thanks a lot
![图片](https://user-images.githubusercontent.com/38203775/154414078-2aa2d512-6400-46a4-98eb-6b968606d155.png)

**Comment by govert** [comment]
It sounds strange to me that you get DisconnectData called on your RTD server when Excel opens, before ConnectData is called. Is this correct?

I expect that `newValues` will be false in your `ConnectData` is called, if Excel has cached values.

I think you have to give your RTD server both ProgId and Guid attributes to be sure that it is registered as the same server every time the add-in is loaded.

**Comment by zzzqgrelax** [comment]
Thanks for your reply 
I have get my rtd server both progid and guid  but it seems doesn't work 
I want to get excel cached Value when open excel and do not need to fetch values for a lot of cells 
Have you tested this case or help providing me a success sample
Thanks a lot

**Comment by govert** [comment]
I have not had a chance to make an example for this, but I did remember one thing.
From an old message on the Google group.

> 
> Excel's RTD mechanism stores the last update for each active topic in the workbook. So when the workbook is opened again, Excel attempts to create the RTD server again, and initializes the active topics. In the ConnectData call, the RTD server can then decide whether to make a new value available, or to let Excel use the old value that was stored as the topic's value, until the next update.
> 
> You can find a detailed write-up of the meaning of the newValues parameter of ConnectData here: http://weblogs.asp.net/kennykerr/Rtd9 
> 
> Excel-DNA's ExcelRtdServer base class has a compatible implementation of ConnectData, with the newValues passed through directly. So an implementation of ExcelRtdServer can leave the newValues at false which lets Excel use previously cached values.
> 
> One complication is the following.
> Excel-DNA supports on-demand registration of the ExcelRtdServer RTD entries in the registry, allowing add-ins to run without requiring any COM registration. This mechanism registers the ExcelRtdServer again a ProgID that is generated from a new Guid. Hence every run of the add-in will have a 'new' RTD server, from Excel's perspective. Thus for on-demand registered RTD servers, the cached value will never be used, as Excel won't use these when the original (cached) RTD fails to load.
> 
> Thus to support cached values, an RTD server must be persistently registered, and use a fixed ProgID.
> The Excel-DNA helper function 'XlCall.RTD' triggers the on-demand mechanism. So the following are required to make a persistent RTD server:
> 
> * Make sure that the ExcelRtdServer-derived class has both a unique [Guid(...)] and a unique [ProgId(...)] attribute, and is marked as [ComVisible].
> 
> * Register the .xll in one of these ways:
>   - Run "Regsvr32 MyAddIn.xll" from a command-line
>   - Call ExcelDna.ComInterop.ComServer.DllRegisterServer() from the add-in's AutoOpen() method.
> 
> * Change any calls from XlCall.RTD to XlCall.Excel(XlCall.xlfRtd... ). The call to xlfRtd is exactly equivalent to calling =RTD(...) from the worksheet, or Application.Rtd(...) from VBA. This skips the on-demand registration.
> 
> It has been a while since I experimented with the cached RTD values, so I might be leaving something out.
> Let me know if you try it, or if I need to add any more details.

**Comment by zzzqgrelax** [comment]
okk   thanks a lot
You've helped me a lot 
sorry to ask another question   
Is there a way to get topic objects or topicids  on activesheet  
I have tried get sheetName by udf and stored in my dto  but user may change it 
I want to update the topic of the current sheet
Is there an elegant and quick way to do that?

**Comment by zzzqgrelax** [comment]
okk  it's greate!
I solved my problem with your help
Thank you very much
