### ISSUE TITLE
Runnig a big blocking query to async non-blocking

### ISSUE THREAD

**Issue by navidanari** [Excel-DNA/ExcelDna#435]
Hi Govert and others, 

I am trying to fetch a big bulk of data that takes sometime and naturally don't want to delay the user till my function is back.

If I had a free hand I would define my function as async and would call it in non-blocking mode. 

But If I follow this Excel Dna complains about the signature of my excel function. Sounds there is no workaround to get this wotk with async pattern.

So the question is: Home I can run a function that could take 30 secs to execute and at the same time let the GUI go and interact with user?

Thanks in advance!

**Comment by govert** [comment]
There is quite a bit of help in Excel-DNA for making async functions.
The implementation which uses RTD behinds the scenes looks like this:

```
using ExcelDna.Integration;
using System.Threading;

namespace AsyncHelloWorld
{
    public class HelloWorld
    {
        [ExcelDna.Integration.ExcelFunction(Description = "Async Hello World")]
        public static object SayHelloAsync(string name)
        {
            return ExcelAsyncUtil.Run("RunSomethingDelay", new [] { name }, () => RunSomethingDelay(name));
        }

        public static string RunSomethingDelay(string name)
        {
            Thread.Sleep(2000);
            return $"Hello {name}";
        }
    }
}
```

To automatically rewrite functions that return `Task<T>` to use this pattern, there are helpers in the Registration Extensions project https://github.com/Excel-DNA/Registration

There is also the world of native Excel async functions, which are also fully supported by Excel-DNA and have some trade-offs from the RTD-based approach.

**Comment by navidanari** [comment]
Thanks Govert, I have extensively used RTDs here and now how it works, but what if I need to return a objet[,]? how I can simulate that with current setup? is there any possibility to return 2D obj? (it is gonna be really big, cannot request each object seperately and put them together on the sheet!)

Br

**Comment by govert** [comment]
If your version of Excel supports Dynamic Arrays, you can return `object[,]` directly.
If you are on old Excel, you have two approaches that can work:
* Use the AsyncBatch approach (https://github.com/Excel-DNA/Samples/blob/master/Misc/AsyncBatchSample.cs) to make individual async calls per cell, but batch the back-end into a single call
* Use a single cell indicator which is the async function, and then an unpacking function which returns an array without async, and uses the 'ArrayResizer' hack (https://groups.google.com/g/exceldna/c/WK6RfD5cym0/m/KaoZR6KPAwAJ)
