### ISSUE TITLE
When will xlGetFmlaInfo return valid info?

### ISSUE THREAD

**Issue by oldoldman** [Excel-DNA/ExcelDna#439]
Hello,
I'm trying to get the current calling formula name in a UDF, but it always return with ```FmlaInfo.wPointMode==0``` which means the rest fields is not valid. How does this happen? Mank thanks!!!

**Comment by keithalewis** [comment]
For more GET.XXX info see: https://xlladdins.github.io/Excel4Macros/get.formula.html

**Comment by oldoldman** [comment]
> For more GET.XXX info see: https://xlladdins.github.io/Excel4Macros/get.formula.html

It seems all formula that can't input in the excel formula bar is in fact has its origin of excel macro, for example , ```xlfGoto```. Is this true ? And your link is an excellent reference!
