### ISSUE TITLE
Is there a way to return an array in RTD server?

### ISSUE THREAD

**Issue by VijayJia** [Excel-DNA/ExcelDna#446]
I want return an array in RTD function. However, it returns an error.

**Comment by govert** [comment]
An RTD server topic cannot return an array, only a simple value.

What your options are next depends on whether your version of Excel supports Dynamic Arrays.

* If your Excel supports Dynamic Arrays, then you can some plumbing where you expose a wrapper UDF which returns an array, and internally uses an RTD server that exposes a key into some internal dictionary. E.g. the RTD server returns a GUID which is a key into a dictionary with the array result, and the wrapper UDF functions gets the GUID from a call the the Excel RTD function, looks up the result internally and returns the array from there. Dynamic Arrays and the fixes in new Excel then handle the result array correctly. This is exactly how the `ExcelAsyncUtil.Observe` feature in Excel-DNA is implemented, allowing you to set up a function that returns an `IObservable` stream. For Dynamic Arrays, the stream of values can safely include `object[,]` arrays.

* If your Excel does not support Dynamic Array, e.g. Excel 2019 or older. Then your own RTD wrapper or your `ExcelAsyncUtil.Observe` / `IObservable` functions cannot safely return arrays to a cell. There is a memory leak and a calling pattern from Excel with makes workarounds very hard. So the best plan here is to split into two functions that _must_ go into different cells: One function will be the RTD wrapper function that returns a simple value key or some sort. The second function will not call RTD internally, and will only take the simple key and look up from internal data the result (possibly an array) and return this. Optionally , the second function can implement the `ArrayResizer` hack to resize the result array. The two function cannot be called nested from a single cell.

**Comment by VijayJia** [comment]
Thanks for your advice. I resolve the issue with follow way:
1. In RTD server, serializes the result to string, and then return the serialized string.
2. In RTD wrapper function format the serialized string to array.

Thanks again.

**Comment by govert** [comment]
Note that under non-Dynamic Array versions of Excel the RTD topic will not always disconnect correctly if called from an array formula. If you split the calls into two cells, it is fine - one cell gets the serialized string value, and an array formula in different cells parse the string and return an array.
