### ISSUE TITLE
Setting Formula2 property in code

### ISSUE THREAD

**Issue by markns** [Excel-DNA/ExcelDna#451]
Hi,
Is there a way to set the `Formula2` property of a cell in code? The 2010 interop libraries don't appear to have this property, so compilation fails.
Thanks!

**Comment by govert** [comment]
You can use the C# 'dynamic' type to make a late-bound COM call for this:

```c#
               var xlApp = (Microsoft.Office.Interop.Excel.Application)ExcelDnaUtil.Application;
                dynamic range = xlApp.Range["A1"];
                range.Formula2 = formula;
```

**Comment by markns** [comment]
Works perfectly, thanks Govert!

**Comment by MichelLaplane** [comment]
using the Microsoft.Office.Interop.Excel.15.0.4795.1001, the Formula2 is not available.
string strValue = range.Formula2; must be transformed to string strValue = range.Formula;
returning to the old time which is very bad.
