### ISSUE TITLE
Strange change of Application context in keyboard shortcut procedure

### ISSUE THREAD

**Issue by rkapl123** [Excel-DNA/ExcelDna#459]
Dear Govert! 

In a procedure being invoked with a keyboard shortcut, the code before the last statement before `Exit Sub` changes application context, which shows up when doing a MsgBox there:

```VB
   <ExcelCommand(Name:="refreshData", ShortCut:="^R")>
    Public Sub refreshData()
        If ExcelDnaUtil.Application.Calculation = Excel.XlCalculation.xlCalculationManual Then
            UserMsg("Calculation is set to manual, this prevents DB Functions from being recalculated. Please set calculation to automatic and retry", "DB-Addin Refresh")
            MsgBox("hello2")
            Exit Sub
        End If
...
```
![image](https://user-images.githubusercontent.com/7430763/167265048-8350c9e1-b4a8-41a7-80b0-27a4e195ffd2.png)

This also crashes `theMethod.ReflectedType.FullName` invocation (which gives the Module/Class name of the called method). Using a try catch helps although:

```VB
    Public Sub LogInfo(LogMessage As String)
        If DebugAddin Then
            Dim caller As String
            Dim theMethod As Object = (New System.Diagnostics.StackTrace).GetFrame(1).GetMethod
            Try : caller = theMethod.ReflectedType.FullName + "." + theMethod.Name : Catch ex As Exception : caller = theMethod.Name : End Try
            WriteToLog(LogMessage, TraceEventType.Information, caller)
        End If
    End Sub
...
```
If this procedure is invoked differently (e.g. from the Ribbon Menu or a context menu), then everything works fine, so I suspect it has something to do with the keyboard shortcut invocation method.

What still remains is the strange context change that is causing this problem.

-regards,
Roland

**Comment by govert** [comment]
Hi @rkapl123 - I've tried your code snippets but can't see anything strange on my side.

![image](https://user-images.githubusercontent.com/414659/167310505-71a6c64a-812e-43e4-9471-90da6a4427f1.png)

![image](https://user-images.githubusercontent.com/414659/167310520-0433b926-91e0-427a-b8ea-766173f7bba2.png)

**Comment by rkapl123** [comment]
Hi Govert!

Thanks for trying the code, however I'm pretty sure now, that the reason actually lies in the ExcelCommand Tag/invocation using the shortcut (`<ExcelCommand(Name:="refreshData", ShortCut:="^R")>`), after a lot of testing I found that the calculation attribute was not the cause (sorry that the attribute got lost somehow by my edits):

```VB
   <ExcelCommand(Name:="refreshData", ShortCut:="^R")>
    Public Sub refreshData()

        If True Then
            UserMsg("Calculation is set to manual, this prevents DB Functions from being recalculated. Please set calculation to automatic and retry", "DB-Addin Refresh")
            MsgBox("hello2")
            Exit Sub
        End If
```

**Comment by govert** [comment]
OK for Release build, the method is being inlined by the JIT compiler. So the method you see as the caller is the one generated at runtime by Excel-DNA. You can prevent inlining with an attribute:

![image](https://user-images.githubusercontent.com/414659/167314273-fe800963-793d-4f6b-9e22-e9fed21146b7.png)

**Comment by rkapl123** [comment]
Oh dear, thanks a lot for the explanation! I thought this was some black magic...

-regards,
Roland
