### ISSUE TITLE
xlfRegister call failed for function or command

### ISSUE THREAD

**Issue by nielsbosma** [Excel-DNA/ExcelDna#50]
I have a user reporting that he's getting this error:

     Registration [Error] xlfRegister call failed for function or command: 'W3CValidate'

in the ExcelDna log-window. What could be wrong?

http://community.seotoolsforexcel.com/t/seo-tools-error-when-opening-new-sheets/30

**Comment by govert** [comment]
@nielsbosma 
Is this still a problem?
Do you have any more details on this / can you post the signature of the function in question?

**Comment by nielsbosma** [comment]
No you can drop it. I haven't received this complaint again.
