### ISSUE TITLE
LogDisplayTraceListener can't be used in the top trace listener

### ISSUE THREAD

**Issue by dreamershl** [Excel-DNA/ExcelDna#51]
With the below config, app will get the NULL exception because of the Debug.print() output in initialization. 
All the Debug methods won't check the TraceFilter. So there is no way to directly use the "LogDisplay" for error message popup. 

The NULL exception is caused by the "LogDisplay.RecordLine(message);" That function doesn't check whether the "LogStrings" is null. 

If add the following check, LogDisplay can be used directly. 
      
    if (LogStrings == null)
                return;
    

App.config

    <sharedListeners>
      <add name="LogDisplay" type="ExcelDna.Logging.LogDisplayTraceListener,ExcelDna.Integration"/>
    </sharedListeners>

    <trace autoflush="false" indentsize="4">
      <listeners>
        <remove name="Default"/>
        <add name="LogDisplay"/>
      </listeners>
    </trace>

**Comment by govert** [comment]
Could you perhaps make a Pull Request to fix this?

**Comment by dreamershl** [comment]
OK. my honor ;)

**Comment by dreamershl** [comment]
I just create a pull request "initialize the LogStrings #52". Pls check. The solution is changed a little bit. instead of check the null in the function, I directly create the List instance since it is static. Thanks.
