### ISSUE TITLE
Using .deps.json file(s) at runtime

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#516]
When compiling a class library targeting .NET 6, the platform and runtime specific libraries may be copied to additional subdirectories under the output. This happens for example with SQLClient, EF Core, and System.Management references. Information about the location of these dependencies can be found in the <MyLibrary>.deps.json file that is created during compilation. 

Excel-DNA will read and use a .deps.json file at runtime if it has the same name as the add-in, i.e if <MyLibrary>-AddIn64.xll has a matching <MyLibrary>-AddIn64.deps.json. But this file is not created by default.

We should consider:
* Add a build step to copy the <MyLibrary>.deps.json to <MyLibrary>-AddIn64.xll and <MyLibrary>-AddIn.xll automatically.
* When making a packed add-in, or publishing a completely unpacked add-in, we have to decide whether we can use the .deps.json file to resolve the dependencies in a better way - this might be tricky since the parsing, interpretation etc. is in native runtime code. Also the required libraries might be bitness-specific.
* We might also consider recreating the `$(OutDir)\runtime` directories under the puublish folder?

**Comment by govert** [comment]
Alternatively, consider whether we can check for a .deps.json file matching each `ExternalLibrary` and set up a chain of reference resolvers to check each. That will skip the copy requirement and support multiple `ExternalLibrary` entries with their dependencies.  Resolution might still go wrong for competing versions of an assembly in that case.

**Comment by govert** [comment]
Maybe we should do the following:
* Under .NET 6, when there is no .dna file, we should default to LoadFromBytes=false in the generated .dna file.
* When loading an ExternalLibrary, if there is a matching .deps.json file, we should add it to a chain of resolvers we manage in the `ExcelDna.ManagedHost.ExcelDnaAssemblyLoadContext`. This is in addition to supporting the <MyAddIn>.deps.json file (which I presume is nearly never present currently) that we would currently use. The `ExcelDnaAssemblyLoadContenxt` `Load` and `LoadUnmanagedDll` calls would then check through the chain of resolvers, using the first result found.

This should allow the following to work OK. If an ExernalLibrary has dependencies (managed or native) which have a location other than the output directory, the details are found in the ExternalLibrary deps.json file. We should then use these for the resolution. I think the three examples are:
* Add a package reference to System.Management - i.e. this sample should work without the extra file copy https://github.com/govert/TestNet6Deps
* Add a package reference to Microsoft.Data.SqlClient adn a function like this:
```
         public static string SayHello(string name)
        {
            try
            {
                var sqlClient = new SqlConnection();
            }
            catch (Exception ex)
            {
                return $"ERROR: {ex}";
            }
            return "Hello " + name;
        }
```

* It should also work if we have two ExternalLibrary entries, and each has a .deps.json with dependencies.

This makes the process of building and debugging the add-in easier, but does not help with the resolution of dependencies when packing. For packing there are some additional problems:
* Do we use a .deps.json file or do our own resolution from packed files
* What do we do with native files - do we support packing, how do we manage the bitness in the publish directory.
* Can we maybe do build-time resolution for the packing and then configure the packed add-in accordingly?

**Comment by govert** [comment]
I presume a future enhancement might be to examine the .deps.json file, and use that to decide what should be packed. The built-in `AssemblyDependencyResolver` parses the deps.json and gives a list of assemblies and thier resolved paths. For native libraries this might be tricky since the `AssemblyDependencyResolver` need context like the 32/64-bitness to resolve the cuorrent native library - so we might have to figure out how to set this context for this plan.

**Comment by Sergey-Vlasov** [comment]
Can you give an example how multiple .deps.json files (for multiple ExternalLibraries) may originate?

Normally, for an add-in project even with references to other projects, a single combined .deps.json is produced by Visual Studio.

**Comment by govert** [comment]
For multiple ExternalLibraries one needs a .dna file. But I see that an add-in with multiple ExternalLibraries probably don't need multiple .deps.json files.

I explored a bit, and made a repository here: https://github.com/govert/MultiLibs/tree/master

I originally thought one could make the AddIn project so that it does not have a reference to the Lib1 and Lib2 projects, and explicitly have the paths in the .dna file. You can see my different attempts here

```xml
<DnaLibrary Name="MultiLib Add-in" >
	<ExternalLibrary Path="AddIn.dll" />
	<!--<ExternalLibrary Path="C:\Temp\MultiLibs\Lib1\bin\Debug\net6.0-windows\Lib1.dll" />
	<ExternalLibrary Path="C:\Temp\MultiLibs\Lib2\bin\Debug\net6.0-windows\Lib2.dll" />-->
	<!--<ExternalLibrary Path="..\..\..\..\Lib1\bin\Debug\net6.0-windows\Lib1.dll" />
	<ExternalLibrary Path="..\..\..\..\Lib2\bin\Debug\net6.0-windows\Lib2.dll" />-->
	<ExternalLibrary Path="Lib1.dll" />
	<ExternalLibrary Path="Lib2.dll" />
</DnaLibrary>
```

While trying this, I had the `EnableDynamicLoading` option true for the libs, so that they have the runtime dependencies copied to the output. But even then, the right files need to be copied to the add-in directory, else they're not found.

In the end, I added project references to the Lib1 and Lib2 projects from the main AddIn project. This means I don't need the `EnableDynamicLoading` in the libraries, both the Lib1/2.dll and their dependencies are copied and also that the AddIn.deps.json contains all the dependencies. I think this is the intended plan, and how the deps.json files get merges at build time.

Then when I copy this deps.json to the .xll names everything works right:
```xml
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy $(OutDir)\AddIn.deps.json $(OutDir)\MultiLib.deps.json" />
		<Exec Command="copy $(OutDir)\AddIn.deps.json $(OutDir)\MultiLib64.deps.json" />
	</Target>
```

So now I think we don't need to support multiple .deps.json files. 
We just have to decide how to use the one that is there. There is still an artificial case where maybe there are multiple .deps.json files present for different ExternalLibrary .dlls because they are copied in explicitly, but let's not support that.

But I would like to get rid of the copy step in the project file. Either 
1. we do the copy as part of the build, and end up with deps.json files for each .xll (then the current resolver code works fine), or 
2. we change the resolver to use the first .deps.json file from an ExternalLibrary (I prefer this, but the implementation is a bit more difficult). Then we stop using the MyProject-AddIn.deps.json file. If there are multiple ExternalLibraries with deps.json files present, the first deps.json file wins.

Can you poke around a bit at the MultiLibs project - I'm still not sure what the best approach is, but want to keep the project file and output directory contents as unsurprising as possible,

**Comment by Sergey-Vlasov** [comment]
I prefer to have deps.json files for each .xll. This is how .NET expects it to be named.

Our main add-in project always has .deps.json and it is first ExternalLibrary, so it will always win anyway.

**Comment by govert** [comment]
OK, so we just add a copy step to the ExcelDna.AddIn build task, which copies the deps.json from the first ExternalLibrary for each .xll file.

**Comment by govert** [comment]
I guess the next question is whether there is some way to use this deps.json file to control the packing list, including packing the right native libraries.
