### ISSUE TITLE
Revisit RTD ThreadSafe functions and performance helper

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#517]
Recent Excel versions support threadsafe RTD wrappers. We would like to support these in our Observables etc., including in the ad-hoc RTD server registration code. We should also check and document the `ExcelIntegration.RegisterRtdWrapper` performance helper.

**Comment by govert** [comment]
https://docs.microsoft.com/en-us/office/vba/excel/concepts/excel-performance/excel-performance-and-limit-improvements

“In Excel M365 version 2002 monthly channel or later, Excel's RealTimeData (RTD) function is much faster than Excel 2010 calculating data in the spreadsheet. We removed bottlenecks in its underlying memory and data structures as well as made it thread-safe to allow it to be calculated on all available threads of Multithreaded recalculation (MTR).”

**Comment by cirrusone** [comment]
Will threadsafe RTD wrappers solve the issue where RTD server misses/blocks updates when a sheet is scrolled or clicked? It would be good if RTD had same behavior as COM where updates are only stopped when cell enters edit mode.

**Comment by govert** [comment]
@cirrusone I'm afraid not - the update behaviour you see is how Excel works with the RTD server and I don't think we have any control over that.
