### ISSUE TITLE
Missing Dlls in Packed xll

### ISSUE THREAD

**Issue by 9swampy** [Excel-DNA/ExcelDna#518]
### Question:
> If I build local in VS both Debug and Release; everything's fine; all DLLs specified are located and packed. Addin works in Excel fine.
> 
> I commited and pushed to our CI build and the packed Dll was coming back about 30% smaller. I used ExcelDnaUnpack to determine it's all the internally built Dlls that are missing. All the external Dlls (some nuget references, some core framework) do get packed as specified. I'm upgrading the packge first time in a long time and it was missing one nuget referenced dll - adding it to the Dna added it to the output correctly, as expected).
> 
> If I build from the same MsBuild command line that gets used in CI according to the build output I can see all the Dlls get built and are present in the expected location, alongside the xll and dna. I've added an extra copy to the CI build to capture the state of the files in the xll/dna folder and they're all present, the dna definitition is up-to-date but the ExcelDnaPack takes a long time to execute (over a minute minutes vs the 2s when running local in VS - I guess because it's failing to find the DLLs specified - but why; they're definitely colocated correctly). Everything looks the same as the output I get when I build local; but the CI build Xll-packed is missing a load  of Dlls.
> 
> What we had before this long overdue upgrade was a scriptthe automated ExcelDnaPack; but I've replaced all that with ExcelDna.Addin and everything works great local; it's the CI build that's causing issues. I've not added in the ExcelDnaPack nuget because it's a version behind; and AddIn seems to be doing everything  including the pack. Is this assumption correct?
> Any suggestions where I should go looking next?
> I can see from posts over the years I share the frustration that there's precious little logging to explain when the pack process starts going wrong/skipping files. I'm tempted to go under the hood to add logging; even a pointer within the code to start with would be helpful.

### Govert
> You are right that the packing is now run as a build task inside the ExcelDna.AddIn package, and no longer an executable that is run as a post-build step.
> 
> The “ExcelDnaPack” NuGet package is a community-contributed package that provides the ExcelDnaPack.exe for backward compatibility, I think for use in other build systems like Cake. For normal builds you probably don’t need this.
> 
>  
> 
> You should check the following:
> 
> * What are the .dna files in the project root directory, if any?
> 
> * What are the .dna files that end up in the output directory? Make sure to clean the output directory before you build, so that old ones don’t confuse things.
> 
> * What is the console output when building? The ExcelDnaPack task writes a bit of logging the console (yes – we should change that to normal build logging).
> 
>  
> 
> I can think of the following going wrong:
> 
> * Maybe the .dna file that ends up in the output directory is different – e.g. the one on your machine that is in the project root might not be checked into source control, so the CI build doesn’t see one, and the build task creates a template .dna file to use, which won’t have your extra libraries in.
> 
> * Maybe the build sequence is different, and the extra .dll files are only getting to the output directory after the packing runs. In this case I expect the packing to fail and the build to fail, but it might be another aspect we’ve not really converted to a build task completely.
> 
>  
> 
> If you’re still stuck, you might want to post some of the details from above – what the .dna files are and what they contain, and what the console output is in the two cases.
> 

Re Govert "**yes – we should change that to normal build logging**"
I've committed to a fork here a proposal for a PR to do just that. See [here](https://github.com/Excel-DNA/ExcelDna/compare/master...9swampy:ExcelDna:Excel-DNA/PackLogging).

_Inject IBuildLogger to ExcelDnaPack.Pack and use it to log to the standard Build output instead of the console. ConsoleLogger added an implementation of the same for PackProgram._
_Decoupled IBuildLogger from implementation and pull down to PackedResources so it can be reused, but kept the implementation unmoved from Addin.Tasks.Logging._

However, I've not tested it at all; couldn't see how you've set up the nuget packaging. If I pack ExcelDna.AddIn.Tasks I get a nuget package but doesn't on first impression generate a substitute for ExcelDna.AddIn published. Is the name just misleading; should I be able to drop ExcelDna.Addin and replace with the ExcelDna.AddIn.Tasks.nupkg generated? 

Could you take a look at the commit and let me know if it looks close to your requirements/expectations and either
1. consider merging and building an alpha I could test (or let me know what standards/changes you'd have preferred)
2. point me to packaging documentation or
3. advise how I should go about building a substitute for ExcelDna.AddIn?

Cheers for all the work you've done on ExcelDna. I haven't used ExcelDna before but I've just inherited a long overdue upgrade at work and as noted above am having some issues with the xll missing some dlls.

To answer your latter questions above:
1. dna in root I verified is correct, up to date. I had to add a missing Nuget reference dll and it subsequently appeared in the xll
2. build is already doing a clean
3. Console output is essentially identical when it works (local in VS) and when it doesn't (local CLI msbuild and on CI); hence the PR. 

Atm I'm using a Nuget, not a build of the repo... is there anything I need to switch on to get more "console" output? Likely I'll try a build of the repo tomorrow... it's late enough now...

**Comment by govert** [comment]
You build logging changes look great - thank you!
Please make a pull request - you might have to navigate the CLA bot too.
I'll then make a new alpha version from there.

The packages are built by the "MasterBuild.cmd" script in the MasterBuild directory. Change the version info in the cmd file and run, then the packages are output to the Package\nupkg directory. You can then add this directory as a NuGet Package Source.

To better understand what is happening with the packing, we are looking for this part of the console output that looks like like this:
```
Using base add-in bin\Debug\net452\ExcelDna.IntelliSense32.xll
  ->  Updating resource: Type: CONFIG, Name: __MAIN__, Length: 907
  ~~> ExternalLibrary path ExcelDna.IntelliSense.Host.dll resolved to bin\Debug\net452\ExcelDna.IntelliSense.Host.dll.
  ~~> Assembly path ExcelDna.IntelliSense.dll resolved to bin\Debug\net452\ExcelDna.IntelliSense.dll.
  ->  Updating resource: Type: ASSEMBLY_LZMA, Name: EXCELDNA.INTELLISENSE.HOST, Length: 4069
  ->  Updating resource: Type: DNA, Name: __MAIN__, Length: 653
  ->  Updating resource: Type: ASSEMBLY_LZMA, Name: EXCELDNA.INTELLISENSE, Length: 60510
Completed Packing bin\Debug\net452\publish\ExcelDna.IntelliSense32-packed.xll.
  ExcelDnaPack: bin\Debug\net452\ExcelDna.IntelliSense32.xll.config -> bin\Debug\net452\publish\ExcelDna.IntelliSense32-packed.xll.config
  ExcelDnaPack: bin\Debug\net452\ExcelDna.IntelliSense64.dna -> bin\Debug\net452\publish\ExcelDna.IntelliSense64-packed.xll
```

**Comment by govert** [comment]
Thank you for the logging PRs @9swampy - thse is now incorporated in version 1.6.1-alpha4 which I've published to NuGet.

The output in the build logging now looks like this:
```
1>        Target ExcelDnaPack:
1>            ExcelDnaPack: bin\Debug\net452\Test161a4-AddIn64.dna -> bin\Debug\net452\publish\Test161a4-AddIn64-packed.xll
1>            PackExcelAddIn: Running PackExcelAddIn Task
1>            PackExcelAddIn: Using base add-in bin\Debug\net452\Test161a4-AddIn64.xll
1>            PackExcelAddIn:   ~~> ExternalLibrary path Test161a4.dll resolved to bin\Debug\net452\Test161a4.dll.
1>            PackExcelAddIn:   ->  Updating resource: Type: ASSEMBLY, Name: TEST161A4, Length: 3584
1>            PackExcelAddIn:   ->  Updating resource: Type: DNA, Name: __MAIN__, Length: 532
1>            PackExcelAddIn: Completed Packing bin\Debug\net452\publish\Test161a4-AddIn64-packed.xll.
```

What we are looking for in your local vs. CI server are those `~~> ...`  and `-> Updating resource`  entries. These indicate which libraries we tried to pack. You should check whether these differ in the two cases.

**Comment by 9swampy** [comment]
[ExcelDna.AddIn](https://www.nuget.org/packages/ExcelDna.AddIn/#versions-body-tab) doesn't seem to have loaded to nuget while [Excel-Dna](https://www.nuget.org/packages/Excel-Dna) and [ExcelDna.Integration](https://www.nuget.org/packages/ExcelDna.Integration/1.6.1-alpha4) have...
