### ISSUE TITLE
GetImage resolution

### ISSUE THREAD

**Issue by wh1t3cAt1k** [Excel-DNA/ExcelDna#523]
Hi @govert ,

We are revamping our ribbon based on custom PNGs instead of the imageMso set.
The resources are embedded through the `Resources` mechanism and the `GetImage` callback.

My question is this: for "large" buttons, are we stuck with using 32x32 icons only?
When I return an 80x80 bitmap, it gets downscaled and doesn't look crisp on my (low-res) monitor.

At the same time, I am wondering if just hard-coding 32x32 resources would not look nice on high-DPI screens such as Retina.

What are my options here? Detecting the screen resolution in `GetImage` in C# somehow?
Just wondering if this is a task that you addressed before.

**Comment by govert** [comment]
I can't find anything in the Office ribbon references about the image size. Other Google results seem to indicate that the sizes are indeed only 32x32 and 16x16.

**Comment by govert** [comment]
I see the Office JS add-ins support nicer images: https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/add-in-icons-monoline.md. I have not seen any indications that this works for normal ribbon extensions.

**Comment by wh1t3cAt1k** [comment]
Thanks for your help @govert , in this case I will simply use the 32 / 16 sizes for our DNA product.

**Comment by wh1t3cAt1k** [comment]
FYI @govert and for the benefit of the community, the 32x32 icons looked ugly on Retina screens.

I used 64x64 bitmaps for custom GetImage and it looked great on both FHD (96 dpi) and Retina (192 dpi) displays.

**Comment by wh1t3cAt1k** [comment]
Comparison on Retina:

![image](https://user-images.githubusercontent.com/5159662/201224177-fc905e6f-82a6-469a-a693-08739cb2842c.png)

Left - 32px, right - 64px

**Comment by garethhayter** [comment]
Can .ico files be used? Don't they contain multiple size images? They might use the correct size at runtime?

**Comment by wh1t3cAt1k** [comment]
AFAIU only bitmaps are supported: https://stackoverflow.com/questions/27526094/use-ico-image-in-ribbon

**Comment by govert** [comment]
@wh1t3cAt1k Great to know - thank you for posting back. I'll have to stop believing everything I see on the Internet.
