### ISSUE TITLE
Re-enable ExcelDnaPack compression, and add option to disable

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#527]
I think we should enable the compression again, but with a "DisableCompression" option in the project file.

**Comment by Sergey-Vlasov** [comment]
If I just re-enable ExcelDnaPack compression, ExcelDna.Loader.dll and ExcelDna.Integration.dll will be always compressed in .xll irrespective of project file settings. Is it OK?

**Comment by govert** [comment]
I would prefer if we could go further and make the result add-in have only uncompressed assemblies if the packing compression is disabled. So the ExcelDnaPack task might unpack and decompress these assemblies, then save again as packed. If that's hard, we might have the template add-ins that ship in the NuGet have uncompressed assemblies, and only then compress and save back as compressed by the packing task. But I doubt that would be much easier.

**Comment by Sergey-Vlasov** [comment]
We already have ExcelDnaPackCompressResources option.

**Comment by gmichaud** [comment]
How does that relate/impact the antivirus issues that you have been working on recently? We have a user that always had issues with McAfee and with1.6.1-alpha6 it appears to have gone away. Want to make sure to keep the necessary settings OFF to prevent this from returning again.

**Comment by govert** [comment]
Hi @gmichaud - We've made a few changes with version 1.6.1 to try to see what helps with the anti-virus detections. Initially we removed both the encoding and the compression. For v1.6.1-alpha6 we had no encoding or compression of the packed assembly resources. With version 1.6.1-beta1 we put back the compression by default, but you can add a project property to disable the compression:
```
	  <ExcelDnaPackCompressResources>false</ExcelDnaPackCompressResources>
```

We have removed the extra encoding completely and won't be putting that back.

From [this discussion on the Google group](https://groups.google.com/g/exceldna/c/Tz2IHKIEziM/m/z7you5CjBQAJ) it seemed like the ESET detection was only due to the extra encoding we were doing, and they were not bothered by the compression. 

I have no information about other anti-virus vendors, nor do I have any information that indicates whether compressing packed resources is a problem or not. But you can now switch it easily for your build.

I appreciate any feedback you have from real use, whether you switch the compression off or leave it on.

**Comment by wh1t3cAt1k** [comment]
@govert is "multi threaded run" in build.props also something that potentially triggers AV detection or it can be safely kept on at all times?

**Comment by govert** [comment]
@wh1t3cAt1k Do you mean the property `ExcelDnaPackRunMultithreaded` ?
This has no runtime effect - it just determines whether the compression of assemblies during build is performed concurrently on multiple threads. It's just a build performance optimization and should not affect the resulting .xll file.
