### ISSUE TITLE
Investigate using .deps.json file to control packing list

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#532]
From issue #516 - we can get a .deps.json file that is used to set up the assembly resolver for runtime dependencies. It would be nice to use this file in the packing task to decide what files to pack (both managed and, once we have support for packing these - #510 -  also mixed/native libraries).

At runtime, when an `AssemblyDependencyResolver` is created with the file location of a .dll or .exe, it finds a matching .deps.json file and populates a set of dictionaries that are later used to resolve the paths to specific assemblies. I think I've seen these set up under the debugger, but can also be found like this:

```
            Debug.Print($"APP_CONTEXT_DEPS_FILES: {AppContext.GetData("APP_CONTEXT_DEPS_FILES")}");
            Debug.Print($"TRUSTED_PLATFORM_ASSEMBLIES: {AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")}");
            Debug.Print($"PLATFORM_RESOURCE_ROOTS: {AppContext.GetData("PLATFORM_RESOURCE_ROOTS")}");
            Debug.Print($"NATIVE_DLL_SEARCH_DIRECTORIES: {AppContext.GetData("NATIVE_DLL_SEARCH_DIRECTORIES")}");
            Debug.Print($"APP_PATHS: {AppContext.GetData("APP_PATHS")}");
```

We might use an `AssemblyDependencyResolver` in the build task, if we don't want to parse and process the .deps.json file ourselves. 
One problem in that case is that we somehow have to set up the context under which the resolution happens (e.g. .NET version, 32-bit vs 64-bit) to get to the right libraries - since these might depend on the runtime identifier etc.

Alternatively, we can pull out what we need from the .deps.json file directly, by trying to see how the format works.

**Comment by govert** [comment]
Maybe there is some way to use the dotnet "PublishSingleFile" feature, or the code from the implementation of that feature, for what we want to do here. https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli

**Comment by Sergey-Vlasov** [comment]
PublishSingleFile works only for exe projects.

**Comment by govert** [comment]
I was wondering how the PublishSingleFile task resolves the dependencies to pack.

**Comment by Sergey-Vlasov** [comment]
Using DependencyContextJsonReader from Microsoft.Extensions.DependencyModel package we can get the following file list.

```cs
using Microsoft.Extensions.DependencyModel;

DependencyContextJsonReader reader = new();
DependencyContext dc = reader.Read(new FileStream(@"MultiLibs\AddIn\bin\Debug\net6.0-windows\AddIn.deps.json", FileMode.Open));

foreach (RuntimeLibrary i in dc.RuntimeLibraries)
{
    foreach (RuntimeAssetGroup k in i.RuntimeAssemblyGroups)
    {
        foreach (var p in k.AssetPaths)
            Console.WriteLine($"{k.Runtime} {p}");
    }

    foreach (RuntimeAssetGroup k in i.NativeLibraryGroups)
    {
        foreach (var p in k.AssetPaths)
            Console.WriteLine($"{k.Runtime} {p}");
    }

    foreach (ResourceAssembly k in i.ResourceAssemblies)
        Console.WriteLine($"{k}");
}
```

> AddIn.dll
>  lib/net6.0-windows7.0/ExcelDna.Integration.dll
>  lib/netstandard2.1/System.Data.SQLite.dll
> linux-x64 runtimes/linux-x64/native/SQLite.Interop.dll
> osx-x64 runtimes/osx-x64/native/SQLite.Interop.dll
> win-x64 runtimes/win-x64/native/SQLite.Interop.dll
> win-x86 runtimes/win-x86/native/SQLite.Interop.dll
>  lib/net6.0/System.CodeDom.dll
> win runtimes/win/lib/net6.0/System.Management.dll
>  lib/net6.0/System.Management.dll
>  Lib1.dll
>  Lib2.dll

Though it is not exactly what we want because lib/*.dlls are actually directly in the output directory.

**Comment by govert** [comment]
I think you're on the right track . . .
From there you can build a DependencyContext (for a specific runtime by setting up the TargetInfo)?

**Comment by govert** [comment]
Or just put together the list from there?
We know we're targeting win-x86 or win-x64, and I suppose a more specific entry like the "win" one for System.Management beats a local-copied one like lib/net6.0/System.Management.dll. I don't know

**Comment by Sergey-Vlasov** [comment]
```cs
Console.WriteLine($"GetRuntimeNativeAssets");
foreach (var p in DependencyContextExtensions.GetRuntimeNativeAssets(dc, "win-x64"))
    Console.WriteLine($"{p}");
Console.WriteLine();

Console.WriteLine($"GetRuntimeNativeRuntimeFileAssets");
foreach (var p in DependencyContextExtensions.GetRuntimeNativeRuntimeFileAssets(dc, "win-x64"))
    Console.WriteLine($"{p.Path}");
Console.WriteLine();

Console.WriteLine($"GetRuntimeAssemblyNames");
foreach (var p in DependencyContextExtensions.GetRuntimeAssemblyNames(dc, "win-x64"))
    Console.WriteLine($"{p.FullName}");
```

> GetRuntimeNativeAssets
> runtimes/win-x64/native/SQLite.Interop.dll
> 
> GetRuntimeNativeRuntimeFileAssets
> runtimes/win-x64/native/SQLite.Interop.dll
> 
> GetRuntimeAssemblyNames
> AddIn
> ExcelDna.Integration
> System.Data.SQLite
> System.CodeDom
> System.Management
> Lib1
> Lib2

Also not exactly what we need.

**Comment by govert** [comment]
You at least need the more general "win" runtimeidentifier too - to get the right System.Management.dll.

**Comment by Sergey-Vlasov** [comment]
It looks like PublishSingleFile is implemented using:
https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/GenerateBundle.cs
https://github.com/dotnet/runtime/blob/main/src/installer/managed/Microsoft.NET.HostModel/Bundle/Bundler.cs

And they take FilesToBundle list not from .deps.json, but from Microsoft.NET.Publish task’s internal files to publish list.

**Comment by Sergey-Vlasov** [comment]
We can start with packing only native .dlls from .deps.json. It will enable the primary scenario of various libraries under .NET 6 having native components.

And to preserve the directory structure of dependencies, I suggest to store them in a zip archive stored as a resource.

**Comment by govert** [comment]
Yes - I think packing the native (and managed) platform-specific libraries that are mentioned in the .deps.json would be a good start. At a first glance, it looks to me like the .deps.json is generated from the same list (or close enough) in that publish task. If we run into lots of problems, we can revisit this easily.

I don't think we should keep the platform-specific 'runtime' directory structure though:
1. When packing, we know exactly which of the two target platforms are applicable (win-x64 or win-x86).
2. I don't think we expect to load duplicate libraries with the same name into the process (I think that only works with some 'activation context' support, and gets messy quickly).
3. We're not expecting to have the .deps.json at runtime for the packed add-in.

So it might be better to resolve the platform-specific libraries at build time (somehow) and effectively pack a flattened list where we assume the name is unique. Then at runtime we resolve managed libraries as we currently do, and for native libraries we add an unpacking-to-a-temp-directory step and resolve from there. We might have an adjusted name for the resource type, like ASSEMBLY_NATIVE instead of ASSEMBLY.

That also keeps the whole compression / no compression story consistent as we add native library support.

**Comment by Sergey-Vlasov** [comment]
I did plan to have the .deps.json at runtime in a temp directory near 'runtime' directory for .NET to resolve full paths to dependencies.

But if we don't support duplicate libraries with the same name, we may work without a directory structure.

**Comment by govert** [comment]
OK I understand it if we have a .deps.json at runtime. I'm still not keen to have the libraries stored as a .zip file, but we could encode the path in the name so that they extract to the same relative path, and then use the .deps.json for the resolution. This assumed we can have a .deps.json in a different directory to the .xll file, and it will resolve relative to the .deps.json location instead of the .xll location. I'm not sure about this, but maybe you can check.
But we'd still have to figure out at build time what to pack for a particular platform. And once we've done that, continuing to depend on the .deps.json and directory tree seems more complicated.
I think try something, and we'll see how it works in practice.

**Comment by Sergey-Vlasov** [comment]
For DependencyContextJsonReader
<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="7.0.0" />
requires at least net462 as a TargetFramework.

And support for .NET Framework 4.5.2, 4.6, and 4.6.1 ended on April 26, 2022.

Can we finally change TargetFramework from net452 to net462 for the ExcelDna.AddIn.Tasks project?

**Comment by govert** [comment]
Yes , that would be fine.
