### ISSUE TITLE
Source Link support

### ISSUE THREAD

**Issue by akgvn** [Excel-DNA/ExcelDna#534]
Please consider adding [source link](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) support and publishing pdb files on nuget.

It will make it much easier to debug & fix problems related to ExcelDNA, may make it easier to contribute to it too.

**Comment by govert** [comment]
@Sergey-Vlasov Could you try to set this up, and add the symbol packages to our build?

**Comment by Sergey-Vlasov** [comment]
I've tested Source Link debugging with ExcelDna.Integration 1.6.1-beta3 and it works:

![sl](https://user-images.githubusercontent.com/15168845/214325419-86e5780e-2a31-4e73-91aa-6da25733520b.png)



NuGet.org Symbol Server should be enabled in VS options:

![ss](https://user-images.githubusercontent.com/15168845/214325583-94d58176-bd4a-490a-a64a-513fe0487833.png)

**Comment by Sergey-Vlasov** [comment]
@govert Which other packages do you want to support with Source Link?

**Comment by Sergey-Vlasov** [comment]
Source Link also works with Go To Definition. In this case debugging mode and symbols are not required.
