### ISSUE TITLE
Improve .NET 6 runtime checks at startup

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#536]
We should check that we show information error messages if startup fails due to missing .NET 6 runtime. In particular, it would be good to check and explain the 32-bit / 64-bit situation, in the light of this discussion: https://github.com/Excel-DNA/ExcelDna/discussions/535#discussioncomment-4374563

**Comment by Sergey-Vlasov** [comment]
I've tested and found that without .NET 6, get_hostfxr_path returns CoreHostLibMissingFailure:

> CoreHostLibMissingFailure 	
> 0x80008083 	
> -2147450749 	
> 131 	
> One of the dependent libraries is missing. Typically when the hostfxr, hostpolicy or coreclr dynamic libraries are not present in the expected locations. Probably means corrupted or incomplete installation.

https://github.com/dotnet/runtime/blob/main/docs/design/features/host-error-codes.md

**Comment by govert** [comment]
I'm hoping we can deal with these failures a bit better, by giving some details to the user (at least the error code) and for the most common cases we can expect, to give additional information that is relevant if we can. 

 For example, if .NET 6 is not installed, we should show a friendly message indicating this, with at least a link and download instructions to this (very confusing) page https://dotnet.microsoft.com/en-us/download/dotnet/6.0 , or similar.
Another case that we can try to deal with explicitly is the 32-bit / 64-bit story from the original discussion #535 .  Since we are running inside the Excel process already, we might indicate what needs to be installed for the add-in to work.
