### ISSUE TITLE
Expose IsInFormulaEditMode

### ISSUE THREAD

**Issue by garethhayter** [Excel-DNA/ExcelDna#537]
I currently need to create a customised version of Excel DNA, purely to access a single function:  `RunMacroSynchronization.IsInFormulaEditMode()`

I do this by adding something like this in a custom class:
`public static bool IsInFormulaEditMode => RunMacroSynchronization.IsInFormulaEditMode();`

I'm now hitting a problem where the version of Excel DNA in the Distribution folder gets zero false positives on VirusTotal, while my custom version gets a few false positives. I could investigate this further, but if this extra feature is useful to anyone else, then it might be worthwhile adding it to base Excel DNA.....then I won't need to create any custom version ;-)

Thoughts? Useful to anyone?

**Comment by govert** [comment]
Hi @garethhayter I think that will be fine. I'm wondering whether the whole PenHelper call should rather be exposed. We've had to put some native support to call that safely.

In the meantime, I suppose you can just call it via reflection?
