### ISSUE TITLE
How can I update type of cell value when using RTD Server update topic

### ISSUE THREAD

**Issue by ThanhHaiDang96** [Excel-DNA/ExcelDna#539]
Hello, 
I create a RTD Server base on TimerRTD example. How can I change data type of value when I call Topic.UpdateValue() function?
E.g. The new value type is DateTime will be displayed as DateTime instead of double.
Thanks and best regards,
T.H

**Comment by govert** [comment]
Date / times are a bit funny in Excel. Natively there is no such cell value, they're always represented by doubles. Then what you see as the date/time display in the cell is just a format that is applied to the cell. So when your function returns a DateTime, Excel-DNA converts that to a double which is passed back to Excel. If the cell, is formatted with some date/time format, it will display like that. Else you just see a double.
On the sheet you can press Ctrl+Shift+3 or Ctrl+Shift+2 to set the format easily.
There are some hackish ways to set the format of the calling cell from inside a UDF, but I would not recommend that.
