### ISSUE TITLE
Building ExcelDNA from source

### ISSUE THREAD

**Issue by rkapl123** [Excel-DNA/ExcelDna#543]
Dear Govert!

I’m trying to build ExcelDNA from source (current version 1.6.1-alpha6) to check how I can get rid of the false positive Virus-scan problem.
I’ve managed to build all steps except for the last one, where I'm missing something called DeveloperTools (with a ExcelDna.Testing subdirectory) that needs to be built in the MasterBuild.cmd
Is there anything I can use, I didn't find this on the ExcelDNA github site.

I'm also going to write the steps up and put it somewhere on [https://docs.excel-dna.net/](https://docs.excel-dna.net/)

-regards,
Roland

**Comment by govert** [comment]
Hi @rkapl123 - the DeveloperTools repository is not public. But you can just remove that entry from the MasterBuild.cmd file.

**Comment by rkapl123** [comment]
OK, I'll add a hint into the building doc. Thank you!
