### ISSUE TITLE
Excel function parameter validate

### ISSUE THREAD

**Issue by SKYC829** [Excel-DNA/ExcelDna#546]
how can i validate parameters before excel function calls?
e.g.
excel data:
    A           B
    1     some word

```C#
[ExcelFunction(Name = "MyAdd")]
public static object Add(int v1,int v2)
{
    // .....
}
```
when use =MyAdd($A$1,$B$1) in excel, how can i validate cell $B$1 is numeric or not before invoke MyAdd function

**Comment by govert** [comment]
If you declare your function as `int` (or `double`) then Excel will only call the function if the input is of the tright type (or can be converted to that type). Otherwise, Excel will return #VALUE without ever calling your function.

If you want to do the validation yourself, you can change your parameter type to `object`, in which case your function will always be called, and you can check that argument type passed in and deal with it as you want.

**Comment by SKYC829** [comment]
> If you declare your function as `int` (or `double`) then Excel will only call the function if the input is of the right type (or can be converted to that type). Otherwise, Excel will return #VALUE without ever calling your function.
> 
> If you want to do the validation yourself, you can change your parameter type to `object`, in which case your function will always be called, and you can check that argument type passed in and deal with it as you want.

what if i want validate parameter's value is between some range,like validate $B$1 is between 0 and 10 Is it only possible to write or call duplicate validation functions within the implementation of each function?

**Comment by govert** [comment]
You could write a validator extension, like in an aspect-oriented style, and then automatically generate the wrapper code that does that validation at runtime, The Excel-DNA "Registration" extensions can help you do this kind of function transformations at runtime. See the project and repository here: https://github.com/Excel-DNA/Registration

**Comment by SKYC829** [comment]
> You could write a validator extension, like in an aspect-oriented style, and then automatically generate the wrapper code that does that validation at runtime, The Excel-DNA "Registration" extensions can help you do this kind of function transformations at runtime. See the project and repository here: https://github.com/Excel-DNA/Registration

Thank you very much. i'll check how to use it :)
