### ISSUE TITLE
Diagnostic Logging : "default configuration" does not work

### ISSUE THREAD

**Issue by RudyCo** [Excel-DNA/ExcelDna#55]
Hello,
I added the following lines to an Excel Command (a brand new Excel-DNA project).
Trace.TraceInformation("Trace information!");
Trace.TraceWarning("Trace warning!");
Trace.TraceError("Trace error!");

I expect to see the LogDisplay opens (because of TraceError) and I expect to see the two last messages (because TraceInformation should not be logged by default).

The documentation states:
"If there is no .xll.config configuration file for the add-in, or there are no entries related to the ExcelDna.Integration TraceSource in the .config file, the following configuration is made"

Nonetheless, when I debug the running code, the Trace class has only the DefaultTraceListener.

Am I missing something or is this a bug?
Thanks in advance.

NB: I am running Excel 2013 64 bit

**Comment by govert** [comment]
I wouldn't expect the `Trace.TraceXXX` methods to work via the internal tracing mechanism without any extra effort.

For now I've only set up the tracing for the Excel-DNA internals, though making an example that shows how to extend this into your add-in would be a good idea.

The `LogDisplayTraceListener` class is public, so you can add that to your `TraceSource` to get Trace messages to go to the `LogDisplay` window.

**Comment by koulkov** [comment]
Thanks Govert for the clarification.
I am able to use the LogDisplay by adding the following code snippet to my AddIn:

public void AutoOpen()
{
	// Log warnings and errors to the Excel-DNA LogDisplay
	Trace.Listeners.Add(new LogDisplayTraceListener());

	// Show unhandled exception messages in Excel cells
	ExcelIntegration.RegisterUnhandledExceptionHandler(obj =>
	{
		if (obj is Exception)
		{
			var ex = obj as Exception;
			var message = String.Format("#EXCEPTION: {0}", ex.Message);
			return message;
		}

		return String.Format("#UNEXPECTED_EXCEPTION: " + obj.ToString());
	});
}

That's being said, I think it would be great to update the documentation page accordingly.
