### ISSUE TITLE
AddIn will not launch if project is hosted in WSL

### ISSUE THREAD

**Issue by lawrence-vo** [Excel-DNA/ExcelDna#553]
If the project is located in WSL like `\\wsl.localhost\Ubuntu\..`, the project will build but will show a pop up that says `'AddIn64.xll' cannot be accessed. The file may be corrupted, located on a server that is not responding, or read-only.`

I have confirmed that the file is not readonly. If I move it to the Windows filsystem, the addin loads as expected.

**Comment by lawrence-vo** [comment]
`result2 = Excel12v(xlFunction, parameters.Length, ppOpers, ptr);` in function `TryExcelImpl12` is throwing the error

**Comment by govert** [comment]
You do need to set the execute flag on te .xll.

**Comment by lawrence-vo** [comment]
@govert  apologies but I am not exactly sure where to put it? Do I put in `commandLineArgs` like `\execute`?

```
{
  "profiles": {
    "Excel": {
      "commandName": "Executable",
      "executablePath": "C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE",
      "commandLineArgs": "ExcelAddIn2-AddIn64.xll"
    }
  }
}

```

Thanks!

**Comment by govert** [comment]
Not sure if this is your problem with WSL, but if the file were hosted on a Linux share, the file has to have the execute Unix file attribute set

**Comment by lawrence-vo** [comment]
For anyone that stumbles on this thread,

I ended up putting `<BaseOutputPath>$(localappdata)\ExcelAddIn</BaseOutputPath>` in my .csproj to have it build on the window side.
