### ISSUE TITLE
ExcelDna ribbon doesn't show in another office versions.

### ISSUE THREAD

**Issue by reza-ebrahimi** [Excel-DNA/ExcelDna#56]
I have compile my project and works good with Excel 2010 but its ribbon not showing in Excel 2007 version.

Is there any workaround to compstible ExcelDna with multiple Excel version?

**Comment by govert** [comment]
Hi,

You should check the xml namespace in the customUI xml. The xmlns for Excel 2007 will work for later versions too, but the newer xmlns will only work for Excel 2010+.

The Excel-DNA samples on Github (under Distribution/Samples/Ribbon) include both xmlns versions.

-Govert

On 02 Jan 2016, at 16:38, Reza Ebrahimi <notifications@github.com<mailto:notifications@github.com>> wrote:


I have compile my project and works good with Excel 2010 but its ribbon not showing in Excel 2007 version

Is there any workaround to compstible ExcelDna with multiple Excel version?

**Comment by reza-ebrahimi** [comment]
@govert Thanks a lot, problem fixed.

Microsoft Office 2010 schema namespace: ```xmlns='http://schemas.microsoft.com/office/2009/07/customui'```

Microsoft Office 2007 schema namespace: ```xmlns='http://schemas.microsoft.com/office/2006/01/customui'```
