### ISSUE TITLE
ExcelDna.Interop package should copy files for F# under .NET 6

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#563]
In the ExcelDna.Interop package we added an extra build target when building for .NET 6 to set the "Embed Interop Types" flag and prevent the assemblies from being copied to the output directory.
For F# projects, there is no support for embedding COM interop assemblies, so we require the files to be copied to output (and added to packing) when building an F# project.
So the special build target should only apply if the project language is C# or VB.NET and not for F# projects.
See this repository for an example https://github.com/govert/FsComInterop , which works after copying the assemblies into a local lib folder, and including the references explicitly. We would rather have this work by just referencing the ExcelDna.Interop package, and not having extra assembly copies and references.

**Comment by govert** [comment]
@Sergey-Vlasov I've tried to make a new version of the ExcelDna.Interop package - I'm calling it version 15.0.1 - with these changes. I have not pushed this package version, it is just local. However, for the F# project I'm still not getting the interop assemblies in the output directory.

I do see that your condition is evaluated correctly. With Detailed build logging:
* Using the original v 15.0.0 package I see this:
```
1>Target LinkExcelDnaInteropEmbeddableAssemblies:
1>Target HideExcelDnaInteropEmbeddableAssemblies:
```

* Using the v 15.0.1 I see:
```
1>Target "LinkExcelDnaInteropEmbeddableAssemblies" skipped, due to false condition; ($(MSBuildProjectExtension)!='.fsproj') was evaluated as (.fsproj!='.fsproj').
1>Target HideExcelDnaInteropEmbeddableAssemblies:
```

So the condition is correct, and being evaluated right. However, the three assemblies are not copied to the output directory.
Having the files explicitly under the project (in my case in a lib directory) and adding References to the project file, with a HintPath pointing to the files, work correctly:
```
<ItemGroup>
    <Reference Include="Microsoft.Office.Interop.Excel">
      <HintPath>lib\Microsoft.Office.Interop.Excel.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Vbe.Interop">
      <HintPath>lib\Microsoft.Vbe.Interop.dll</HintPath>
    </Reference>
    <Reference Include="office">
      <HintPath>lib\Office.dll</HintPath>
    </Reference>
  </ItemGroup>
```

I'm testing  with this project. Changing from the explicit References to the 15.0.1 package breaks the TestComVersion() function etc.

Could you try to figure out why it is still not copying the assemblies for F#?

**Comment by Sergey-Vlasov** [comment]
@govert  Have you made a new version of the ExcelDna.AddIn package too, as it also had HideExcelDnaInteropEmbeddableAssemblies target?

**Comment by govert** [comment]
@Sergey-Vlasov Thank you - I think that's the problem, and will check. I had seen the changes to ExcelDna.AddIn pacakage in the PR, but completely forgot about it yesterday.
