### ISSUE TITLE
Excel-DNA 33.9 and Excel 16 /2015 64 bit

### ISSUE THREAD

**Issue by drdbkarron** [Excel-DNA/ExcelDna#58]
I am updating a client UDF package that included some ribbon menus and built in documentation so the function would show up in the function directory during spreadsheet entry and the types would validate.

The demo software DOES NOT FUNCTION out of the box on 64 bit.
I had to fall back to compileing 32 bit and it seems to work on 64 bit excel.

**Comment by govert** [comment]
I presume you mean Excel 2016. I've not tried the 64-bit version of Excel 2016 myself, but I've not had any reports of problems with Excel-DNA add-ins in that version.

I'm not sure what you are rebuilding as 32-bit, but it is not possible to load the 32-bit .xll into the 64-bit version of Excel.

Can you explain what add-in you are loading (is it the file Distribution\ExcelDna64.xll from the .zip Release file?) and whether any messages appear, or other errors are show?

**Comment by govert** [comment]
I'm closing this for now - feel free to re-open. I believe this is just due to uncertainty about the exact Excel version being used.
