### ISSUE TITLE
Excel new instance debugging

### ISSUE THREAD

**Issue by nsulikowski** [Excel-DNA/ExcelDna#583]
Is there any way to make `ExcelDnaSetLaunchSettings` populate the executable with the /x flag to force Excel to open a new instance?
This is helpful when debugging if I have another Excel's open in that computer.

```
C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE /x
```

**Comment by govert** [comment]
You can disable the debug settings that are updated when you build with this property:
```
<RunExcelDnaSetDebuggerOptions>false</RunExcelDnaSetDebuggerOptions>
```

Then you can set the extra flag in the debug options and they will remain.

**Comment by nsulikowski** [comment]
That worked. Thanks.

**Comment by nsulikowski** [comment]
Thanks. I do see the command line arguments:
/x "aaaa-AddIn64.xll"
Thanks.
