### ISSUE TITLE
System.Reflection.Metadata in NuGet package for build

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#589]
We have this as a dependency of our build task, but we're not shipping the library in the NuGet package.
The build normally seems to work fine, but [this discussion](https://groups.google.com/g/exceldna/c/wYJ76hJLQ_w) makes me ask whether we are supposed to ship it or not.
How would we know whether this is expected to be available in the build environment?

**Comment by Sergey-Vlasov** [comment]
As I understand, System.Reflection.Metadata comes with .NET Core and VS MSBuild.

I’m (unfortunately?) can’t reproduce the problem from the discussion on my machine(s). Tried VS 2022 17.1.6 and VS 2019 too.

And without experiencing the problem, I can’t try to see if adding System.Reflection.Metadata.dll to our package will help or not.

**Comment by Michael-Kempe** [comment]
Hi, I see the same error when building my project on VS2019 v16.11.32.

Adding a reference to the project does not help - also adding System.Reflection.Metadata.dll v6.0.0.0 to the  Excel DNA Package Folder (ExcelDna.AddIn.1.7.0\tools\net452\) does not work.

My project:
AnyCPU
.Net Framework v4.7.2
VS 2019 v16.11.32

My project worked with ExcelDna.AddIn v1.6

Any suggestions?

Here's the error message:
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ExcelDna.PackedResources.ExcelDnaPack.IsAssembly(String path, Boolean& isPE)
   at ExcelDna.PackedResources.ExcelDnaPack.IsNativeLibrary(String path)
   at ExcelDna.PackedResources.ExcelDnaPack.PackDnaLibrary(String dnaPath, Byte[] dnaContent, String dnaDirectory, ResourceUpdater ru, Boolean compress, Boolean multithreading, List`1 filesToPublish, Boolean packManagedDependencies, String[] dependenciesToExcludeParam, String outputBitness, IBuildLogger buildLogger)
   at ExcelDna.PackedResources.ExcelDnaPack.Pack(String dnaPath, String xllOutputPathParam, Boolean compress, Boolean multithreading, Boolean overwrite, String usageInfo, List`1 filesToPublish, Boolean packNativeLibraryDependencies, Boolean packManagedDependencies, String excludeDependencies, Boolean useManagedResourceResolver, String outputBitness, IBuildLogger buildLogger)
   at ExcelDna.AddIn.Tasks.PackExcelAddIn.Execute()

=== Pre-bind state information ===
LOG: DisplayName = System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/
LOG: Initial PrivatePath = NULL
Calling assembly : ExcelDna.AddIn.Tasks, Version=1.1.0.0, Culture=neutral, PublicKeyToken=f225e9659857edbe.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: The same bind was seen before, and was failed with hr = 0x80070002.	Test.Excel

**Comment by govert** [comment]
@Michael-Kempe Thanks for reporting that you're running into this problem too.
I'll have to test with a clean machine and VS 2019 installation to see if this can be reproduced.

My only immediate suggestion is to build with VS 2022, or maybe from a 'dotnet build' command line.

**Comment by Sergey-Vlasov** [comment]
I've retested it with VS 2019 on my main workstation and on a clean VM with the project attached and still can't reproduce the problem. Wondering what may cause it...


[MyAddin.zip](https://github.com/Excel-DNA/ExcelDna/files/13849317/MyAddin.zip)

**Comment by NicolasLatremouille** [comment]
I was having this exact same issue **exclusively when trying to pack** a .dll built by a different project in the solution (using <Reference Path="MyClassLib.dll" Pack="true" />).
I tried with both Excel-Dna v1.8 and v1.7 with no luck.

After pasting System.Reflection.Metadata.dll v6.0.0 and all its dependencies into the bin/Release folder in the project of the **of the packed .dll** (not the bin of the add-in project), the build error disappeared... (I tried this based on comments here: https://github.com/dotnet/roslyn/issues/13146)

I wanted to post my full build error message here, so I deleted the copy of System.Reflection.Metadata.dll, but now I don't get error. I will try to update if I get it again.

Running VS2017 15.9.66 and targetting framework 4.7.2 (yes old stuff)

**Comment by govert** [comment]
@NicolasLatremouille Could you please try with the latest prerelease version of Excel-DNA v1.9.0-alpha2 ?
We have changed how the assemblies are loaded into the build process when packing (https://github.com/Excel-DNA/ExcelDna/commit/5a9db0980d3386dac11abc860c75cee2c277ef0d) and I'm wondering if this is the same issue.

**Comment by NicolasLatremouille** [comment]
Hello Govert, How would I go about doing that?
Sorry a bit a newbie...

> @NicolasLatremouille Could you please try with the latest prerelease version of Excel-DNA v1.9.0-alpha2 ? We have changed how the assemblies are loaded into the build process when packing ([5a9db09](https://github.com/Excel-DNA/ExcelDna/commit/5a9db0980d3386dac11abc860c75cee2c277ef0d)) and I'm wondering if this is the same issue.

**Comment by NicolasLatremouille** [comment]
> @NicolasLatremouille Could you please try with the latest prerelease version of Excel-DNA v1.9.0-alpha2 ? We have changed how the assemblies are loaded into the build process when packing ([5a9db09](https://github.com/Excel-DNA/ExcelDna/commit/5a9db0980d3386dac11abc860c75cee2c277ef0d)) and I'm wondering if this is the same issue.

Getting the same thing:
```
1>------ Build started: Project: GraphicsExport, Configuration: Release Any CPU ------
1>  GraphicsExport -> C:\Users\XXXXXXX\source\repos\ReportAutomation\GraphicsExport\bin\Release\GraphicsExport.dll
2>------ Build started: Project: ReportAutomationAddIn, Configuration: Release Any CPU ------
2>  ---
2>  ExcelDnaSetDebuggerOptions: EXCEL.EXE path for debugging: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE
2>  ExcelDnaSetDebuggerOptions: Add-In for debugging: bin\Release\ReportAutomationAddIn-AddIn64bit.xll
2>  ReportAutomationAddIn -> C:\Users\XXXXXXXX\source\repos\ReportAutomation\ReportAutomation\bin\Release\ReportAutomation.dll
2>  ---
2>  ExcelDnaBuild: ReportAutomationAddIn-AddIn.dna -> bin\Release\ReportAutomationAddIn-AddIn32bit.dna
2>  ExcelDnaBuild: ..\packages\ExcelDna.AddIn.1.9.0-alpha2\build\..\tools\\net452\ExcelDna.xll -> bin\Release\ReportAutomationAddIn-AddIn32bit.xll
2>  ExcelDnaBuild: ---
2>  ExcelDnaBuild: ReportAutomationAddIn-AddIn.dna -> bin\Release\ReportAutomationAddIn-AddIn64bit.dna
2>  ExcelDnaBuild: ..\packages\ExcelDna.AddIn.1.9.0-alpha2\build\..\tools\\net452\ExcelDna64.xll -> bin\Release\ReportAutomationAddIn-AddIn64bit.xll
2>  ---
2>  ExcelDnaPack: bin\Release\ReportAutomationAddIn-AddIn32bit.dna -> bin\Release\ReportAutomationAddIn-AddIn32bit-packed.xll
2>  PackExcelAddIn: Using base add-in bin\Release\ReportAutomationAddIn-AddIn32bit.xll
2>  PackExcelAddIn:   ~~> ExternalLibrary path ReportAutomation.dll resolved to bin\Release\ReportAutomation.dll.
2>  PackExcelAddIn:   ~~> Assembly path GraphicsExport.dll resolved to bin\Release\GraphicsExport.dll.
2>MSBUILD : PackExcelAddIn error DNA964120249: Could not load file or assembly 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2>MSBUILD : PackExcelAddIn error DNA964120249: System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2>MSBUILD : PackExcelAddIn error DNA964120249: File name: 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.IsAssembly(String path, Boolean& isPE)
2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.IsNativeLibrary(String path)
2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.PackDnaLibrary(String dnaPath, Byte[] dnaContent, String dnaDirectory, ResourceUpdater ru, Boolean compress, Boolean multithreading, List`1 filesToPublish, Boolean packManagedDependencies, String[] dependenciesToExcludeParam, String outputBitness, IBuildLogger buildLogger)
2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.Pack(String dnaPath, String xllOutputPathParam, Boolean compress, Boolean multithreading, Boolean overwrite, String usageInfo, List`1 filesToPublish, Boolean packNativeLibraryDependencies, Boolean packManagedDependencies, String excludeDependencies, Boolean useManagedResourceResolver, String outputBitness, IBuildLogger buildLogger)
2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.AddIn.Tasks.PackExcelAddIn.Execute()
2>MSBUILD : PackExcelAddIn error DNA964120249: 
2>MSBUILD : PackExcelAddIn error DNA964120249: WRN: Assembly binding logging is turned OFF.
2>MSBUILD : PackExcelAddIn error DNA964120249: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
2>MSBUILD : PackExcelAddIn error DNA964120249: Note: There is some performance penalty associated with assembly bind failure logging.
2>MSBUILD : PackExcelAddIn error DNA964120249: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
2>MSBUILD : PackExcelAddIn error DNA964120249: 
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by NicolasLatremouille** [comment]
> > @NicolasLatremouille Could you please try with the latest prerelease version of Excel-DNA v1.9.0-alpha2 ? We have changed how the assemblies are loaded into the build process when packing ([5a9db09](https://github.com/Excel-DNA/ExcelDna/commit/5a9db0980d3386dac11abc860c75cee2c277ef0d)) and I'm wondering if this is the same issue.
> 
> Getting the same thing:
> 
> ```
> 1>------ Build started: Project: GraphicsExport, Configuration: Release Any CPU ------
> 1>  GraphicsExport -> C:\Users\XXXXXXX\source\repos\ReportAutomation\GraphicsExport\bin\Release\GraphicsExport.dll
> 2>------ Build started: Project: ReportAutomationAddIn, Configuration: Release Any CPU ------
> 2>  ---
> 2>  ExcelDnaSetDebuggerOptions: EXCEL.EXE path for debugging: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE
> 2>  ExcelDnaSetDebuggerOptions: Add-In for debugging: bin\Release\ReportAutomationAddIn-AddIn64bit.xll
> 2>  ReportAutomationAddIn -> C:\Users\XXXXXXXX\source\repos\ReportAutomation\ReportAutomation\bin\Release\ReportAutomation.dll
> 2>  ---
> 2>  ExcelDnaBuild: ReportAutomationAddIn-AddIn.dna -> bin\Release\ReportAutomationAddIn-AddIn32bit.dna
> 2>  ExcelDnaBuild: ..\packages\ExcelDna.AddIn.1.9.0-alpha2\build\..\tools\\net452\ExcelDna.xll -> bin\Release\ReportAutomationAddIn-AddIn32bit.xll
> 2>  ExcelDnaBuild: ---
> 2>  ExcelDnaBuild: ReportAutomationAddIn-AddIn.dna -> bin\Release\ReportAutomationAddIn-AddIn64bit.dna
> 2>  ExcelDnaBuild: ..\packages\ExcelDna.AddIn.1.9.0-alpha2\build\..\tools\\net452\ExcelDna64.xll -> bin\Release\ReportAutomationAddIn-AddIn64bit.xll
> 2>  ---
> 2>  ExcelDnaPack: bin\Release\ReportAutomationAddIn-AddIn32bit.dna -> bin\Release\ReportAutomationAddIn-AddIn32bit-packed.xll
> 2>  PackExcelAddIn: Using base add-in bin\Release\ReportAutomationAddIn-AddIn32bit.xll
> 2>  PackExcelAddIn:   ~~> ExternalLibrary path ReportAutomation.dll resolved to bin\Release\ReportAutomation.dll.
> 2>  PackExcelAddIn:   ~~> Assembly path GraphicsExport.dll resolved to bin\Release\GraphicsExport.dll.
> 2>MSBUILD : PackExcelAddIn error DNA964120249: Could not load file or assembly 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 2>MSBUILD : PackExcelAddIn error DNA964120249: System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 2>MSBUILD : PackExcelAddIn error DNA964120249: File name: 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> 2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.IsAssembly(String path, Boolean& isPE)
> 2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.IsNativeLibrary(String path)
> 2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.PackDnaLibrary(String dnaPath, Byte[] dnaContent, String dnaDirectory, ResourceUpdater ru, Boolean compress, Boolean multithreading, List`1 filesToPublish, Boolean packManagedDependencies, String[] dependenciesToExcludeParam, String outputBitness, IBuildLogger buildLogger)
> 2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.PackedResources.ExcelDnaPack.Pack(String dnaPath, String xllOutputPathParam, Boolean compress, Boolean multithreading, Boolean overwrite, String usageInfo, List`1 filesToPublish, Boolean packNativeLibraryDependencies, Boolean packManagedDependencies, String excludeDependencies, Boolean useManagedResourceResolver, String outputBitness, IBuildLogger buildLogger)
> 2>MSBUILD : PackExcelAddIn error DNA964120249:    at ExcelDna.AddIn.Tasks.PackExcelAddIn.Execute()
> 2>MSBUILD : PackExcelAddIn error DNA964120249: 
> 2>MSBUILD : PackExcelAddIn error DNA964120249: WRN: Assembly binding logging is turned OFF.
> 2>MSBUILD : PackExcelAddIn error DNA964120249: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> 2>MSBUILD : PackExcelAddIn error DNA964120249: Note: There is some performance penalty associated with assembly bind failure logging.
> 2>MSBUILD : PackExcelAddIn error DNA964120249: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> 2>MSBUILD : PackExcelAddIn error DNA964120249: 
> ========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> ```

This workaround worked on the first go:
1. Add just System.Reflection.Metadata.dll & System.Collections.Immutable.dll to .\packages\ExcelDna.AddIn.1.9.0-alpha2\tools\net452\
2. Build > Clean Solution
3. Restart Visual Studio
4. Build packing should work now

**Comment by Sergey-Vlasov** [comment]
I can now reproduce this problem in VS 2017 with the attached sample solution.
[MyAddinWithLib.zip](https://github.com/user-attachments/files/17349486/MyAddinWithLib.zip)
