### ISSUE TITLE
XLL File is treated as a Trojan:Win32/WacatacH!m , how to solve it?

### ISSUE THREAD

**Issue by fangjunai** [Excel-DNA/ExcelDna#599]
XLL File is treated as a Trojan:Win32/WacatacH!m , how to solve it?

Windows 10 or Windows 11 

Version 1.5:
 package id="ExcelDna.AddIn" version="1.5.0" targetFramework="net472"
package id="ExcelDna.Integration" version="1.5.0" targetFramework="net472"

![Microsoft Defender](https://user-images.githubusercontent.com/8251679/233597987-970835e8-a8ec-4831-957d-8f54ad28e83d.png)

**Comment by govert** [comment]
Can you try ExcelDna.AddIn version 1.7.0-rc3?

**Comment by fangjunai** [comment]
Thank you, I'll give it a try
