### ISSUE TITLE
RTD-based ExcelAsyncUtil.Observe does not restart when reopening book

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#60]
Follow-up from this discussion: https://groups.google.com/d/topic/exceldna/zuPN8-W_5KU/discussion

**Comment by janct** [comment]
Hi Govert,

I also have this problem with version 0.33. Version 0.32 works fine.

**Comment by govert** [comment]
The problem is due to us now using a stable ProgId for the internal ExcelObserverRtdServer (https://github.com/Excel-DNA/ExcelDna/blob/41645feea71a6dba4c77b4052bb8d51fd7661d2a/Source/ExcelDna.Integration/ExcelRtdObserver.cs#L580-L580).

I need to revisit the registration here ...

**Comment by govert** [comment]
OK - I'm still looking to see what changes caused this behaviour.

**Comment by govert** [comment]
I've found the bug - it was introduced in version 0.33 by a fix to another RTD-related update problem.

Commit 79cc05f0d82499239fd50172d690d40aa3f78518 should fix this.

**Comment by janct** [comment]
It looks fine now. Thanks!
