### ISSUE TITLE
After Unregistering an add-in with COM object, Excel crashes when closing

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#61]
Due to DllCanUnload() attempting to reload the add-in during shutdown.
Reproduced in Samples\MasterSlave

**Comment by govert** [comment]
Commit 0ea3ed668427d0b43d2597a2113c5728b45e7134 is a partial fix for this - it stops the crash but  won't allow the .xll to be unloaded completely (if COM features were used).

**Comment by terryaney** [comment]
What does 

> won't allow the .xll to be unloaded completely (if COM features were used)

 mean exactly?

**Comment by govert** [comment]
If your add-in has a ribbon or CTP, or uses the COM sever featur, or uses RTD or async functions, then the .xll file may be locked by the Excel process even after your add-in is unloaded. This means you can't delete the .xll file ntil Excel is closed.
