### ISSUE TITLE
XlCustomMarshal::MarshalManagedToNative memory corrupted

### ISSUE THREAD

**Issue by dreamershl** [Excel-DNA/ExcelDna#62]
After a long hour running, always crash the Excel with "System.NullReferenceException"

The following are the variable info. Strangely the pOper is 0x0000000c0 for the last string value of the ManagedObj.

![screen shot 2016-02-27 at 7 49 13 am](https://cloud.githubusercontent.com/assets/1271739/13368722/f7b21b80-dd27-11e5-9c7b-f4b861a76bfd.png)

![screen shot 2016-02-27 at 7 54 11 am](https://cloud.githubusercontent.com/assets/1271739/13368764/5baa1f70-dd28-11e5-92c6-18860ae725ae.png)

![screen shot 2016-02-27 at 7 53 12 am](https://cloud.githubusercontent.com/assets/1271739/13368845/2ec5c828-dd29-11e5-8947-c93d89472001.png)

**Comment by govert** [comment]
Strange! I can't think of other similar reports.
My first thought is that I would not trust the debugger display. It seems unlikely that the stack is corrupt, but is that not what it would imply?

* Which Excel version (and 32/64-bit?)
* Under Release as well as Debug versions?
* Are there changes that make the error not appear?
* Can you make a simple sample that reproduces the error?

**Comment by govert** [comment]
You need to be a bit careful: The code you show is the debug version, which uses the pre-Excel 2007 C API (XlOper). It is likely that your release code running under Excel 2007+ will use the XlOper12 version. It is a bit more likely that there is a problem with the pre-Excel 2007 code than in the normal Excel 2007+ code which I guess most users run.

The reason for compiling the pre-Excel 2007 code under Debug is just so that it gets tested a bit.

**Comment by dreamershl** [comment]
1. Excel is 2010 (version:14.0.7166.5000 32 bits)
2. It is in the ExcelDNA debug version. 

The ExcelDNA debug version is from the github source code. 

In the release version, this issue also happened although not so often. Because my project need almost run for 24*7 hours.  Will monitor it.

**Comment by govert** [comment]
How does the problem present itself in your Normal running - does Excel crash or just get a bad function result?

Is the array the input to a function, or is it another C API call?
Is it possible the you have some other thread that is changing the array at the same time, so that it changes during marshaling?

Does this happen on different machines?

-Govert

On 28 Feb 2016, at 04:14, Shen liang <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Excel is 2010 (version:14.0.7166.5000 32 bits)
  2.  It is in the ExcelDNA debug version.

The ExcelDNA debug version is from the github source code.

In the release version, this issue also happened although not so often. Because my project need almost run for 24*7 hours. Will monitor it.

**Comment by dreamershl** [comment]
In the report case, it is reported by Visual studio 2015 for the unexpected exception. 

This error happend in the past. I also had thought it may be caused by unintended change. So I put this string array into the static variable. It means the string array is only initialized once and won't be changed any more. But still get this error. 

I do notice in my release version installed in another person's PC. Sometime, Excel quit quietly. When restart the excel, it prompt to disable the addin for the crashing. Now I try to run the release version in my PC for 24 hours. 

Will update you if any new foundings. Thanks a lot for the support.

**Comment by dreamershl** [comment]
this is my code to initialize the string array and UDF to return the result
   
    private static string[] _priceFieldAry = UDFUtils.enumNames(typeof(PriceRTDServer.FIELD));

    [ExcelFunction(Description = "list price fields",
            IsThreadSafe = true, IsExceptionSafe = true, IsVolatile = false)]
        public static object[] _priceFields()
        {
            return _priceFieldAry;
        }

**Comment by dreamershl** [comment]
Would like to highlight one more thing. In the past I try to utilize the multiple thread calculation. After I put the "IsThreadSafe=true" on the UDFs, the application becomes very unstable (always encounter this corrupted memory issue). 

Maybe I should change the attribute "IsThreadSafe=false" and try this function again.

**Comment by govert** [comment]
If you mark your function as IsThreadSafe=true, the obligation is on you to be sure that your implementation really is thread-safe.

Likewise, if your function is marked as IsExceptionSafe=true then any unhandled exception from a function or macro will crash the Excel process.

So these really are advanced option. But if your function just returns a static array, and you can check that the array contents are never updated elsewhere, I would not expect the error.

Maybe some other code is causing memory or stack corruption, and you just happen to detect it in this function.

Have you seen the same NullReferenceException in the same place in the code when returning from that function repeatedly, or only once so far?


On 28 Feb 2016, at 15:04, Shen liang <notifications@github.com<mailto:notifications@github.com>> wrote:


Would like to highlight one more thing. In the past I try to utilize the multiple thread calculation. After I put the "IsThreadSafe=true" on the UDFs, the application becomes very unstable (always encounter this corrupted memory issue).

Maybe I should change the attribute "IsThreadSafe=false" and try this function again.

**Comment by dreamershl** [comment]
In fact, I have encountered this error (always from this function) many times. In the past, I always suspect it is caused by my code and maybe it is only related to my own PC. But after getting a Excel unexpected quit report, I start to believe this error may be caused somewhere.

Another recent quite often reported error (corrupted memory again) is in the Excel native code. But if I just ignore it (by clicking the VS continue debug), Excel will just run as normal.

I agree with you. It may be caused by some other corrupted code. Need time to test it out. Once it happened again, will switch the IsThreadSafe flag off and test the addin again.

**Comment by dreamershl** [comment]
Just for sharing. not sure whether I can't use the static variable in the thread safe UDF even just for reading access only.

"Use thread-local memory for thread-specific storage, and replace static variables within functions with thread-local variables."

**Comment by govert** [comment]
Where are you quoting from?

On 28 Feb 2016, at 15:59, Shen liang <notifications@github.com<mailto:notifications@github.com>> wrote:


Just for sharing. not sure whether I can't use the static variable in the thread safe UDF even just for reading access only.

"Use thread-local memory for thread-specific storage, and replace static variables within functions with thread-local variables."

**Comment by dreamershl** [comment]
It is from MSDN "Registering XLL Functions as Thread Safe"

https://msdn.microsoft.com/en-us/library/office/bb687899.aspx

**Comment by dreamershl** [comment]
Without any change, the issue is gone after I reinstall my PC. not sure whether my development environment is the reason for all these strange issue. Basically it is very safe to use the multithread Excel calculation as long as the function itself is thread safe.
