### ISSUE TITLE
Review startup error handling

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#627]
From this discussion: https://groups.google.com/g/exceldna/c/U5tHPPIYI14

We should check that if the plain .NET 6 runtime is installed but not the Desktop runtime, that we give a sensible message.
Also check that we are handling and displaying other load errors ?

**Comment by elan-slovelock** [comment]
We have noticed silent crashing during ExcelDna startup for some users. This seems to occur when they have `Microsoft.WindowsDesktop.App 6.0.0` installed but nothing later. We have been building with newer versions of the dotnet SDK (e.g. 6.0.18) and ExcelDna 1.7.0-rc*. I think this is related to https://github.com/dotnet/core/pull/7346. This might be a useful thing to investigate when looking at these startup errors.

**Comment by elan-slovelock** [comment]
Also related to this topic, in [DnaLibray.AutoOpen](https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.Integration/DnaLibrary.cs#L305) (and AutoClose) it would be useful to have an explicit catch block for [TargetInvocationException](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.targetinvocationexception?view=net-7.0) so you can log the `InnerException` which is more useful. This generally wraps any exception thrown from the invoked method.

**Comment by govert** [comment]
With https://github.com/Excel-DNA/ExcelDna/pull/635 and related updates we've improved the error information.  We've also set  .NET 6.0.2 is the minimum version supported for Excel-DNA, according to my understanding of https://github.com/dotnet/core/pull/7346.
