### ISSUE TITLE
What members present in root Excel Application?

### ISSUE THREAD

**Issue by AAlex-11** [Excel-DNA/ExcelDna#629]
Imports ExcelDna.Integration
      Imports Microsoft.Office.Interop.Excel

      Public Module Module1
          Public Sub Colorize()
              Try
                  Debug.WriteLine("Start")                   'working
                  Dim Xl = ExcelDnaUtil.Application    'working
                  Dim Wbs = Xl.Workbooks                        '  Public member 'Workbooks' on type 'Application' not found.
                  Dim Range1 As Range = Xl.Range($"A1:Z{Num}")    '  Public member 'Range' on type 'Application' not found.
                  ...

              Catch ex As Exception
                  MsgBox(ex.Message)
              End Try
          End Sub
      End Module

**Comment by govert** [comment]
The object returned from `ExcelDnaUtil.Application` is the root Excel Application object.
You can type the variable as 'Application' (meaning Microsoft.Office.Interop.Excel.Application) and will see the members you expect:
```
            Dim Xl As Application = ExcelDnaUtil.Application
```

**Comment by AAlex-11** [comment]
Thank you, this is solution

**Comment by AAlex-11** [comment]
@govert , however I don't understand how this project is working at all. For example, I receive reference to Range.

         Dim Range1 As Range = Xl.Range($"A1:Z1")
         For Each One As Range In Range1
                   Debug.WriteLine (One.Value )            'Value present
                   Debug.WriteLine (One.Interior.Color )   'Missing ??? Why ???


If we click to Range definition 


              [ComImport]
              [InterfaceType(2)]
              [Guid("00020846-0000-0000-C000-000000000046")]
              [TypeLibType(4096)]
              public interface Range : IEnumerable
              .....


However Interior property present in Excel definition



![DNA-07222023_130105_1](https://github.com/Excel-DNA/ExcelDna/assets/138773344/604aff5b-67b0-4541-8e2b-c31c6fc8de12)

How is possible that one property is present, but second property is missing?

**Comment by govert** [comment]
Does it work when you compile and run it?

I do see a warning from the compiler flash up that says (for any public property on `Range`) that it is not found??I'm not sure why the compiler thinks the member is not there, but for me it compiles, runs and works correctly.

(I'm using the `ExcelDna.Interop` package from NuGet to get a reference to the interop assemblies, and not referencing then directly as "COM References" from my project.)

**Comment by AAlex-11** [comment]
Thank you, @govert . I don't knoq what happens today. Yesterday, my code working with mistake. Today code is working !!!
I want to understand how is possible to create custom functions for sheet using VB.NET and finally it's done! Thank you.


![DNA-07232023_145654_1](https://github.com/Excel-DNA/ExcelDna/assets/138773344/67dc93e3-fc31-4567-b166-a2ab29325b1b)
