### ISSUE TITLE
Assertion Failed on users machine

### ISSUE THREAD

**Issue by femimada** [Excel-DNA/ExcelDna#654]

**Comment by govert** [comment]
What is the exact Excel-DNA version you are using?

**Comment by femimada** [comment]
Using version 1.6.0

**Comment by govert** [comment]
I suggest you try 1.7.0. That should at least give you an error code or better message

**Comment by govert** [comment]
But I see the problem - the user must have the "WindowsDesktop" version of the .NET 6 runtime installed.

**Comment by femimada** [comment]
Thank you Govert. I will update the Excel DNA version. Which runtime version is compatible with Excel DNA? My prior understanding is that it is compatible with any .NET 6 runtime.

**Comment by govert** [comment]
You need the .NET Desktop Runtime of the same bitness (32-bit or 64-bit) as your Excel installation:
![image](https://github.com/Excel-DNA/ExcelDna/assets/414659/9242ac86-cd3c-44c0-9ee1-47c966d69ad5)

**Comment by femimada** [comment]
Thank you Govert.  Updating the package was helpful - it provided more useful information regarding the error.  The issue was ultimately resolved by using the correct .NET runtime.
