### ISSUE TITLE
How much money is needed to make it .net 8 compatible?

### ISSUE THREAD

**Issue by maxima120** [Excel-DNA/ExcelDna#672]
1. the background - nobody is using .net framework in new projects. almost everyone is upgrading their .net 7 projects to .net 8 as we speak.
2. hence there is no future for excel dna in .net if it doesnt keep up with progress. do or die situation
3. ergo - in couple years you become a museum curiousity, hard-core fun club of retired developers. an atari pixelated game for nostalgic misfits

Question - how much do you need to make it .net 8 ? i am sure if you (or someone you trust) run a crowd sourcing campaign you get enough interest.

thoughts?

**Comment by govert** [comment]
Excel-DNA is registered on [GitHub Sponsors](https://github.com/sponsors/Excel-DNA/) and any contribution you can make (small, large, monthly or once-off) will be very welcome, encourages further development and support, and ensures the project can stay open source.

Excel-DNA supports the .NET core series of runtimes, subject to the constraints and difficulties presented to us by the priorities and choices made by those currently in charge of the .NET runtime. I understand that the future of .NET and hence Excel-DNA, is represented by progressive runtime development path. The current release of Excel-DNA (v1.7.0) supports .NET 6, and our latest pre-release supports newer versions too, including .NET 8. 

.NET Framework 4.x is a very stable implementation of the runtime, with great add-in hosting and isolation features. It is installed and serviced as part of the operating system and will be a stable platform to target with guaranteed support at least into the 2030s. These are serious advantages to many current and future add-in developers, making it the best choice in many cases and one Excel-DNA will also support for many years to come.



> Question - how much do you need to make it .net 8 ?
