### ISSUE TITLE
Excel Crash after Close

### ISSUE THREAD

**Issue by konne** [Excel-DNA/ExcelDna#69]
Hi Govert,

since the new Version I get very often after the close of Excel the following short crash and restart windows. I have no idea howto debug this. I have attached a small sample project and a recorded video of the screen in second 22 you see that message for about 1-2 seconds.

bye Konrad

[ExcelDNA_Crash.zip](https://github.com/Excel-DNA/ExcelDna/files/193671/ExcelDNA_Crash.zip)
[ExcelDNA_Crash.zip](https://github.com/Excel-DNA/ExcelDna/files/193673/ExcelDNA_Crash.zip)

**Comment by govert** [comment]
Hi @konne - I can't see a project, only the video.
Do you have a small project that reproduces the issue?

Crashing when closing can happen if you try to talk to Excel after it has started to close.

**Comment by govert** [comment]
If you mean that an empty project causes this - what other add-ins are loaded?

**Comment by konne** [comment]
Hi Govert,
I have also attached as second zip (unfortunatelly the same name) a small nearly empty project.
But this is comming from my large sense excel project.

bye Konrad

**Comment by konne** [comment]
Sorry here the small project with I recorded the video-
[ExcelDNATest.zip](https://github.com/Excel-DNA/ExcelDna/files/193719/ExcelDNATest.zip)

**Comment by govert** [comment]
So it's an empty project.

Excel-DNA doesn't run code when you close Excel in this case.
It's not a problem I have or that I think other people have (crashing when closing an empty project).

What version of Excel and Visual Studio (including Updates / Service Packs)?
Any other add-ins (COM or .xll or .xlam) loaded?
Does it only happen when debugging?

**Comment by govert** [comment]
You can also check in the Windows event log for the crash details.

**Comment by konne** [comment]
Hi Govert,
I know that this is an empty project. This happens with a huge project a small and also with an empty project.
I have Windows 10, VS 2015 newest SP, Excel 2016
This happens usally only with debug from VS2015 but sometimes also with release build that are started direct with excel.
In the windows eventlog there is this wonderful message :-)

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-03-29T15:01:52.000000000Z" /> 
  <EventRecordID>1039558</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>XXXXXXXXX</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>EXCEL.EXE</Data> 
  <Data>16.0.6568.2036</Data> 
  <Data>56d69749</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.10240.16683</Data> 
  <Data>56ad9704</Data> 
  <Data>c0000005</Data> 
  <Data>000000000002ec74</Data> 
  <Data>5368</Data> 
  <Data>01d189cbbc259577</Data> 
  <Data>C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE</Data> 
  <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data>df10803d-5758-496a-983f-5bbf501147df</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by govert** [comment]
OK - from the event log we can see it's an access violation (code c0000005).
Do you see it under older Excel versions?

**Comment by govert** [comment]
Can you confirm this does not happen when you use the previous NuGet package (Install-Package Excel-DNA -Version 0.32.0)?

**Comment by konne** [comment]
It's also under 0.32.0, so I just thought that it comes from the update.
For the Excel Version I'm not shure. I think I have seen it already at a customer with 2013, but I had at that time no chance to evaluate if it is the same error.
Any Ideas how to get the root cause / debug this?

**Comment by govert** [comment]
Excel 2016 and VS 2015 crashing with an AV at the end of a debug session should not be a concern - that's just some bug in one of the Microsoft pieces.

Do you have a reproducible way to crash when not debugging?

**Comment by konne** [comment]
>Excel 2016 is certainly still buggy.
Yes, but my customers are using it already

>Do you have a reproducible way to crash when not debugging?
At the moment not, I will close that Issue and if I found to reproduce it without debugging I will make a new Issue.
Thx for your help.

**Comment by govert** [comment]
Getting the event log info for such a crash is useful.

**Comment by govert** [comment]
If you want to pursue the deugging case further, you can check that it happens with a small VSTO add-in too, then report to Microsoft.
