### ISSUE TITLE
ExcelDNA support independent deployment?

### ISSUE THREAD

**Issue by zzzqgrelax** [Excel-DNA/ExcelDna#697]
I migirate an addin from .NET 4.6.2 to .NET6  and it works well with vs ide
when i publish the project with  --self-contained true 
throw many exceptions like 1>Assembly at bin\Release\net6.0-windows\win-x86\Microsoft.CSharp.dll could not be packed. Possibly a mixed assembly? (These are not supported yet.)   
does it not support?
and .net6 addin can only load with runtime installed in system?

**Comment by govert** [comment]
We currently don't support the self-contained runtime option. You need to have the runtime (in fact the Desktop runtime) installed.
Not supporting the self-contained option is a limitation of the .NET hosting interface we're using, though I can't remember the details exactly.

**Comment by zzzqgrelax** [comment]
ok   thanks
