### ISSUE TITLE
ExcelDnaPack has a problem with output file paths without directory component

### ISSUE THREAD

**Issue by phrrngtn** [Excel-DNA/ExcelDna#7]
from https://exceldna.codeplex.com/workitem/9366

Me:
> I had to be very careful with the command-line arguments to ExcelDnaPack. My previous comment about packing failing was due to omitting leading '.\ ' from the paths and had nothing to do with mixed-mode assemblies (I incorrectly thought it had something to do with this as I had a reference to a mixed mode assembly in the solution but was not referencing it in the anywhere else in the code nor in the .dna)

Govert:
> Are you saying that it makes a difference to ExcelDnaPack whether put the arguments as ".\XXX.dna" vs. just "XXX.dna"? Do you have any idea why that would be?

Reproduce by omitting the leading .\
```
C:\work\DummyCTP\DummyCTP\bin\Debug>ExcelDnaPack.exe DummyCTP.dna /O DummyCTP.xll /Y
Output directory could not be created. Error: Path cannot be the empty string or all whitespace.

Exiting ExcelDnaPack.
```
The problem appears to be with this line:
```
   string outputDirectory = Path.GetDirectoryName(xllOutputPath);
```

I found that specifying a leading .\ on the output argument is sufficient.

```
C:\work\DummyCTP\DummyCTP\bin\Debug>ExcelDnaPack.exe DummyCTP.dna /O .\DummyCTP.xll /Y
Using base add-in C:\tools\ExcelDna.xll
  ->  Updating resource: Type: ASSEMBLY_LZMA, Name: EXCELDNA.INTEGRATION, Length: 60651
  ->  Updating resource: Type: CONFIG, Name: __MAIN__, Length: 524
  ~~> ExternalLibrary path DummyCTP.dll resolved to C:\work\DummyCTP\DummyCTP\bin\Debug\DummyCTP.dll.
  ->  Updating resource: Type: ASSEMBLY_LZMA, Name: REINSCTP, Length: 4959
  ~~> Assembly path NLog.dll resolved to C:\work\DummyCTP\DummyCTP\bin\Debug\NLog.dll.
  ->  Updating resource: Type: ASSEMBLY_LZMA, Name: NLOG, Length: 119256
  ->  Updating resource: Type: DNA, Name: __MAIN__, Length: 1035
Completed Packing .\DummyCTP.xll.

```

I will check out a couple of these suggestions for command-line processing (not my favorite topic!) and see if any of them look appropriate
http://stackoverflow.com/questions/491595/best-way-to-parse-command-line-arguments-in-c

**Comment by govert** [comment]
OK great - that just looks like a bug with the blank outputDirectory - it should have a sensible default.

I don't want to complicate the ExcelDnaPack too much, though I agree command line handling is rather primitive...

**Comment by phrrngtn** [comment]
I like using docopt for Python. There is a C# port, https://github.com/docopt/docopt.net but I ended up with the simple workaround.

**Comment by govert** [comment]
Cool - thanks!
