### ISSUE TITLE
Create Setup Project (.exe) to install XLL addin

### ISSUE THREAD

**Issue by zmarwa** [Excel-DNA/ExcelDna#70]
Hello,
I 've created an XLL ADD-IN which contains UDFs with Excel-DNA integration. I just want to create a setup that install My XLL. Is that possible??

Also, does the installation of XLL-ADDIN add new entries in the registry (Like Automation Add-IN). Or how Excel finds Functions created in XLL ??

best regards,
zm

**Comment by govert** [comment]
You can find a template project for a WiX installer here: https://github.com/Excel-DNA/WiXInstaller

There is a registry entry that tell Excel about your add-in, so that it is loaded when Excel starts (equivalent to what Excel does when you manually install the add-in with the "Alt-t,i" Add-Ins dialog box).

**Comment by zmarwa** [comment]
Thank you for your fast reply!
Only for a WiX installer? Is there a way to use Visual Studio Installer?

How to check if the XLL is installed in the registry?

**Comment by govert** [comment]
Another alternative is for the add-in to self-install when you double click it (just add to the Excel AddIns collection in AutoOpen if it isn’t there).

I have no recent experience with the old Visual Studio Installer, but the registry check is tricky (you need some code in a custom action to do it).
You need to enumerate through keys called OPEN, OPEN1, OPEN2, OPEN3 etc. to find a slot for your add-in.

The Excel registry entries for .xll add-ins are discussed here: http://stackoverflow.com/questions/18602560/how-to-deploy-an-excel-xll-add-in-and-automatically-register-the-add-in-in-excel and here: https://groups.google.com/forum/#!msg/exceldna/d2ogsPkv6YM/NGnSrU9tmpMJ
