### ISSUE TITLE
Exception in QueueAsMacro method cannot be handlered by RegisterUnhandledExceptionHandler

### ISSUE THREAD

**Issue by kchen0723** [Excel-DNA/ExcelDna#71]
ExcelIntegration.RegisterUnhandledExceptionHandler can register a exception handler. We hope this is a global exception handler. 
But this handler cannot handle the exception which is raised from ExcelAsyncUtil.QueueAsMacro.

Steps to reproduce:
In the AsyncMacros.dna, change method as below:
    public static DateTime asyncWriteWithCApi()
    {
        ExcelAsyncUtil.QueueAsMacro(
            delegate
            {
                var refB1 = new ExcelReference(0, 0, 1, 1, "Sheet1");
                refB1.SetValue("Done writing...!");
                throw new Exception("testing exception");
            });

        return DateTime.Now;
    }

We hope this exception will be caught by the register handler. but actually it cannot. The LogDisplay will be shown instead.

**Comment by kchen0723** [comment]
It because in SyncMacro() of ExcelSynchronizationContext.cs, The excel DNA invoked the macro, catch the error and use the default logger to log it. 
here Could we use the RegisterUnhandledExceptionHandler to handler it? We hope this handler is a global handler.

**Comment by govert** [comment]
I agree - that is a place where the UnhandledExceptionHandler should be called.

**Comment by kchen0723** [comment]
Thanks for your comment. Should I make a pull request to fix it?

**Comment by govert** [comment]
Yes, thank you - a pull request would be great.

**Comment by kchen0723** [comment]
This issue has been fixed. We can close this ticket now.
