### ISSUE TITLE
"Excel API is unavailable - cannot retrieve Application object" is back

### ISSUE THREAD

**Issue by alainbryden** [Excel-DNA/ExcelDna#72]
Hey Govert,

This issue appears to be back in version 0.33.9. Since updating, my add-in has been working fine on my computer, but as soon as I go to test it on a new machine **that hasn't previously run the add-in**, I get this error.

the add-in loads initially, but as soon as they execute a function that requires ExcelDnaUtil.Application, an exception is thrown with the message "Excel API is unavailable - cannot retrieve Application object". By repeating the action, the error was thrown every time.

It looks like after instructing the users to shut down Excel, restart, and try again - they didn't experience the error a second time. Neither has seen it come back again since, but it can be reproduced by opening the machine on another machine that hasn't run the add-in before.

If it matters, I'm now also targetting .Net 4.5 since updating to ExcelDNA 0.33.9 from Nuget. All of the machines that encountered the error were running Office 2013.

**Comment by govert** [comment]
Maybe you can try a really simple add-in, just the .xll file and a .dna file:

```
<DnaLibrary RuntimeVersion="v4.0" Language="C#">
<![CDATA[
    using ExcelDna.Integration;

    public class AddIn : IExcelAddIn
    {
        public void AutoOpen()
        {
            try
            {
                dynamic app = ExcelDnaUtil.Application;
                XlCall.Excel(XlCall.xlcAlert, "Hello from Excel-DNA - running in Excel version " + app.Version);
            }
            catch (Exception ex)
            {
                XlCall.Excel(XlCall.xlcAlert, "Error from Excel-DNA: " + ex.Message);
            }
        }
        
        public void AutoClose()
        {
        }
    }
]]>
</DnaLibrary>
```

**Comment by govert** [comment]
@alainbryden Are you able to reproduce this issue, or can I close?

**Comment by alainbryden** [comment]
Hi @govert, Sorry, I've been an absentee open source contributor this year - I haven't had a chance to build and test your minimal add-in. Feel free to close this, and I'll be sure to re-open with additional information if and when I've had a chance to investigate the issue further.

**Comment by govert** [comment]
@alainbryden OK - I'll close it for now.
