### ISSUE TITLE
MasterBuild error NETSDK1047 ExcelDnaPack doesn't have a target for 'net452/win-x86'

### ISSUE THREAD

**Issue by Sergey-Vlasov** [Excel-DNA/ExcelDna#730]
With .NET SDK Version: 9.0.100-rc.1.24452.12 or 9.0.100-rc.2.24474.11 installed.

Running MasterBuild\MasterBuild.cmd gives:

```
(ResolvePackageAssets target) -> 
  C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1047: Assets file 'Source\ExcelDnaPack\obj\project.assets.json' doesn't have a target for 'net452/win-x86'. Ensure that restore has run and that you have included 'net452' in the TargetFrameworks for your project. You may also need to include 'win-x86' in your project's RuntimeIdentifiers. [Source\ExcelDnaPack\ExcelDnaPack.csproj::TargetFramework=net452]
```

**Comment by Sergey-Vlasov** [comment]
A workaround is to change

`<RuntimeIdentifiers>win7-x86;win7-x64</RuntimeIdentifiers>`

to

`<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>`

in Source\ExcelDnaPack\ExcelDnaPack.csproj.

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Sergey-Vlasov** [comment]
Can be related to [.NET SDK uses a smaller RID graph](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph)

"Use portable RIDs, for example, linux-<arch>, linux-musl-<arch>, osx-<arch>, and win-<arch>, instead of version-specific or distro-specific RIDs, such as ubuntu.16.04-<arch>, osx.10.11-<arch>, and win10-<arch>."

**Comment by Sergey-Vlasov** [comment]
The same error with .NET SDK 9.0.100 RTM.
