### ISSUE TITLE
Does it work with .NET 9?

### ISSUE THREAD

**Issue by nsulikowski** [Excel-DNA/ExcelDna#737]
It says .NET 6 and higher. It worked with .NET 8... so I'm assuming it'll work with .NET 9.
Can you confirm before I modify my code?
Best,
Nestor

**Comment by govert** [comment]
Hi Nestor,
I'm also assuming so, but have not tested.
It would be great if you can confirm after modifying your code.
-Govert

**Comment by nsulikowski** [comment]
It seems to work!

**Comment by govert** [comment]
Yay! Thanks for coming back @nsulikowski :-)
