### ISSUE TITLE
ExcelDna.Loader.XlAddIn.Initialize call failed 

### ISSUE THREAD

**Issue by akothoor** [Excel-DNA/ExcelDna#75]
![image](https://cloud.githubusercontent.com/assets/14793205/14891318/34664aba-0d34-11e6-939c-db663bfb2587.png)

While debugging, the add-in worked fine. But once I added the WixInstaller and after installing the Add-In, on opening Excel this is the error that keeps popping-up. Do you have any idea how this can be resolved ?

Thanks!

**Comment by govert** [comment]
Is there a file called ExcelDna.Integration.dll next to the location of the installed .xll file?

If there is, then you should delete it.

Otherwise, you need to check whether a simple Excel-DNA add-in works on that machine. Perhaps there is an anti-virus blocking things.

**Comment by akothoor** [comment]
No, there is no dll in that directory. I think it is the new version of ExcelDNA I am using. I already have an add-in installed on version 0.32. When I installed another new add-in on version 0.33.57.. this error started to pop-up.

**Comment by govert** [comment]
@akothoor Is ths still a problem for you, or can I close the issue?

**Comment by akothoor** [comment]
@govert  It's resolved, I don't see this error anymore. You can close this issue. Thanks!

**Comment by ronnydedecker** [comment]
the code in MainAddIn with interface IExcelAddIn  causes load error.

[ExcelDnaClassLibraryExemple.zip](https://github.com/Excel-DNA/ExcelDna/files/2401155/ExcelDnaClassLibraryExemple.zip)
![capture](https://user-images.githubusercontent.com/37349740/45817166-66929480-bccd-11e8-881b-8c27581d08a7.PNG)


I already went on your blog 
https://groups.google.com/forum/m/?hl=en.-#!topic/exceldna/mCnua6uFuWk

**Comment by ronnydedecker** [comment]
maybe this belongs not here
