### ISSUE TITLE
Working with App.Config files

### ISSUE THREAD

**Issue by interdrift** [Excel-DNA/ExcelDna#8]
I find working with the App.Config file a really hard task. I have been wondering on how to actually ease  my pain and I found a solution which seems to work partially : It gets done through a class that I found on SO :

Is there a better way to actually work with an app config file that is already built in? If not, would you consider integrating the class I have been using? The problem is that whenever I use the ConfigurationManager Excel looks for the config file in MyDocuments since that is the default working directory for Excel.

**Comment by govert** [comment]
The links seem to missing.

**Comment by interdrift** [comment]
https://gist.github.com/interdrift/b26b1eb39555841bd703

You can check it out over here. I will attach the SO answer as soon as I find it to give the credits to the person who answered it.

**Comment by govert** [comment]
Is the problem only when you are trying to write to the .config file?

**Comment by interdrift** [comment]
No, it is happening whenever I use the ConfigurationManager in read/write operations.

**Comment by govert** [comment]
Read should not be a problem. The .xll.config file is set as the configuration file when the AppDomain is created. AppSettings and NLog configuration in that file work fine. Writing might be a different story...

**Comment by govert** [comment]
Anyway, I wouldn't like to add code to Excel-DNA that sets private fields in the ConfigurationManager via reflection. But if it works in your add-in, that's OK.

**Comment by Turhan8** [comment]
`ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None).FilePath` returns 
`C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE.config`
What am I missing?

**Comment by govert** [comment]
You are not missing anything - you're just looking at pretty old information and I'm guessing you are targeting .NET 6 now.

The old configuration system does not work the same in the new runtime. In particular, when targeting .NET Framework, there is an AppDomain for every add-in, and the AppDomain has an associated .config file when Excel-DNA sets up. But when targeting .NET 6, there are no AppDomains anymore, so no implicit configuration file per add-in. Hence, you just have the Excel configuration file is the implicit configuration that you can access. Unfortunately there are various other issues with the `System.Configuration.ConfigurationManager` usage under .NET 6.

So if you are targeting .NET 6, I suggest you investigate the newer `Microsoft.Extensions.Configuration` libraries - see https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration

**Comment by Turhan8** [comment]
I am not using Microsoft.Extension.Configuration but I have a different problem. Why does it look for machine.config in the directory of the add-in? I would be grateful if you could help me to prevent these exceptions. I shared details of this problem here https://github.com/Excel-DNA/ExcelDna/issues/608

This is how I get the config now:
```
try
{
    var path_default = $"{currentDirectory}\\appsettings.json";
    var path_environment = $"{currentDirectory}\\appsettings.{environmentName}.json";

    var configBuilder = new ConfigurationBuilder();
    configBuilder.AddJsonFile(path_default, optional: true, reloadOnChange: true);
    configBuilder.AddJsonFile(path_environment, optional: true, reloadOnChange: true);
    var config = configBuilder.Build();
    return config;
}
catch (Exception ex)
{
    Log.Error(ex, "Error in configuration setup");
    return null;
}
```
