### ISSUE TITLE
ExcelRibbon causing "Microsoft Excel has stopped working" exception when deactivating the add-in in Excel

### ISSUE THREAD

**Issue by davidandersen** [Excel-DNA/ExcelDna#81]
I'm finding that Excel throws a dialog exception box with "Microsoft Excel has stopped working" when I close down Excel after I've deactivate the add-in from the native Excel Add-Ins manager. I'm finding this is happening with version 0.33.9, but used to work with 0.32.0. The add-in itself functions properly, it's just that it throws this exception when shutting Excel down. It seems to be associated with the inclusion of a custom ribbon and a class that inherits from <code>ExcelRibbon</code>.

Please help, this is causing some issues for us and our slew of add-ins.

Thanks!
## The Configuration
- ExcelDna version 0.33.9
- Windows 7
- Excel 2010 version 14.0.7151.5001 (64 bit)
- Tested on multiple machines and getting the same behavior

Attached is a sample project that can be used, but here is a summary of what I'm doing and the behavior that I'm seeing.
## The Code

I have a class named MyAddIn that looks something like below.

``` CSharp
using System;
using ExcelDna.Integration;

namespace ExcelDna.ExcelRibbonException
{
    public class MyAddIn : IExcelAddIn
    {
        public void AutoOpen()
        {
        }

        public void AutoClose()
        {
        }

        [ExcelFunction(Name = "NewGuid", Description = "Returns a new GUID.", IsVolatile = true)]
        public static string NewGuid()
        {
            return Guid.NewGuid().ToString();
        }
    }
}
```

Secondly, I'm also declaring a ribbon in the .dna file which looks something like this:

``` XML
<DnaLibrary Name="ExcelDna.ExcelRibbonException Add-In" RuntimeVersion="v4.0">
  <ExternalLibrary Path="ExcelDna.ExcelRibbonException.dll" LoadFromBytes="true" Pack="true" />

  <!-- 
       The RuntimeVersion attribute above allows two settings:
       * RuntimeVersion="v2.0" - for .NET 2.0, 3.0 and 3.5
       * RuntimeVersion="v4.0" - for .NET 4 and 4.5

       Additional referenced assemblies can be specified by adding 'Reference' tags. 
       These libraries will not be examined and registered with Excel as add-in libraries, 
       but will be packed into the -packed.xll file and loaded at runtime as needed.
       For example:

       <Reference Path="Another.Library.dll" Pack="true" />

       Excel-DNA also allows the xml for ribbon UI extensions to be specified in the .dna file.
       See the main Excel-DNA site at http://excel-dna.net for downloads of the full distribution.
  -->
  <CustomUI>
    <customUI xmlns='http://schemas.microsoft.com/office/2009/07/customui' loadImage='LoadImage'>
      <ribbon>
        <tabs>
          <tab id='myTab' label='My Tab'>
            <group id='myGroup' label='My Group'>
              <button id='myButton' label='Press Me' size='large' />
            </group>
          </tab>
        </tabs>
      </ribbon>
    </customUI>
  </CustomUI>
</DnaLibrary>
```

Thirdly, I have a class named MyRibbon that is ComVisible and it looks something like this.

``` CSharp
using System.Runtime.InteropServices;
using ExcelDna.Integration.CustomUI;

namespace ExcelDna.ExcelRibbonException
{
    [ComVisible(true)]
    public class MyRibbon : ExcelRibbon
    {
    }
}
```
## The Behavior

Here are the steps that I'm taking that is resulting in the exception:
1. Open Excel
2. Go to the **Developer** tab and click on **Add-Ins**.
3. Click on **Browse**, locate the 64 bit packed .xll, e.g. <code>..\ExcelDna.ExcelRibbonException\ExcelDna.ExcelRibbonException\bin\Debug\ExcelDna.ExcelRibbonException-AddIn64-packed.xll</code>
4. Click **OK**
5. See that the **My Tab** tab was added.
6. Also see that the <code>NewGuid()</code> function is working, e.g. go to any cell an type in <code>=NewGuid()</code>
7. Go to the **Developer** tab and click on **Add-Ins**.
8. Uncheck the box next to ExcelDna.ExcelRibbonException Add-In (this does not cause any issues).
9. Close out of Excel. This will cause the below exception to be thrown.

![image](https://cloud.githubusercontent.com/assets/2736161/15549049/ad3bef36-225f-11e6-80ef-8655c40cd7d5.png)
## The Sample Project

[ExcelDna.ExcelRibbonException.zip](https://github.com/Excel-DNA/ExcelDna/files/282498/ExcelDna.ExcelRibbonException.zip)

**Comment by konne** [comment]
Hi, I already reported that issue and this happens for me only in the debug mode with VS and not with the release compile. This is the reason I ignoer it.
bye Konrad

**Comment by davidandersen** [comment]
Thanks Konrad, but I am seeing this happen with both the Debug and Release versions.

**Comment by konne** [comment]
Hi David, do you start the release from Visual Studio, or do you open the XLL separate with Excel. bye Konrad

**Comment by davidandersen** [comment]
I do not get the error when calling the .xll directly, e.g. calling it from Visual Studio or opening it via Explorer. I am only getting the error when opening Excel first, loading and enabling, then disabling and closing down.

Thanks.

**Comment by konne** [comment]
What Excel do you use. If I use Excel 2016 I only get the same error if I start it with Visual Studio.

**Comment by davidandersen** [comment]
Excel 2010.

**Comment by govert** [comment]
@davidandersen I believe you are running into issue #61, which was fixed in commit 0ea3ed668427d0b43d2597a2113c5728b45e7134 in February. So it should be fixed in the current source and for the next release (0.34) which I'm currently working on.

@konne I think the debugging crash you are referring to is completely unrelated to Excel-DNA and occurs on exiting whenever you started Excel 2016 under the Visual Studio debugger. Perhaps you can add your voice to this discussion on MSDN: https://social.msdn.microsoft.com/Forums/office/en-US/cfda89a1-f1f9-4a09-bdf5-068880fc8e60/excel-2016-crashes-after-a-debug-session?forum=exceldev

**Comment by davidandersen** [comment]
Thanks @govert -- much appreciated!

**Comment by govert** [comment]
@davidandersen Thank you for your detailed error report.
There is still an issue in this regard, which I'm keeping track of under #67. The add-in you are unloading is not completely released from the Excel process if it activated some COM features (like the Ribbon support). I think Excel-DNA would have to do some extra bookkeeping to be able to release properly. I've not give that any more attention yet.

**Comment by davidandersen** [comment]
@govert -- Thanks for the heads up and the feedback. I'll stay tuned and let you know if I come across anything else. Again, much appreciated.

**Comment by Christopherjjdl** [comment]
Just to extend this issue, not sure whether this is a new issue. 

This only appears to happen in Excel 365, as i cannot replicate them on my machine which has 2013. But when closing Excel 365 that has an addin with COM features then opening a it again the COM features don't load up, no error messages occur. This is also stopping the load of the other addins. To get them working again they have to go to the addins menu, uncheck and check the addins. 

I am guessing that when they close excel the addins are not released from the excel process, and opening excel causes it to not load properly. But i do not pretend to understand the intricacies of how Excel-dna works.
