### ISSUE TITLE
Ribbon from .dna file is not loaded

### ISSUE THREAD

**Issue by buybackoff** [Excel-DNA/ExcelDna#88]
Spent hours to make a ribbon work from C# project (repo from another machine where everything worked a while ago in Excel 2015, current Excel version is 2010. Also tried brand new projects). Then I found that the F# ribbon [sample](https://github.com/Excel-DNA/Samples/tree/master/FSharpRibbon) worked (it uses `GetCustomUI` overload of `ExcelRibbon`), even after updates to 33.9 from 32.0. But strangely - the same approach wasn't working from C# anyway. The same code and references - I was checking line by line - refused to load a ribbon from C# project. Then I added `[ComVisible(true)]` to the class that inherits from `ExcelRibbon` and the `GetCustomUI` method started working from C# - finally!

So I probably narrowed down the issue to default COM visibility (there is no `[ComVisible(true)]` attribute in F#, but it just works), but couldn't quickly understand how the text from `.dna` files is processed inside the `ExcelDna.Integration` project. I am kind of OK now with inheriting from `ExcelRibbon`, but something doesn't work out of the box as expected.

**Comment by buybackoff** [comment]
Nevermind! When I found a working solution I jumped to another problem (seemingly two static classes, which is caused by double dll load) and found an answer [here](https://groups.google.com/forum/#!topic/exceldna/xyV6SlhrJ1w) (even both answers). After adding the `ComVisible` attribute the ribbon definition in the .dna file started working as well. It is strange that the same AddIn in Excel 2015 worked without that attribute (as well as F#).

**Comment by govert** [comment]
By default, .NET assemblies are COM visible.
The C# project template adds [assembly:ComVisible(false)] to the AssemblyInfo.cs. There's a project property setting that will also set this assembly-wide default. Perhaps your previous project had this set.
You can then override this assembly setting for a particular class, as you've done now.

**Comment by buybackoff** [comment]
Yes, I have found this line! Now everything makes sense, and F# thing as well. Sorry for the noise! :)
