### ISSUE TITLE
ExcelAsyncUtil.Run seems to only run a given result once (regardless how many cells contain that formula)

### ISSUE THREAD

**Issue by stripwax** [Excel-DNA/ExcelDna#89]
Example:  I have a function called XYZ and another function called XYZAsync , which I have implemented simply as:

```
[ExcelFunction(Description = "Async version of XYZ", Category="Mine")]
public static object XYZAsync(object arg1=null, object arg2 = null)
{
    return ExcelAsyncUtil.Run("XYZAsync", new object[] {arg1,arg2}, delegate{ return XYZ(arg1,arg2); });
}

[ExcelFunction(Description = "XYZ", Category="Mine")]
public static object XYZ(object arg1=null, object arg2=null)
{
    // ... do stuff
}
```

As a demonstration, my "do stuff" calculates and returns a random number, different every time.
=XYZ(foo,bar) works fine, but =XYZAsync(foo,bar) seems to always return the same number.  As if it has only actually executed the inner XYZ function once.

I saw some threads referring to a bug in excel-dna 0.32 , which read as if the bug has been fixed in 0.33 and onwards.  I'm using 0.33.9 however and I see this bug.

Hopefully I'm just doing something silly/wrong here.

**Comment by thomasmktong** [comment]
I think I have the a similar problem. When I drag the formula across cells, the result returned is the same. The formula works when I manually type in or copy-paste the formula.

I am using 0.33.9 too.

**Comment by govert** [comment]
If the arguments are the same, that would be expected.

On 3 Oct 2016 10:41 am, Thomas Tong <notifications@github.com> wrote:

I think I have the a similar problem. When I drag the formula across cells, the result returned is the same. The formula works when I manually type in or copy-paste the formula.

I am using 0.33.9 too.

**Comment by thomasmktong** [comment]
Please see the image below. Column A is static value and Column B is async formula which simply display the input. As you can see, the formula I typed in Cell B1 works fine, but when I drag it down to copy to other cells, they cannot show the correct value.

![untitled](https://cloud.githubusercontent.com/assets/7279232/19029124/bf941000-8975-11e6-8dd9-6a0f5408be06.png)

The function's code looks like this.

        [ExcelFunction(Description = "SV_Async", Category = "XXXX - Single Value")]
        public static object SV_Async(params object[] args)
        {
            object asyncResult = ExcelAsyncUtil.Run("SV", string.Empty, 
                delegate()
                {
                    return string.Join(",", args);
                });
            
            if (asyncResult.Equals(ExcelError.ExcelErrorNA))
            {
                return ExcelError.ExcelErrorGettingData;
            }
            return asyncResult;
        }

I am new to this library. Please advise if I have done anything wrong, thanks!

**Comment by buybackoff** [comment]
Instead of `string.Empty`, put `args` into `ExcelAsyncUtil.Run("SV", ...`, since ExcelDna uses this for hashing of inputs.

**Comment by thomasmktong** [comment]
It works great for me now, thanks very much for your help! @buybackoff and @govert

**Comment by iOZCharlie** [comment]
Hello @stripwax.

I have talked the same problem and then I remember that we are experiencing threading issues, let me explain.

If you use the same variables, those variables will last under the context of the running function, unless those variables have an exclusive place on memory, what you need to do is creating a class that will encapsulate the values ant then pass this class to the ExelAsyncUtil.Run delegate or create an array or another structure that supports memory persistence.

Doing this, the values passed to the Asynchronous delegate will last instead of being wiped by the asynchronous call.
