### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by Yenyenx** [Excel-DNA/ExcelDna#9]
Hi,
I'm quite new to Excel-DNA but already find it really powerful. I seem to me exception handling mechanism in Excel-DNA is not able to catch an exception thrown in C# within user's code. For instance, I have a dummy function named "divide" which takes as argument 2 doubles. In practice, the exception thrown by the null division returns #Value, which does not give me much information about what's happening. 

I would expect Excel-DNA to return the actual Exception message and the name of the main method which throws the exception.

I took a look at the source code and a quick fix in the method HandleUnhandledException could do the trick instead of just returning ExcelError.ExcelErrorValue. What do you think ?

Rgds,
Yenyenx

**Comment by govert** [comment]
Returning a real #VALUE value for errors has some advantages over returning a string, like propagating properly to other formulas, and working with the `IsError()` function. It's also the behaviour of the built-in Excel functions, so I think it's the right default.

You can override the unhandled exception behaviour by registering your own handler with a call to `ExcelIntegration.RegisterUnhandledExceptionHandler(...)`. Your handler can the process the exception (although the parameter is an 'object' it should always be an Exception) and return a string with the information you want to see. Your `IExcelAddIn.AutoOpen()` would be a good place to set this.
