### ISSUE TITLE
Ribbon xml testing

### ISSUE THREAD

**Issue by darul75** [Excel-DNA/ExcelDna#93]
Hi,

I would like to unit test some basic logic on a ribbon **outside the Excel environment**.

This xml ribbon is made of buttons with custom state (enabled/disabled) based on a business arbitrary custom model.

At runtime in Excel it works fine but I would like unit test it, here a very basic scenario.

```xml
...
<button id='login' getEnabled="GetLoginEnabled" />
...
```

```c#
[ComVisible(true)]
public class Ribbon : ExcelRibbon {
    Model myModel;

    public Ribbon(Model myModel) { 
        this.myModel = myModel;
    }

    public GetLoginEnabled() {
        return myModel.loginEnable;
     }

....
}
```

Is it possible to check the status of a button in the ribbon ?

**Comment by govert** [comment]
Well, you'd basically have to mock a whole ribbon implementation. There is no "status of a button" other than in Excel - in other words there is no code in Excel-DNA e.g. in the `ExcelRibbon` class - which corresponds to your button or its `Enabled` state at all. Your `Model` is the only piece outside of Excel that implements the button state.

**Comment by govert** [comment]
What do you actually want to test?

**Comment by darul75** [comment]
First thanks for replying in depth. My tests would just cover model change impacts on the ribbon components.

**Comment by govert** [comment]
OK. If you do want to test inside Excel ,so you get to check the actual ribbon interaction, you'd need some kind of UI Automation framework like "White" to press the buttons, check their state etc.

Can I close this issue, or is there anything related you want to ask?

**Comment by darul75** [comment]
Yeah it sounds good enough for me, TDD in M$ is so much pain ;)
