### ISSUE TITLE
Centering window in middle of excel Application

### ISSUE THREAD

**Issue by darul75** [Excel-DNA/ExcelDna#94]
Hi @govert :)

I have tried to align a window on center of a page but it looks like units are not compatible between the one received from excel and the one expected by wpf.

Do you have any idea ?

```c#
dynamic xlApp = ExcelDnaUtil.Application;

dynamic left = xlApp.Application.Left;
dynamic top = xlApp.Application.Top;
dynamic width = xlApp.Application.Width;
dynamic height = xlApp.Application.Height;

// create ExcelWindowPosition
```

Then placing window:

```c#    
public class MyWindow : Window
{
  // initializing component...
  this.Left = this.ExcelWindowPosition.Left + (this.ExcelWindowPosition.Width - this.Width) / 2;
  this.Top = this.ExcelWindowPosition.Top + (this.ExcelWindowPosition.Height - this.Height) / 2;
```

https://msdn.microsoft.com/en-us/library/microsoft.office.interop.excel._application.left.aspx
https://msdn.microsoft.com/en-us/library/system.windows.window.left(v=vs.110).aspx

**Comment by JamesFaix** [comment]
I've also had problems with this working in WinForms with the Excel PIA.  I don't think it is specific to ExcelDNA.

**Comment by darul75** [comment]
Yes indeed it does not look to be relative to dna, will go back to stackoverflow ;) in the meantime if you have any solutions I take it

**Comment by darul75** [comment]
Finally got it working through dll manner:

```c#
 [DllImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    static extern bool GetWindowRect(IntPtr hWnd, ref RECT lpRect);
    [StructLayout(LayoutKind.Sequential)]
    private struct RECT
    {
        public int Left;
        public int Top;
        public int Right;
        public int Bottom;
    }
``
`
And with ExcelDNA

```c#
dynamic xlApp = ExcelDnaUtil.Application;
int excelHwnd = xlApp.Application.Hwnd;
RECT rect = new RECT();

GetWindowRect(new IntPtr(excelHwnd), ref rect);
```

**Comment by JamesFaix** [comment]
When I had the issue before I think I ended up working around the problem, and not solving it directly.  I used the `System.Windows.Forms.Form.StartPosition` property to set where the window would open the first time.  When the form closed it would save the screen position as a user setting, and when it opened it would load any previously saved location setting.

**Comment by darul75** [comment]
Indeed it looks like a workaround but my solution works everytime ;) and I hope for every excel version. Will test it later and let you know if some issues occur. Anyway thanks a lot for helping me.
