### ISSUE TITLE
CustomMarshaler are not working on 64-bit 

### ISSUE THREAD

**Issue by sanchugh** [Excel-DNA/ExcelDna#98]
Firstly, thank you so much govert for such a great contribution. Brilliant job, Well done !
We are using some of it for getting results from a library but when we run it in 64 bit mode, it doesn't work.
I am wondering if you know how can they work for 64 bit platform ?
Many Thanks,
San

**Comment by govert** [comment]
Excel-DNA is fully supported under 64-bit Excel - the issue here is just about the debug build, as far as I understand.

What problems do you have?

Maybe you're using some other library that doesn't support 64-bit?

-Govert


On 25 Nov 2016, at 14:32, sanchugh <notifications@github.com<mailto:notifications@github.com>> wrote:


Firstly, thank you so much govert for such a great contribution. Brilliant job, Well done !
We are using some of it for getting results from a library but when we run it in 64 bit mode, it doesn't work.
I am wondering if you know how can they work for 64 bit platform ?
Many Thanks,
San

**Comment by govert** [comment]
I think you're asking about the same issue as here: https://github.com/Excel-DNA/ExcelDna/issues/96

If not, maybe you can explain more.

**Comment by sanchugh** [comment]
no it is not, let me explain you in detail: 
We are using a excel based library (call it myLib) in C# application so using your custom marshalers.

The problem is happening while reverse marshaling processing the results in 64 bit. 
I have debug the code and here are the details: 

Inside XlObjectMarshaler class in the following method         
unsafe public object MarshalNativeToManaged(IntPtr pNativeData)
        {
            // Make a nice object from the native OPER
            object managed;
            XlOper* pOper = (XlOper*)pNativeData;
            // Ignore any Free flags
            **XlType type = pOper->xlType & ~XlType.XlBitXLFree & ~XlType.XlBitDLLFree;**

In above line the type returned should be XlTypeArray ( I am getting it when I use 32 bit myLib and build my C# application in 64 bit all is good in x86 world).

However when use 64 bit myLib and compile my C# program in 64 bit, the "type" returned in  
above line is "XlTypeBoolean | XlTypeReference" .

Let me know if you need more info ?

**Comment by govert** [comment]
I think I understand what you mean.
You are acting as if you are Excel, and talking to another .xll add-in?

That code would not normally run for an Excel-DNA add-in under 64-bit Excel (it would use the XLoper12 instead of the Xloper). So it might be that the struct definition is not right under 64-bit (due to different offsets) that the compiler applies. One would need to investigate the packing under 64-bit.

I'm happy to help if you can put together a complete example that I can debug.
You can e-mail me directly.

**Comment by sanchugh** [comment]
Yes you got it correct govert ! Thanks for your valuable suggestions I just saw in your source there is another marshaler XlCustomMarshal12 which believe I need to use for 64 bit and XLoper12 instead of Xloper. Let me try using these first and see it it works. Thank you so much !

**Comment by sanchugh** [comment]
I changed XlOper and XlType with XlOper12 and XlType12 version however still it didn't work. 
The type information is coming as some random number that could be because of different offsets as you said earlier. unfortunately, I can't share the lib (myLib) so I am thinking how can I reproduce this in a sample example without referencing myLib?

**Comment by govert** [comment]
What is the function’s registration string?

It might expect to use Xloper (and not Xloper12) even under 64-bit. But the Excel-DNA signature for Xloper might just not work under 64-bit (i.e. Excel can use it under 64-bit, but Excel-DNA avoids that, which might hide problems with the declaration).

**Comment by sanchugh** [comment]
This is generic function pointer for registering:
        
[UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi, SetLastError = true)]
        [return: MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(XlObjectMarshaler), MarshalCookie = "ret")]
        internal delegate object FunctionPointer
        (
            string function,
            int nargs,
            [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(XlObjectArrayMarshaler), MarshalCookie = "Excel4v")]
            object[] args
        );

Here is how we call the lib:
 var libDir = Path.GetDirectoryName(fullPath);
 KernelFunctions.SetDllDirectory(libDir);  // public extern static bool SetDllDirectory(string lpPathName); 
var libHandlePtr = KernelFunctions.LoadLibrary(libPath); // public extern static IntPtr LoadLibrary(string lpLibFileName);
var funcPointer = KernelFunctions.GetProcAddress(_libHandle, procName); // public extern static IntPtr GetProcAddress(IntPtr hModule, string lpProcName);

// after that we marshal the funcPointer with about generic TDelegate definition
var managedDelegate = Marshal.GetDelegateForFunctionPointer(procAddress, typeof(TDelegate));
managedDelegate.DynamicInvoke(parameters); // finally calling function

**Comment by sanchugh** [comment]
I also tried with 
        [UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi, SetLastError = true)]
        [return: MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(XlObject12Marshaler), MarshalCookie = "ret")]
        internal delegate object FunctionPointer
        (
            string function,
            int nargs,
            [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(XlObjectArray12Marshaler), MarshalCookie = "Excel4v")]
            object[] args
        );
but no luck... :(

**Comment by govert** [comment]
You have to figure out what the registration string is for your function when it registers under Excel - that will confirm what parameter type it expects.

Anyway, I suggest you mail me directly - this is not really a use case related to Excel-DNA.

On 28 Nov 2016, at 19:08, sanchugh <notifications@github.com<mailto:notifications@github.com>> wrote:


I also tried with
[UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi, SetLastError = true)]
[return: MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(XlObject12Marshaler), MarshalCookie = "ret")]
internal delegate object FunctionPointer
(
string function,
int nargs,
[MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(XlObjectArray12Marshaler), MarshalCookie = "Excel4v")]
object[] args
);
but no luck... :(

**Comment by sanchugh** [comment]
As I can see we are just using XlObjectMarshaler and XlObjectArrayMarshaler features out of Excel.DNA within our app (not using Excel at all as you figure out earlier). I tried to find it however couldn't locate it. Do you know where it could be or any function which I debug and can show this registration string ?

**Comment by govert** [comment]
I'm closing, as this is not related to the Excel-DNA usage scenario.
I'm happy to help figure out this marshaling issue for your case if you contact me directly.
